<?php
namespace App\Domain\Characters\Templates;
use App\Domain\Media\CharacterVisuals\CharacterVisualAssetService;use App\Domain\WorldCatalog\CatalogStatus;use App\Models\CharacterClass;use App\Models\CharacterTemplate;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\DB;use InvalidArgumentException;
final class CharacterTemplateService{
private $validator;private $visuals;
public function __construct(CharacterTemplateValidator $validator,CharacterVisualAssetService $visuals){$this->validator=$validator;$this->visuals=$visuals;}
public function save(array $data,CharacterTemplate $template=null,UploadedFile $image=null){unset($data['image']);$requested=$data['status'];if($template&&$template->exists&&$template->characters()->exists()&&$data['code']!==$template->code)throw new InvalidArgumentException('El código no puede cambiar porque la plantilla ya tiene personajes asociados.');$previousBody=$template?$template->body_type:null;$saved=DB::transaction(function()use($data,$template,$requested){$model=$template&&$template->exists?CharacterTemplate::whereKey($template->id)->lockForUpdate()->firstOrFail():new CharacterTemplate();$data['status']=$requested===CatalogStatus::ACTIVE?($model->exists?$model->status:CatalogStatus::HIDDEN):$requested;$model->fill($data);$model->setRelation('characterClass',CharacterClass::whereKey($model->character_class_id)->firstOrFail());$this->validator->validate($model,false);$model->save();return$model;},3);if($image)$this->visuals->replace($saved,$image);if($previousBody!==null&&$previousBody!==$saved->body_type)$this->visuals->syncBodyType($saved);if($requested===CatalogStatus::ACTIVE)$this->setStatus($saved,CatalogStatus::ACTIVE);return$saved->fresh();}
public function setStatus(CharacterTemplate $template,$status){if(!in_array($status,CatalogStatus::values(),true))throw new InvalidArgumentException('Estado no válido.');return DB::transaction(function()use($template,$status){$locked=CharacterTemplate::with(['characterClass','mediaAssets'])->whereKey($template->id)->lockForUpdate()->firstOrFail();$locked->status=$status;$this->validator->validate($locked,$status===CatalogStatus::ACTIVE);$locked->save();return$locked;},3);}
public function deleteImage(CharacterTemplate $template){$this->visuals->delete($template->fresh());}
}
