<?php
namespace App\Domain\Hunts\Sessions;
use App\Domain\Characters\Appearance\CharacterAppearanceService;use App\Domain\Characters\CharacterStatsCalculator;use App\Domain\Equipment\CharacterEquipmentSummaryService;use App\Domain\Hunts\Rewards\HuntRewardService;use App\Domain\Inventory\CharacterInventorySummaryService;use App\Domain\Inventory\Instances\Rarity\ItemRarityVisualStyleResolver;use App\Domain\Media\MediaAssetType;use App\Models\Character;use App\Models\Item;use App\Models\ItemRarity;use App\Models\Zone;
final class HuntingSessionPresentationService{
private $appearance;private $stats;private $equipment;private $inventory;private $rewards;private $rarityVisuals;
public function __construct(CharacterAppearanceService $appearance,CharacterStatsCalculator $stats,CharacterEquipmentSummaryService $equipment,CharacterInventorySummaryService $inventory,HuntRewardService $rewards,ItemRarityVisualStyleResolver $rarityVisuals){$this->appearance=$appearance;$this->stats=$stats;$this->equipment=$equipment;$this->inventory=$inventory;$this->rewards=$rewards;$this->rarityVisuals=$rarityVisuals;}
public function prepare(Character $character,Zone $zone){$breakdown=$this->stats->breakdown($character);return['appearance'=>$this->appearance->presentation($character),'background'=>$this->background($zone),'pending_rewards'=>$this->decoratePendingSummary($this->rewards->summaryPendingForCharacter($character)),'equipment'=>$this->equipment->snapshot($character,$breakdown->equipmentSources())->toArray(),'inventory'=>$this->decorateInventory($this->inventory->snapshot($character)),'stats'=>$this->stats($breakdown->effective())];}
public function decoratePendingSummary(array $summary){$rows=collect($summary['items']);$ids=$rows->pluck('item_id')->unique()->values();$rarityIds=$rows->where('is_unique',true)->pluck('item_rarity_id')->filter(function($id){return$id!==null;})->unique()->values();$items=$this->itemsWithIcons($ids);$rarities=$rarityIds->isEmpty()?collect():ItemRarity::whereIn('id',$rarityIds)->get()->keyBy('id');$summary['items']=array_map(function($row)use($items,$rarities){$row['image_url']=$this->iconUrl($items->get((int)$row['item_id']));$row['rarity_visual']=null;$row['css_variables']=null;$row['rarity_visual_style_attribute']=null;if(!empty($row['is_unique'])&&$row['item_rarity_id']!==null){$rarity=$rarities->get((int)$row['item_rarity_id']);if($rarity){$visual=$this->rarityVisuals->resolve($rarity);$row['rarity_name']=$rarity->name;$row['rarity_visual']=$visual->toArray();$row['css_variables']=$visual->cssVariables();$row['rarity_visual_style_attribute']=$visual->inlineStyle();}}return$row;},$summary['items']);return$summary;}
public function decorateInventory(array $inventory){$ids=collect($inventory['stackable_items'])->pluck('item_id')->merge(collect($inventory['item_instances'])->pluck('item_id'))->unique()->values();$items=$this->itemsWithIcons($ids);foreach(['stackable_items','item_instances']as$key)$inventory[$key]=array_map(function($row)use($items){$row['image_url']=$this->iconUrl($items->get((int)$row['item_id']));return$row;},$inventory[$key]);return$inventory;}
private function stats($s){return['current_health'=>$s->currentHealth(),'max_health'=>$s->maxHealth(),'attack'=>$s->attack(),'defense'=>$s->defense(),'accuracy_rate'=>$s->accuracyRate(),'evasion_rate'=>$s->evasionRate(),'critical_chance'=>$s->criticalChance(),'critical_damage_multiplier'=>$s->criticalDamageMultiplier(),'attack_speed'=>$s->attackSpeed(),'damage_reduction_rate'=>$s->damageReductionRate(),'power'=>$s->power(),'loot_bonus'=>$s->lootBonus(),'experience_bonus'=>$s->experienceBonus(),'gold_bonus'=>$s->goldBonus()];}
private function background(Zone $zone){$zone->loadMissing('mediaAssets');$asset=$zone->mediaAssets->first(function($a){return$a->asset_type===MediaAssetType::BACKGROUND&&(bool)$a->is_primary;});return['url'=>$asset?$asset->url():null,'transparent'=>$asset===null];}
private function itemsWithIcons($ids){return$ids->isEmpty()?collect():Item::whereIn('id',$ids)->with(['mediaAssets'=>function($q){$q->where('asset_type',MediaAssetType::ICON)->where('is_primary',true);}])->get()->keyBy('id');}
private function iconUrl($item){if(!$item)return null;$asset=$item->relationLoaded('mediaAssets')?$item->mediaAssets->first():null;return$asset?$asset->url():null;}
}
