<?php
namespace App\Domain\Hunts\Sessions;
use App\Domain\Characters\Appearance\CharacterAppearanceService;use App\Domain\Characters\CharacterStatsCalculator;use App\Domain\Equipment\CharacterEquipmentSlot;use App\Domain\Hunts\Rewards\HuntRewardService;use App\Domain\Inventory\CharacterInventorySummaryService;use App\Domain\Media\MediaAssetType;use App\Models\Character;use App\Models\Item;use App\Models\Zone;
final class HuntingSessionPresentationService{
private $appearance;private $stats;private $inventory;private $rewards;
public function __construct(CharacterAppearanceService $appearance,CharacterStatsCalculator $stats,CharacterInventorySummaryService $inventory,HuntRewardService $rewards){$this->appearance=$appearance;$this->stats=$stats;$this->inventory=$inventory;$this->rewards=$rewards;}
public function prepare(Character $character,Zone $zone){return['appearance'=>$this->appearance->presentation($character),'background'=>$this->background($zone),'pending_rewards'=>$this->decoratePendingSummary($this->rewards->summaryPendingForCharacter($character)),'equipment'=>$this->equipment($character),'inventory'=>$this->decorateInventory($this->inventory->snapshot($character)),'stats'=>$this->stats($character)];}
public function decoratePendingSummary(array $summary){$ids=collect($summary['items'])->pluck('item_id')->unique()->values();$items=$this->itemsWithIcons($ids);$summary['items']=array_map(function($row)use($items){$row['image_url']=$this->iconUrl($items->get((int)$row['item_id']));return$row;},$summary['items']);return$summary;}
public function decorateInventory(array $inventory){$ids=collect($inventory['stackable_items'])->pluck('item_id')->merge(collect($inventory['item_instances'])->pluck('item_id'))->unique()->values();$items=$this->itemsWithIcons($ids);foreach(['stackable_items','item_instances']as$key)$inventory[$key]=array_map(function($row)use($items){$row['image_url']=$this->iconUrl($items->get((int)$row['item_id']));return$row;},$inventory[$key]);return$inventory;}
private function equipment(Character $character){$character->loadMissing(['equipment.itemInstance.item.mediaAssets']);$bySlot=$character->equipment->keyBy('slot');$rows=[];foreach(CharacterEquipmentSlot::all()as$slot){$equipped=$bySlot->get($slot);$instance=$equipped?$equipped->itemInstance:null;$item=$instance?$instance->item:null;$rows[]=['slot'=>$slot,'label'=>CharacterEquipmentSlot::label($slot),'occupied'=>(bool)$item,'item_name'=>$item?$item->name:null,'refinement_level'=>$instance?(int)$instance->refinement_level:null,'image_url'=>$this->iconUrl($item)];}return$rows;}
private function stats(Character $character){$s=$this->stats->calculate($character);return['current_health'=>$s->currentHealth(),'max_health'=>$s->maxHealth(),'attack'=>$s->attack(),'defense'=>$s->defense(),'accuracy_rate'=>$s->accuracyRate(),'evasion_rate'=>$s->evasionRate(),'critical_chance'=>$s->criticalChance(),'critical_damage_multiplier'=>$s->criticalDamageMultiplier(),'attack_speed'=>$s->attackSpeed(),'damage_reduction_rate'=>$s->damageReductionRate(),'power'=>$s->power(),'loot_bonus'=>$s->lootBonus(),'experience_bonus'=>$s->experienceBonus(),'gold_bonus'=>$s->goldBonus()];}
private function background(Zone $zone){$zone->loadMissing('mediaAssets');$asset=$zone->mediaAssets->first(function($a){return$a->asset_type===MediaAssetType::BACKGROUND&&(bool)$a->is_primary;});return['url'=>$asset?$asset->url():null,'transparent'=>$asset===null];}
private function itemsWithIcons($ids){return$ids->isEmpty()?collect():Item::whereIn('id',$ids)->with(['mediaAssets'=>function($q){$q->where('asset_type',MediaAssetType::ICON)->where('is_primary',true);}])->get()->keyBy('id');}
private function iconUrl($item){if(!$item)return null;$asset=$item->relationLoaded('mediaAssets')?$item->mediaAssets->first():null;return$asset?$asset->url():null;}
}
