<?php
namespace App\Domain\WorldMaps;
use App\Domain\WorldMaps\Exceptions\WorldMapAspectRatioConfirmationException;use App\Domain\WorldMaps\Exceptions\WorldMapConcurrencyException;use App\Models\Region;use App\Models\World;use App\Models\WorldMap;use App\Models\WorldMapArea;use App\Models\Zone;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Log;use InvalidArgumentException;
final class WorldMapAdminService{
private $maps;private $polygons;private $actions;private $images;
public function __construct(WorldMapValidator $maps,WorldMapPolygonValidator $polygons,WorldMapAreaActionValidator $actions,WorldMapImageService $images){$this->maps=$maps;$this->polygons=$polygons;$this->actions=$actions;$this->images=$images;}
public function saveMap(array $data,WorldMap $map=null,UploadedFile $image=null){$new=$image?$this->images->store($image):null;$old=null;try{$saved=DB::transaction(function()use($data,$map,$new,&$old){$model=$map&&$map->exists?WorldMap::whereKey($map->id)->lockForUpdate()->firstOrFail():new WorldMap();if($model->exists)$this->assertVersion($model,$data);$confirm=!empty($data['confirm_aspect_ratio_change']);unset($data['version'],$data['image'],$data['confirm_aspect_ratio_change']);if($new){if($model->exists&&$this->images->aspectChanged($model->original_width,$model->original_height,$new['original_width'],$new['original_height'])&&!$confirm)throw new WorldMapAspectRatioConfirmationException();$old=['disk'=>$model->image_disk,'path'=>$model->image_path];$data=array_merge($data,$new);}$data['is_default']=!empty($data['is_default']);$candidate=$model->replicate();$candidate->fill($data);$candidate->version=$model->exists?$model->version+1:1;$this->maps->validate($candidate);if($candidate->is_default)$this->clearSiblingDefaults($candidate,$model->exists?$model->id:null);$model->fill($data);$model->version=$candidate->version;$model->save();return$model->fresh();},3);}catch(\Throwable $e){if($new)$this->images->delete($new['image_disk'],$new['image_path']);throw$e;}if($old&&$old['path']&&$old['path']!==$saved->image_path){try{if(!$this->images->delete($old['disk'],$old['path']))Log::warning('Old WorldMap image could not be deleted.',$old);}catch(\Throwable $e){Log::warning('Old WorldMap image cleanup failed.',['path'=>$old['path'],'message'=>$e->getMessage()]);}}return$saved;}
public function deactivateMap(WorldMap $map,$version){return DB::transaction(function()use($map,$version){$locked=WorldMap::whereKey($map->id)->lockForUpdate()->firstOrFail();$this->assertVersion($locked,['version'=>$version]);$locked->status=WorldMapStatus::INACTIVE;$locked->is_default=false;$locked->version++;$locked->save();return$locked;},3);}
public function saveArea(WorldMap $map,array $data,WorldMapArea $area=null){return DB::transaction(function()use($map,$data,$area){$parent=WorldMap::whereKey($map->id)->lockForUpdate()->firstOrFail();$model=$area&&$area->exists?WorldMapArea::where('world_map_id',$parent->id)->whereKey($area->id)->lockForUpdate()->firstOrFail():new WorldMapArea(['world_map_id'=>$parent->id]);if($model->exists)$this->assertVersion($model,$data);unset($data['version'],$data['id'],$data['world_map_id'],$data['created_at'],$data['updated_at']);if(isset($data['polygon_points'])&&$data['polygon_points']!==null&&$data['polygon_points']!=='')$data['polygon_points']=$this->polygons->normalize($data['polygon_points']);else$data['polygon_points']=null;$candidate=$model->replicate();$candidate->fill($data);$candidate->world_map_id=$parent->id;$candidate->version=$model->exists?$model->version+1:1;$candidate->setRelation('zone',$candidate->zone_id?Zone::find($candidate->zone_id):null);$candidate->setRelation('targetWorldMap',$candidate->target_world_map_id?WorldMap::find($candidate->target_world_map_id):null);$candidate->setRelation('targetWorld',$candidate->target_world_id?World::find($candidate->target_world_id):null);$candidate->setRelation('targetRegion',$candidate->target_region_id?Region::find($candidate->target_region_id):null);$strict=$candidate->status!==WorldMapAreaStatus::DRAFT;$this->actions->validate($candidate,$parent,$strict);if($strict&&!$candidate->polygon_points)throw new InvalidArgumentException('Active or inactive area requires valid geometry.');if($candidate->status===WorldMapAreaStatus::ACTIVE)$this->maps->validate($parent);$model->fill($data);$model->world_map_id=$parent->id;$model->version=$candidate->version;$model->save();$parent->touch();return$model->fresh();},3);}
public function deactivateArea(WorldMap $map,WorldMapArea $area,$version){return$this->changeAreaStatus($map,$area,$version,WorldMapAreaStatus::INACTIVE);}public function activateArea(WorldMap $map,WorldMapArea $area,$version){return$this->changeAreaStatus($map,$area,$version,WorldMapAreaStatus::ACTIVE);}private function changeAreaStatus($map,$area,$version,$status){$data=$area->toArray();$data['status']=$status;$data['version']=$version;return$this->saveArea($map,$data,$area);}
private function clearSiblingDefaults(WorldMap $candidate,$except){$q=WorldMap::query()->where('is_default',true);$candidate->world_id?$q->where('world_id',$candidate->world_id)->whereNull('region_id'):$q->where('region_id',$candidate->region_id)->whereNull('world_id');if($except)$q->where('id','<>',$except);$q->orderBy('id')->lockForUpdate()->update(['is_default'=>false]);}private function assertVersion($model,array $data){if(!isset($data['version'])||(int)$data['version']!==(int)$model->version)throw new WorldMapConcurrencyException();}}
