<?php
namespace App\Domain\Admin\Content;
use App\Domain\Equipment\EquipmentItemFamily;
use App\Domain\Equipment\HandRequirement;
use App\Domain\Media\ZoneBackgrounds\ZoneCombatBackgroundService;
use App\Domain\Equipment\EquipmentType;use App\Domain\Equipment\EquippableItemValidator;use App\Domain\Inventory\Instances\ItemRefinementConfiguration;use App\Domain\Inventory\ItemClassification;use App\Domain\Media\CatalogImages\CatalogImageService;use App\Domain\Media\CatalogImages\CatalogImageType;use App\Domain\Media\MediaAssetType;use App\Domain\Probability\PercentagePpmConverter;use App\Domain\WorldCatalog\CatalogStatus;use App\Domain\WorldCatalog\ItemType;use App\Domain\WorldCatalog\ZoneType;use App\Models\CharacterClass;use App\Models\Item;use App\Models\ItemRarity;use App\Models\Monster;use App\Models\MonsterLootEntry;use App\Models\Region;use App\Models\Zone;use InvalidArgumentException;
final class ContentAdminReadService{
private $classification;private $equippable;private $images;private $zoneBackgrounds;private $probabilities;public function __construct(ItemClassification $classification,EquippableItemValidator $equippable,CatalogImageService $images,ZoneCombatBackgroundService $zoneBackgrounds,PercentagePpmConverter $probabilities){$this->classification=$classification;$this->equippable=$equippable;$this->images=$images;$this->zoneBackgrounds=$zoneBackgrounds;$this->probabilities=$probabilities;}
public function itemOptions(Item $item=null){$selected=$item&&$item->exists?$item->allowedCharacterClasses()->orderBy('sort_order')->orderBy('name')->get():collect();$active=CharacterClass::where('status',CatalogStatus::ACTIVE)->orderBy('sort_order')->orderBy('name')->get();$classes=$active->merge($selected)->unique('id')->map(function($class)use($selected){return['id'=>(int)$class->id,'code'=>$class->code,'name'=>$class->name,'status'=>$class->status,'selected'=>$selected->contains('id',$class->id)];})->values()->all();$selectedRarities=$item&&$item->exists?$item->allowedRarities()->pluck('item_rarities.id')->map(function($id){return(int)$id;})->all():[];$rarities=ItemRarity::where('status',CatalogStatus::ACTIVE)->when(!empty($selectedRarities),function($query)use($selectedRarities){$query->orWhereIn('id',$selectedRarities);})->orderBy('sort_order')->orderBy('id')->get()->map(function($rarity)use($selectedRarities){return['id'=>(int)$rarity->id,'code'=>$rarity->code,'name'=>$rarity->name,'status'=>$rarity->status,'visual_style'=>$rarity->visual_style,'selected'=>in_array((int)$rarity->id,$selectedRarities,true)];})->all();return['item_types'=>ItemType::values(),'equipment_types'=>EquipmentType::all(),'hand_requirements'=>HandRequirement::labels(),'equipment_families'=>EquipmentItemFamily::labels(),'rarities'=>$rarities,'refinement_stats'=>ItemRefinementConfiguration::values(),'statuses'=>CatalogStatus::values(),'character_classes'=>$classes,'selected_character_class_ids'=>$selected->pluck('id')->map(function($id){return(int)$id;})->all(),'selected_rarity_ids'=>$selectedRarities];}
public function zoneOptions(Zone $zone=null){$sizes=[1=>100,2=>0,3=>0];if($zone&&$zone->exists){$rows=$zone->encounterSizeConfigs()->whereIn('enemy_count',[1,2,3])->get()->keyBy('enemy_count');foreach([1,2,3]as$count)if($rows->has($count))$sizes[$count]=(int)$rows->get($count)->weight;}return['regions'=>Region::with('world')->orderBy('world_id')->orderBy('name')->get(),'zone_types'=>ZoneType::values(),'statuses'=>CatalogStatus::values(),'encounter_sizes'=>$sizes];}public function zoneBackground(Zone $zone){return$this->zoneBackgrounds->presentation($zone);}public function statuses(){return CatalogStatus::values();}
public function items(){$p=Item::with(['allowedCharacterClasses','mediaAssets'=>function($q){$q->where('asset_type',MediaAssetType::ICON)->where('is_primary',true)->orderBy('id');}])->orderBy('name')->paginate(25);$p->setCollection($p->getCollection()->map(function($item){return$this->itemData($item);}));return$p;}
public function item(Item $item){$item->loadMissing(['allowedCharacterClasses','mediaAssets'=>function($q){$q->where('asset_type',MediaAssetType::ICON)->where('is_primary',true)->orderBy('id');}]);return$this->itemData($item);}
private function itemData(Item $item){try{$classification=$this->classification->classify($item);$this->equippable->equipmentType($item);$coherent=true;}catch(InvalidArgumentException $e){$classification='incoherent';$coherent=false;}return['model'=>$item,'image'=>$this->images->presentationFor($item,CatalogImageType::ITEM),'classification'=>$classification,'coherent'=>$coherent,'required_level'=>(int)$item->required_level,'allowed_classes'=>$item->allowedCharacterClasses->map(function($class){return['id'=>(int)$class->id,'code'=>$class->code,'name'=>$class->name,'status'=>$class->status];})->all(),'bonuses'=>['max_health_bonus'=>$item->max_health_bonus,'attack_bonus'=>$item->attack_bonus,'defense_bonus'=>$item->defense_bonus,'accuracy_bonus'=>$item->accuracy_bonus,'evasion_bonus'=>$item->evasion_bonus,'critical_chance_bonus'=>$item->critical_chance_bonus,'attack_speed_bonus'=>$item->attack_speed_bonus]];}
public function monsters(){$p=Monster::with(['zones.region.world','lootEntries.item','mediaAssets'=>function($q){$q->where('asset_type',MediaAssetType::PORTRAIT)->where('is_primary',true)->orderBy('id');}])->orderBy('name')->paginate(25);$p->setCollection($p->getCollection()->map(function($monster){return['model'=>$monster,'image'=>$this->images->presentationFor($monster,CatalogImageType::MONSTER)];}));return$p;}
public function monster(Monster $monster){return$monster->load(['zones.region.world','lootEntries.item','mediaAssets'=>function($q){$q->where('asset_type',MediaAssetType::PORTRAIT)->where('is_primary',true)->orderBy('id');}]);}public function monsterImage(Monster $monster){return$this->images->presentationFor($monster,CatalogImageType::MONSTER);}
public function lootRows(Monster $monster){return$monster->lootEntries->sortBy(function($entry){return sprintf('%010d:%010d',(int)$entry->sort_order,(int)$entry->id);})->map(function($entry){$unique=false;try{$unique=$this->classification->classify($entry->item)===ItemClassification::UNIQUE;}catch(InvalidArgumentException $e){}return['model'=>$entry,'item'=>$entry->item,'probability_ppm'=>(int)$entry->drop_probability_ppm,'probability_percent'=>$this->probabilities->toPercentageString((int)$entry->drop_probability_ppm),'status_label'=>ucfirst($entry->status),'status_badge'=>$entry->status===CatalogStatus::ACTIVE?'success':'secondary','quantity_warning'=>$unique&&((int)$entry->minimum_quantity!==1||(int)$entry->maximum_quantity!==1)];})->values();}
public function zones(){return Zone::with('region.world')->orderBy('region_id')->orderBy('name')->paginate(25);}public function zone(Zone $zone){return$zone->load(['region.world','monsters']);}public function loot(){$p=MonsterLootEntry::with(['monster','item'])->orderBy('monster_id')->orderBy('sort_order')->paginate(25);$p->getCollection()->each(function($entry){$entry->setAttribute('drop_probability_percent',$this->probabilities->toPercentageString((int)$entry->drop_probability_ppm));});return$p;}}
