<?php
namespace App\Domain\Admin\Content;
use App\Domain\Inventory\Instances\ItemRarityCode;use App\Domain\Inventory\Instances\Rarity\ItemRarityVisualConfiguration;use App\Domain\Inventory\Instances\Rarity\ItemRarityVisualStyleResolver;use App\Domain\Probability\PercentageBasisPointsConverter;use App\Domain\WorldCatalog\CatalogStatus;use App\Models\ItemRarity;use Illuminate\Support\Facades\DB;use InvalidArgumentException;
final class ItemRarityContentService
{
    private $validator;private $resolver;private $percentages;public function __construct(ItemRarityVisualConfiguration $validator,ItemRarityVisualStyleResolver $resolver,PercentageBasisPointsConverter $percentages){$this->validator=$validator;$this->resolver=$resolver;$this->percentages=$percentages;}
    public function rows(){return ItemRarity::withCount(['items','itemInstances'])->orderBy('sort_order')->orderBy('id')->get()->each(function($rarity){$visual=$this->resolver->resolve($rarity);$rarity->setAttribute('border_opacity_percent',$this->percentages->toPercentageString($visual->borderOpacityBasisPoints()));$rarity->setAttribute('inner_glow_opacity_percent',$this->percentages->toPercentageString($visual->innerGlowOpacityBasisPoints()));$rarity->setAttribute('rarity_visual_style_attribute',$visual->inlineStyle());});}
    public function update(ItemRarity $rarity,array $data){ItemRarityCode::assert($rarity->code);return DB::transaction(function()use($rarity,$data){$locked=ItemRarity::whereKey($rarity->id)->lockForUpdate()->firstOrFail();if($locked->code===ItemRarityCode::COMMON&&$data['status']!==CatalogStatus::ACTIVE&&($locked->items()->exists()||$locked->itemInstances()->exists()))throw new InvalidArgumentException('Common no puede desactivarse mientras exista contenido histórico que la utilice.');$allowed=['name','status','sort_order','visual_style','weapon_accuracy_bonus_basis_points','weapon_critical_bonus_basis_points','armor_evasion_bonus_basis_points','armor_speed_bonus_hundredths','armor_absorb_damage_bonus_basis_points','border_color_hex','border_opacity_basis_points','border_width_px','inner_glow_color_hex','inner_glow_opacity_basis_points','inner_glow_blur_px','inner_glow_spread_px'];$safe=array_intersect_key($data,array_flip($allowed));$visual=$this->validator->normalize($safe);$safe=array_merge($safe,$visual);$locked->fill($safe);$locked->save();return$locked;});}
}
