@extends('layouts.game')
@section('title','Editor · '.$map->name)
@section('content')
@include('admin.content.partials.navigation')
@include('admin.content.partials.messages')
<div class="d-flex justify-content-between flex-wrap gap-2"><div><h1>{{ $map->name }}</h1><p>{{ $map->world ? $map->world->name : $map->region->world->name.' › '.$map->region->name }} · {{ $map->status }} · versión {{ $map->version }}</p></div><a class="btn btn-outline-secondary align-self-start" href="{{ route('admin.content.world-maps.edit',$map) }}">Editar mapa/imagen</a></div>

@if(!$image['public_url_available'])
<div class="alert alert-warning" role="alert"><strong>La imagen del mapa no está disponible.</strong><div class="small mt-2">Disk: <code>{{ $image['disk'] ?: 'vacío' }}</code><br>Path relativo: <code>{{ $image['path'] ?: 'vacío' }}</code><br>Existe en disk: {{ $image['exists'] ? 'true' : 'false' }}</div><a class="btn btn-sm btn-warning mt-3" href="{{ route('admin.content.world-maps.edit',$map) }}">Reemplazar imagen</a></div>
@endif

<div class="row g-3" id="world-map-editor" data-world-map-editor data-image-width="{{ $image['original_width'] }}" data-image-height="{{ $image['original_height'] }}" data-image-available="{{ $image['public_url_available'] ? '1' : '0' }}">
    <div class="col-xl-8">
        <div class="alert alert-info py-2" data-world-map-status role="status" aria-live="polite">{{ $image['public_url_available'] ? 'Cargando imagen del mapa...' : 'No se pudo cargar la imagen del mapa.' }}</div>
        <div class="world-map-canvas world-map-editor-canvas" data-map-canvas>
            @if($image['public_url_available'])<img class="world-map-image" data-world-map-image src="{{ $image['url'] }}" alt="{{ $map->name }}">@endif
            <svg class="world-map-overlay" data-world-map-svg viewBox="0 0 {{ $image['original_width'] }} {{ $image['original_height'] }}" preserveAspectRatio="xMidYMid meet" role="img" aria-label="Editor de polígonos">
                <g data-area-layer>@foreach($areaRows as $row)@if($row['svg_points'])<polygon tabindex="0" data-area-id="{{ $row['model']->id }}" points="{{ $row['svg_points'] }}" style="fill:{{ $row['model']->fill_color?:'#0d6efd' }};fill-opacity:{{ $row['model']->fill_opacity===null?'0.25':$row['model']->fill_opacity }};stroke:{{ $row['model']->stroke_color?:'#ffffff' }};stroke-width:{{ $row['model']->stroke_width?:2 }}"></polygon>@endif @endforeach</g>
                <g data-draft-layer></g>
            </svg>
        </div>
        <div class="d-flex flex-wrap gap-2 mt-2">
            <button type="button" class="btn btn-sm btn-primary" data-world-map-create disabled>Crear polígono</button>
            <button type="button" class="btn btn-sm btn-outline-secondary" data-world-map-undo disabled>Deshacer punto</button>
            <button type="button" class="btn btn-sm btn-outline-danger" data-world-map-clear disabled>Limpiar borrador</button>
            <button type="button" class="btn btn-sm btn-success" data-world-map-close disabled>Cerrar polígono</button>
            <span class="small text-secondary align-self-center" data-coordinate-readout>Sin geometría preparada.</span>
        </div>
    </div>
    <div class="col-xl-4"><form method="POST" data-area-form action="{{ route('admin.content.world-maps.areas.store',$map) }}">@csrf <input type="hidden" name="_method" value="POST" data-method><input type="hidden" name="version" value="" data-area-version><input type="hidden" name="polygon_points" data-polygon-input>
        <h2 class="h4">Área</h2><div class="mb-2"><label class="form-label">Código</label><input class="form-control" name="code" required></div><div class="mb-2"><label class="form-label">Nombre</label><input class="form-control" name="name" required></div><div class="mb-2"><label class="form-label">Descripción de texto plano</label><textarea class="form-control" name="description"></textarea></div><div class="row g-2"><div class="col-6"><label>Acción</label><select class="form-select" name="action_type">@foreach($options['actions'] as $action)<option>{{ $action }}</option>@endforeach</select></div><div class="col-6"><label>Estado</label><select class="form-select" name="status">@foreach($options['statuses'] as $status)<option>{{ $status }}</option>@endforeach</select></div></div>
        <div class="mt-2"><label>Zone</label><select class="form-select" name="zone_id"><option value="">—</option>@foreach($options['zones'] as $zone)<option value="{{ $zone->id }}">{{ $zone->region->world->name }} › {{ $zone->region->name }} › {{ $zone->name }}</option>@endforeach</select></div><div class="mt-2"><label>Mapa destino</label><select class="form-select" name="target_world_map_id"><option value="">—</option>@foreach($options['maps'] as $target)<option value="{{ $target->id }}">{{ $target->name }}</option>@endforeach</select></div><div class="row g-2 mt-1"><div class="col-6"><label>World destino</label><select class="form-select" name="target_world_id"><option value="">—</option>@foreach($options['worlds'] as $world)<option value="{{ $world->id }}">{{ $world->name }}</option>@endforeach</select></div><div class="col-6"><label>Region destino</label><select class="form-select" name="target_region_id"><option value="">—</option>@foreach($options['regions'] as $region)<option value="{{ $region->id }}">{{ $region->world->name }} › {{ $region->name }}</option>@endforeach</select></div></div><div class="mt-2"><label>Ruta interna permitida</label><select class="form-select" name="internal_route_name"><option value="">—</option>@foreach($options['internal_routes'] as $key=>$route)<option value="{{ $key }}">{{ $key }}</option>@endforeach</select><input type="hidden" name="internal_route_parameters"></div>
        <div class="row g-2 mt-1"><div class="col-4"><label>z-index</label><input class="form-control" name="z_index" value="0"></div><div class="col-4"><label>Orden</label><input class="form-control" name="sort_order" value="0"></div><div class="col-4"><label>Modo</label><select class="form-select" name="display_mode"><option>panel</option><option>navigate</option></select></div></div><div class="row g-2 mt-1"><div class="col-6"><label>Disponible desde</label><input type="datetime-local" class="form-control" name="available_from"></div><div class="col-6"><label>Disponible hasta</label><input type="datetime-local" class="form-control" name="available_until"></div></div>
        <input type="hidden" name="fill_color" value="#0d6efd"><input type="hidden" name="fill_opacity" value="0.25"><input type="hidden" name="stroke_color" value="#ffffff"><input type="hidden" name="stroke_width" value="2"><input type="hidden" name="hover_fill_color" value="#ffc107"><input type="hidden" name="hover_fill_opacity" value="0.45"><button class="btn btn-primary mt-3" data-world-map-save disabled>Guardar área</button><button type="button" class="btn btn-outline-secondary mt-3" data-new-area>Nueva</button></form></div>
</div>
<hr><h2 class="h4">Áreas configuradas</h2><table class="table"><thead><tr><th>Área</th><th>Acción</th><th>Estado</th><th>Orden visual</th><th></th></tr></thead><tbody>@foreach($areaRows as $row)@php($area=$row['model'])<tr><td>{{ $area->name }}<br><small>{{ $area->code }}</small></td><td>{{ $area->action_type }}</td><td>{{ $area->status }}</td><td>{{ $area->z_index }} / {{ $area->sort_order }}</td><td><button type="button" class="btn btn-sm btn-outline-primary" data-edit-area data-area='@json($row['payload'])' data-update-url="{{ route('admin.content.world-maps.areas.update',[$map,$area]) }}">Editar</button><form class="d-inline" method="POST" action="{{ $area->status==='active'?route('admin.content.world-maps.areas.deactivate',[$map,$area]):route('admin.content.world-maps.areas.activate',[$map,$area]) }}">@csrf @method('PATCH')<input type="hidden" name="version" value="{{ $area->version }}"><button class="btn btn-sm btn-outline-secondary">{{ $area->status==='active'?'Desactivar':'Activar' }}</button></form></td></tr>@endforeach</tbody></table>
@endsection
