<?php
namespace App\Domain\Wallet;
use App\Domain\Wallet\Data\GoldTransactionEntry;
use App\Domain\Wallet\Data\WalletBalance;
use App\Domain\Wallet\Exceptions\IdempotencyConflictException;
use App\Domain\Wallet\Exceptions\InsufficientGoldException;
use App\Models\Character; use App\Models\CharacterWallet; use App\Models\GoldTransaction;
use Illuminate\Support\Collection; use Illuminate\Support\Facades\DB; use InvalidArgumentException;
final class WalletService {
 public function balance(Character $c):WalletBalance{$w=CharacterWallet::where('character_id',$c->id)->first();return new WalletBalance($c->id,$w?(int)$w->gold_balance:0);}
 public function credit(Character $c,int $a,string $r,?string $d=null,?string $rt=null,?int $ri=null,?string $k=null):GoldTransactionEntry{return $this->move($c,GoldTransactionType::CREDIT,$a,$r,$d,$rt,$ri,$k);}
 public function creditLocked(Character $c,int $a,string $r,?string $d=null,?string $rt=null,?int $ri=null,?string $k=null):GoldTransactionEntry{if(DB::transactionLevel()<1)throw new \RuntimeException('Active transaction required.');return $this->moveLocked($c,GoldTransactionType::CREDIT,$a,$r,$d,$rt,$ri,$k);}
 public function debit(Character $c,int $a,string $r,?string $d=null,?string $rt=null,?int $ri=null,?string $k=null):GoldTransactionEntry{return $this->move($c,GoldTransactionType::DEBIT,$a,$r,$d,$rt,$ri,$k);}
 public function transactions(Character $c,int $limit=50):Collection{if($limit<1)throw new InvalidArgumentException('Limit must be positive.');return GoldTransaction::where('character_id',$c->id)->orderByDesc('created_at')->orderByDesc('id')->limit($limit)->get()->map(function($t){return $this->entry($t);});}
 private function move(Character $c,$type,$amount,$reason,$description,$referenceType,$referenceId,$key){$this->validate($amount,$reason,$key);return DB::transaction(function()use($c,$type,$amount,$reason,$description,$referenceType,$referenceId,$key){$locked=Character::whereKey($c->id)->lockForUpdate()->firstOrFail();return$this->moveLocked($locked,$type,$amount,$reason,$description,$referenceType,$referenceId,$key);},3);}
 private function moveLocked(Character $c,$type,$amount,$reason,$description,$referenceType,$referenceId,$key){$this->validate($amount,$reason,$key);if($key!==null){$old=GoldTransaction::where('idempotency_key',$key)->first();if($old)return$this->replay($old,$c,$type,$amount,$reason,$description,$referenceType,$referenceId);}$wallet=CharacterWallet::where('character_id',$c->id)->lockForUpdate()->first();if(!$wallet){$wallet=new CharacterWallet();$wallet->character_id=$c->id;$wallet->gold_balance=0;$wallet->save();}$before=(int)$wallet->gold_balance;if($type===GoldTransactionType::CREDIT){if($amount>PHP_INT_MAX-$before)throw new InvalidArgumentException('Gold balance would exceed PHP_INT_MAX.');$after=$before+$amount;}else{if($amount>$before)throw new InsufficientGoldException('Insufficient gold.');$after=$before-$amount;}$wallet->gold_balance=$after;$wallet->save();$t=GoldTransaction::create(['character_id'=>$c->id,'transaction_type'=>$type,'amount'=>$amount,'balance_before'=>$before,'balance_after'=>$after,'reason_code'=>$reason,'description'=>$description,'reference_type'=>$referenceType,'reference_id'=>$referenceId,'idempotency_key'=>$key]);return$this->entry($t);}
 private function validate($amount,$reason,$key){if(!is_int($amount)||$amount<=0)throw new InvalidArgumentException('Amount must be positive.');if(!in_array($reason,GoldReasonCode::all(),true))throw new InvalidArgumentException('Invalid reason code.');if($key!==null&&($key===''||strlen($key)>191))throw new InvalidArgumentException('Invalid idempotency key.');}
 private function replay($t,$c,$type,$amount,$reason,$description,$referenceType,$referenceId){$same=(int)$t->character_id===(int)$c->id&&$t->transaction_type===$type&&(int)$t->amount===$amount&&$t->reason_code===$reason&&$t->description===$description&&$t->reference_type===$referenceType&&($t->reference_id===null?$referenceId===null:(int)$t->reference_id===$referenceId);if(!$same)throw new IdempotencyConflictException('Idempotency key belongs to another operation.');return $this->entry($t);}
 private function entry($t){return new GoldTransactionEntry($t->id,$t->character_id,$t->transaction_type,$t->amount,$t->balance_before,$t->balance_after,$t->reason_code,$t->description,$t->reference_type,$t->reference_id,$t->created_at);}
}
