<?php
namespace App\Domain\Inventory\Capacity;
use App\Models\Character;
use App\Models\InventoryCapacityGrant;
use Carbon\CarbonImmutable;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use InvalidArgumentException;
final class InventoryCapacityGrantService{public function grant(Character $character,$slots,$sourceType,$sourceIdentifier,CarbonImmutable $startsAt=null,CarbonImmutable $endsAt=null){if(!is_int($slots)||$slots<=0||$slots>InventoryCapacityLimits::MAX_OPERATIONAL_SLOTS)throw new InvalidArgumentException('Invalid capacity grant slots.');if(trim((string)$sourceType)===''||trim((string)$sourceIdentifier)==='')throw new InvalidArgumentException('Capacity grant source is required.');if($startsAt&&$endsAt&&$endsAt->lte($startsAt))throw new InvalidArgumentException('Capacity grant end must be after start.');try{return DB::transaction(function()use($character,$slots,$sourceType,$sourceIdentifier,$startsAt,$endsAt){$locked=Character::whereKey($character->id)->lockForUpdate()->firstOrFail();$base=(int)$locked->base_inventory_slots;if($base<=0||$base>InventoryCapacityLimits::MAX_OPERATIONAL_SLOTS)throw new InvalidArgumentException('Invalid base inventory capacity.');if(InventoryCapacityGrant::where('character_id',$locked->id)->where('source_type',$sourceType)->where('source_identifier',$sourceIdentifier)->lockForUpdate()->exists())throw new InvalidArgumentException('Duplicate logical capacity grant.');$active=(int)InventoryCapacityGrant::where('character_id',$locked->id)->where('is_active',true)->lockForUpdate()->sum('slots');if($slots>InventoryCapacityLimits::MAX_OPERATIONAL_SLOTS-$base-$active)throw new InvalidArgumentException('Capacity grants exceed operational limit.');return InventoryCapacityGrant::create(['character_id'=>$locked->id,'slots'=>$slots,'source_type'=>$sourceType,'source_identifier'=>$sourceIdentifier,'is_active'=>true,'starts_at'=>$startsAt,'ends_at'=>$endsAt,'granted_at'=>CarbonImmutable::now()]);},3);}catch(QueryException $e){if((string)$e->getCode()==='23000'&&strpos($e->getMessage(),'capacity_grants_logical_unique')!==false)throw new InvalidArgumentException('Duplicate logical capacity grant.');throw$e;}}}
