<?php
namespace App\Domain\Shops;
use App\Domain\Equipment\EquipmentType;use App\Domain\Equipment\EquippableItemValidator;use App\Domain\Inventory\ItemClassification;use App\Domain\WorldCatalog\CatalogStatus;use App\Domain\WorldCatalog\ItemType;use App\Models\Item;use App\Models\Npc;use App\Models\Shop;use App\Models\ShopLocation;use App\Models\ShopOffer;use InvalidArgumentException;
final class ShopCatalogValidator{
 private $classification;private $equippable;public function __construct(ItemClassification $classification,EquippableItemValidator $equippable){$this->classification=$classification;$this->equippable=$equippable;}
 public function validateNpc(Npc $npc){if(trim((string)$npc->code)===''||trim((string)$npc->name)===''||!in_array($npc->status,CatalogStatus::values(),true))throw new InvalidArgumentException('Invalid NPC catalog configuration.');return$npc;}
 public function validateShop(Shop $shop){if(trim((string)$shop->code)===''||trim((string)$shop->name)===''||!$shop->npc_id||!in_array($shop->status,CatalogStatus::values(),true))throw new InvalidArgumentException('Invalid Shop catalog configuration.');$this->window($shop->starts_at,$shop->ends_at);return$shop;}
 public function validateLocation(ShopLocation $location){if(!$location->shop_id||!in_array($location->locatable_type,ShopLocationType::enabled(),true)||!$location->locatable_id||!in_array($location->status,CatalogStatus::values(),true)||(int)$location->sort_order<0)throw new InvalidArgumentException('Invalid Shop location configuration.');return$location;}
 public function validateOffer(ShopOffer $offer){if(!$offer->shop_id||!$offer->item_id||!in_array($offer->category,ShopOfferCategory::values(),true)||!in_array($offer->visibility,ShopOfferVisibility::values(),true)||!in_array($offer->status,CatalogStatus::values(),true))throw new InvalidArgumentException('Invalid Shop offer configuration.');foreach(['quantity','gold_price']as$field)if(!$this->positive($offer->{$field}))throw new InvalidArgumentException('Shop offer quantity and price must be positive safe integers.');$limit=$this->nullableInteger($offer->stock_limit);$remaining=$this->nullableInteger($offer->stock_remaining);if(($limit===null)!==($remaining===null)||($limit!==null&&($limit<1||$remaining<0||$remaining>$limit)))throw new InvalidArgumentException('Invalid Shop offer stock configuration.');foreach(['purchase_limit_per_character','required_character_level']as$field){$value=$this->nullableInteger($offer->{$field});if($value!==null&&$value<1)throw new InvalidArgumentException('Invalid Shop offer requirement.');}$this->window($offer->starts_at,$offer->ends_at);return$offer;}
 public function validateSellableItem(Item $item,$category){if(!$item->exists||$item->status!==CatalogStatus::ACTIVE||!in_array($item->item_type,[ItemType::MATERIAL,ItemType::CONSUMABLE,ItemType::EQUIPMENT,ItemType::DRAGON_MATERIAL],true))throw new InvalidArgumentException('El Item no es vendible en Shops.');$this->classification->classify($item);$this->equippable->equipmentType($item);$valid=$category===ShopOfferCategory::EVENT||($category===ShopOfferCategory::WEAPONS&&$item->item_type===ItemType::EQUIPMENT&&$item->equipment_type===EquipmentType::WEAPON)||($category===ShopOfferCategory::ARMOR&&$item->item_type===ItemType::EQUIPMENT&&$item->equipment_type!==EquipmentType::WEAPON)||($category===ShopOfferCategory::CONSUMABLES&&$item->item_type===ItemType::CONSUMABLE)||($category===ShopOfferCategory::MATERIALS&&in_array($item->item_type,[ItemType::MATERIAL,ItemType::DRAGON_MATERIAL],true));if(!$valid)throw new InvalidArgumentException('La categoría comercial no es coherente con el Item.');return$item;}
 private function window($starts,$ends){if($starts!==null&&$ends!==null&&$ends->lte($starts))throw new InvalidArgumentException('Availability end must be after start.');}
 private function positive($value){return is_int($value)&&$value>0;}
 private function nullableInteger($value){if($value===null)return null;if(!is_int($value)||$value<0)throw new InvalidArgumentException('Invalid safe integer.');return$value;}
}
