<?php
namespace App\Http\Requests\Admin\Content;
use App\Domain\Inventory\Instances\ItemRarityCode;use App\Domain\Probability\PercentageBasisPointsConverter;use App\Domain\WorldCatalog\CatalogStatus;use Illuminate\Foundation\Http\FormRequest;use Illuminate\Validation\Rule;use InvalidArgumentException;
final class UpdateItemRarityRequest extends FormRequest
{
    public function authorize(){return true;}
    protected function prepareForValidation(){$data=['border_color_hex'=>strtoupper(trim((string)$this->input('border_color_hex'))),'inner_glow_color_hex'=>strtoupper(trim((string)$this->input('inner_glow_color_hex')))];$converter=app(PercentageBasisPointsConverter::class);foreach(['border_opacity_percent'=>'border_opacity_basis_points','inner_glow_opacity_percent'=>'inner_glow_opacity_basis_points']as$input=>$output){try{$data[$output]=$converter->toBasisPoints($this->input($input));}catch(InvalidArgumentException $e){$data[$output]=-1;}}$this->merge($data);}
    public function rules(){return['name'=>'required|string|max:64','status'=>['required',Rule::in(CatalogStatus::values())],'sort_order'=>'required|integer|min:1|max:65535','visual_style'=>['required',Rule::in(ItemRarityCode::styles())],'weapon_accuracy_bonus_basis_points'=>'required|integer|min:0|max:10000','weapon_critical_bonus_basis_points'=>'required|integer|min:0|max:10000','armor_evasion_bonus_basis_points'=>'required|integer|min:0|max:10000','armor_speed_bonus_hundredths'=>'required|integer|min:0|max:100000','armor_absorb_damage_bonus_basis_points'=>'required|integer|min:0|max:10000','border_color_hex'=>['required','regex:/^#[0-9A-F]{6}$/D'],'border_opacity_percent'=>['required','regex:/^(?:0|[1-9][0-9]?|100)(?:\.[0-9]{1,2})?$/D'],'border_opacity_basis_points'=>'required|integer|min:0|max:10000','border_width_px'=>'required|integer|min:1|max:5','inner_glow_color_hex'=>['required','regex:/^#[0-9A-F]{6}$/D'],'inner_glow_opacity_percent'=>['required','regex:/^(?:0|[1-9][0-9]?|100)(?:\.[0-9]{1,2})?$/D'],'inner_glow_opacity_basis_points'=>'required|integer|min:0|max:10000','inner_glow_blur_px'=>'required|integer|min:0|max:40','inner_glow_spread_px'=>'required|integer|min:0|max:20'];}
}
