<?php
namespace App\Domain\Media\CharacterVisuals;
use App\Domain\Media\CharacterVisuals\Data\CharacterVisualPresentation;use App\Domain\Media\MediaAssetService;use App\Domain\Media\MediaAssetType;use App\Models\CharacterTemplate;use App\Models\MediaAsset;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Log;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;use Throwable;
final class CharacterVisualAssetService{const VERSION=1;const DISK='public';const QUALITY=82;const MAX_BYTES=5242880;const MAX_DIMENSION=4096;const MAX_PIXELS=16777216;const SIZES=[128=>192,256=>384,512=>768];private $media;public function __construct(MediaAssetService $media){$this->media=$media;}
public function replace(CharacterTemplate $template,UploadedFile $file){$source=$this->decode($file);$root='game-assets/character-templates/'.date('Y/m').'/'.Str::uuid();$original=$root.'/original.'.$source['extension'];$paths=[];try{Storage::disk(self::DISK)->put($original,file_get_contents($file->getRealPath()));foreach(self::SIZES as$width=>$height){$path=$root.'/'.$width.'.webp';$this->writeVariant($source['image'],$source['width'],$source['height'],$width,$height,$path);$paths[(string)$width]=$path;}foreach($paths as$path)if(!Storage::disk(self::DISK)->exists($path))throw new CharacterVisualAssetException('No se pudo verificar una variante visual.');$metadata=['character_visual_version'=>self::VERSION,'root'=>$root,'body_type'=>$template->body_type,'canvas'=>['width'=>512,'height'=>768,'ratio'=>'2:3'],'variants'=>$paths,'original'=>['path'=>$original,'mime'=>$source['mime'],'width'=>$source['width'],'height'=>$source['height'],'size'=>(int)$file->getSize()]];$result=$this->media->replacePrimary($template,['asset_type'=>MediaAssetType::BASE_VISUAL,'disk'=>self::DISK,'path'=>$paths['256'],'mime_type'=>'image/webp','width'=>256,'height'=>384,'file_size'=>Storage::disk(self::DISK)->size($paths['256']),'metadata'=>$metadata,'sort_order'=>0]);if($result['previous'])$this->deleteFiles($result['previous']);return$result['asset'];}catch(Throwable $e){Storage::disk(self::DISK)->deleteDirectory($root);throw$e;}finally{if(isset($source['image']))imagedestroy($source['image']);}}
public function delete(CharacterTemplate $template){if($template->status==='active')throw new CharacterVisualAssetException('Inactiva la plantilla antes de eliminar su imagen base.');$asset=$this->media->deletePrimary($template,MediaAssetType::BASE_VISUAL);if($asset)$this->deleteFiles($asset);}
public function syncBodyType(CharacterTemplate $template){$asset=$template->primaryMediaAsset(MediaAssetType::BASE_VISUAL)->first();if(!$asset)return;$metadata=is_array($asset->metadata)?$asset->metadata:[];$metadata['body_type']=$template->body_type;$asset->metadata=$metadata;$asset->save();}
public function isActivationReady(CharacterTemplate $template){$asset=$this->asset($template);if(!$asset||$asset->mime_type!=='image/webp')return false;$m=is_array($asset->metadata)?$asset->metadata:[];$canvas=isset($m['canvas'])&&is_array($m['canvas'])?$m['canvas']:[];if((isset($m['character_visual_version'])?(int)$m['character_visual_version']:0)!==self::VERSION||(isset($canvas['width'])?(int)$canvas['width']:0)!==512||(isset($canvas['height'])?(int)$canvas['height']:0)!==768||(isset($canvas['ratio'])?$canvas['ratio']:null)!=='2:3'||!isset($m['variants'])||!is_array($m['variants']))return false;foreach(array_keys(self::SIZES)as$size){$path=isset($m['variants'][(string)$size])?$m['variants'][(string)$size]:null;if(!$this->relative($path)||!Storage::disk($asset->disk)->exists($path))return false;}return true;}
public function presentation(CharacterTemplate $template=null){$fallback=[];foreach(array_keys(self::SIZES)as$s)$fallback[$s]=asset('assets/images/character-templates/default-'.$s.'.svg');if(!$template)return new CharacterVisualPresentation($fallback,false);$asset=$this->asset($template);if(!$asset)return new CharacterVisualPresentation($fallback,false);$m=is_array($asset->metadata)?$asset->metadata:[];$urls=[];foreach(array_keys(self::SIZES)as$s){$path=isset($m['variants'][(string)$s])?$m['variants'][(string)$s]:null;$urls[$s]=$this->relative($path)&&Storage::disk($asset->disk)->exists($path)?Storage::disk($asset->disk)->url($path):$fallback[$s];}return new CharacterVisualPresentation($urls,$urls[256]!==$fallback[256]);}
private function asset(CharacterTemplate $template){if($template->relationLoaded('mediaAssets'))return$template->mediaAssets->first(function($a){return$a->asset_type===MediaAssetType::BASE_VISUAL&&$a->is_primary;});return$template->primaryMediaAsset(MediaAssetType::BASE_VISUAL)->first();}
private function decode(UploadedFile $file){if(!$file->isValid()||(int)$file->getSize()>self::MAX_BYTES)throw new CharacterVisualAssetException('La imagen no es válida o supera 5 MB.');$info=@getimagesize($file->getRealPath());if(!$info)throw new CharacterVisualAssetException('El archivo no es una imagen decodificable.');$w=(int)$info[0];$h=(int)$info[1];if($w<=0||$h<=0||$w>self::MAX_DIMENSION||$h>self::MAX_DIMENSION||$w*$h>self::MAX_PIXELS)throw new CharacterVisualAssetException('Las dimensiones de la imagen no son válidas.');if(abs($w*3-$h*2)>2)throw new CharacterVisualAssetException('La imagen debe mantener proporción vertical 2:3.');$mime=$info['mime'];$map=['image/png'=>['imagecreatefrompng','png'],'image/webp'=>['imagecreatefromwebp','webp'],'image/jpeg'=>['imagecreatefromjpeg','jpg']];if(!isset($map[$mime]))throw new CharacterVisualAssetException('Solo se permiten imágenes PNG, WebP o JPEG.');$image=@call_user_func($map[$mime][0],$file->getRealPath());if(!$image)throw new CharacterVisualAssetException('No se pudo decodificar la imagen.');imagealphablending($image,false);imagesavealpha($image,true);return['image'=>$image,'width'=>$w,'height'=>$h,'mime'=>$mime,'extension'=>$map[$mime][1]];}
private function writeVariant($source,$sw,$sh,$dw,$dh,$path){$canvas=imagecreatetruecolor($dw,$dh);imagealphablending($canvas,false);imagesavealpha($canvas,true);$transparent=imagecolorallocatealpha($canvas,0,0,0,127);imagefill($canvas,0,0,$transparent);if(!imagecopyresampled($canvas,$source,0,0,0,0,$dw,$dh,$sw,$sh))throw new CharacterVisualAssetException('No se pudo escalar la imagen.');ob_start();$ok=imagewebp($canvas,null,self::QUALITY);$bytes=ob_get_clean();imagedestroy($canvas);if(!$ok||$bytes==='')throw new CharacterVisualAssetException('No se pudo generar WebP.');Storage::disk(self::DISK)->put($path,$bytes);}
private function deleteFiles(MediaAsset $asset){$m=is_array($asset->metadata)?$asset->metadata:[];$root=isset($m['root'])?$m['root']:null;if(!$this->relative($root))return;try{if(!Storage::disk($asset->disk)->deleteDirectory($root))Log::warning('No se pudo eliminar un directorio visual anterior.',['asset_id'=>$asset->id]);}catch(Throwable $e){Log::warning('Falló la limpieza de un directorio visual anterior.',['asset_id'=>$asset->id]);}}
private function relative($path){return is_string($path)&&$path!==''&&$path===trim($path)&&strpos($path,"\0")===false&&strpos($path,'\\')===false&&$path[0]!=='/'&&strpos($path,'..')===false;}}
