<?php
namespace App\Domain\Inventory\Instances;
use App\Domain\Equipment\CharacterEquipmentSlot;use App\Models\Character;use App\Models\Item;use App\Models\ItemInstance;use App\Models\ItemInstanceEvent;use Carbon\CarbonImmutable;use Illuminate\Support\Facades\DB;use RuntimeException;
final class ItemInstanceEventService
{
    public function appendEquipped(ItemInstance $instance,Character $actor,Item $item,$slot,$operationUuid,CarbonImmutable $now){return$this->append($instance,$actor,$item,$slot,$operationUuid,$now,ItemInstanceEventType::EQUIPPED);}
    public function appendUnequipped(ItemInstance $instance,Character $actor,Item $item,$slot,$operationUuid,CarbonImmutable $now){return$this->append($instance,$actor,$item,$slot,$operationUuid,$now,ItemInstanceEventType::UNEQUIPPED);}
    public function appendRefinementSucceeded(ItemInstance $instance,Character $actor,Item $item,$operationUuid,array $metadata,CarbonImmutable $now){return$this->appendRefinementResult($instance,$actor,$item,$operationUuid,$metadata,$now,ItemInstanceEventType::REFINEMENT_SUCCEEDED);}
    public function appendRefinementFailed(ItemInstance $instance,Character $actor,Item $item,$operationUuid,array $metadata,CarbonImmutable $now){return$this->appendRefinementResult($instance,$actor,$item,$operationUuid,$metadata,$now,ItemInstanceEventType::REFINEMENT_FAILED);}
    private function appendRefinementResult(ItemInstance $instance,Character $actor,Item $item,$operationUuid,array $metadata,CarbonImmutable $now,$type){if(DB::transactionLevel()<1)throw new RuntimeException('Active transaction required.');return ItemInstanceEvent::create(['item_instance_id'=>$instance->id,'operation_uuid'=>$operationUuid,'event_type'=>$type,'actor_character_id'=>$actor->id,'from_character_id'=>$actor->id,'to_character_id'=>$actor->id,'from_item_id'=>$item->id,'to_item_id'=>$item->id,'refinement_before'=>$metadata['from_level'],'refinement_after'=>$metadata['current_level'],'source_type'=>'refinement_level','source_id'=>$metadata['refinement_rule_id'],'metadata'=>$metadata,'occurred_at'=>$now,'created_at'=>$now]);}
    private function append(ItemInstance $instance,Character $actor,Item $item,$slot,$operationUuid,CarbonImmutable $now,$type){if(DB::transactionLevel()<1)throw new RuntimeException('Active transaction required.');CharacterEquipmentSlot::assertValid($slot);if((int)$instance->character_id!==(int)$actor->id||(int)$instance->item_id!==(int)$item->id)throw new RuntimeException('Invalid equipment event context.');return ItemInstanceEvent::create(['item_instance_id'=>$instance->id,'operation_uuid'=>$operationUuid,'event_type'=>$type,'actor_character_id'=>$actor->id,'from_character_id'=>$actor->id,'to_character_id'=>$actor->id,'from_item_id'=>$item->id,'to_item_id'=>$item->id,'refinement_before'=>$instance->refinement_level,'refinement_after'=>$instance->refinement_level,'source_type'=>null,'source_id'=>null,'metadata'=>['slot'=>$slot],'occurred_at'=>$now,'created_at'=>$now]);}
}
