<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ShowLoginController;
use App\Http\Controllers\Auth\ShowRegistrationController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GameHomeController;
use App\Http\Controllers\CharacterController;
use App\Http\Controllers\CharacterSelectionController;
use App\Http\Controllers\WorldCatalogController;
use App\Http\Controllers\RegionCatalogController;
use App\Http\Controllers\ZoneCatalogController;
use App\Http\Controllers\WorldMapController;
use App\Http\Controllers\CharacterInventoryController;
use App\Http\Controllers\CharacterWalletController;
use App\Http\Controllers\CharacterHuntController;
use App\Http\Controllers\CharacterHuntingSessionController;
use App\Http\Controllers\CharacterHuntRewardClaimController;
use App\Http\Controllers\CharacterEquipmentController;
use App\Http\Controllers\CharacterItemRefinementController;
use App\Http\Controllers\CharacterOverviewController;
use App\Http\Controllers\ManualCombatController;
use App\Http\Controllers\ShopPurchaseController;
use App\Http\Controllers\ShopSaleController;
use App\Http\Controllers\ShopController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\Content\ItemController as AdminItemController;
use App\Http\Controllers\Admin\Content\MonsterController as AdminMonsterController;
use App\Http\Controllers\Admin\Content\ZoneController as AdminZoneController;
use App\Http\Controllers\Admin\Content\ZoneMonsterController as AdminZoneMonsterController;
use App\Http\Controllers\Admin\Content\LootController as AdminLootController;
use App\Http\Controllers\Admin\Content\RefinementController as AdminRefinementController;
use App\Http\Controllers\Admin\Content\RefinementStatModifierController as AdminRefinementStatModifierController;
use App\Http\Controllers\Admin\Content\WorldMapController as AdminWorldMapController;
use App\Http\Controllers\Admin\Content\WorldMapAreaController as AdminWorldMapAreaController;
use App\Http\Controllers\Admin\Content\CharacterTemplateController as AdminCharacterTemplateController;
use App\Http\Controllers\Admin\Content\CharacterClassController as AdminCharacterClassController;
use App\Http\Controllers\Admin\Content\GameHomeCardController as AdminGameHomeCardController;
use App\Http\Controllers\Admin\Content\ItemVisualAssetController as AdminItemVisualAssetController;
use App\Http\Controllers\Admin\Content\RegionController as AdminRegionController;
use App\Http\Controllers\Admin\Content\WorldController as AdminWorldController;
use App\Http\Controllers\Admin\Content\CharacterProgressionController as AdminCharacterProgressionController;
use App\Http\Controllers\Admin\Content\NpcController as AdminNpcController;
use App\Http\Controllers\Admin\Content\ShopController as AdminShopController;
use App\Http\Controllers\Admin\Content\ShopOfferController as AdminShopOfferController;
use App\Http\Controllers\Admin\Content\ItemRarityController as AdminItemRarityController;
use App\Http\Controllers\Admin\Content\ItemRarityDropRateController as AdminItemRarityDropRateController;

Route::middleware('guest')->group(function () {
    Route::get('/login', ShowLoginController::class)->name('login');
    Route::post('/login', LoginController::class);
    Route::get('/registro', ShowRegistrationController::class)->name('register');
    Route::post('/registro', RegisterController::class);
});

Route::middleware(['auth', 'game.navigation'])->group(function () {
    Route::get('/characters/create', [CharacterController::class, 'create'])->name('characters.create');
    Route::post('/characters', [CharacterController::class, 'store'])->name('characters.store');
    Route::get('/characters/select', [CharacterSelectionController::class, 'index'])->name('characters.select');
    Route::post('/characters/{character}/select', [CharacterSelectionController::class, 'store'])->name('characters.select.store');
    Route::middleware(['character.active.route','character.required'])->group(function () {
    Route::get('/characters/{character}/overview', CharacterOverviewController::class)->name('characters.overview');
    Route::get('/characters/{character}', [CharacterController::class, 'show'])->name('characters.show');
    Route::get('/characters/{character}/inventory', [CharacterInventoryController::class, 'index'])->name('characters.inventory.index');
    Route::get('/characters/{character}/wallet', [CharacterWalletController::class, 'show'])->name('characters.wallet.show');
    Route::get('/characters/{character}/hunts', [CharacterHuntController::class, 'index'])->name('characters.hunts.index');
    Route::get('/characters/{character}/hunts/{hunt}', [CharacterHuntController::class, 'show'])->name('characters.hunts.show');
    Route::post('/characters/{character}/zones/{zone}/hunts', [CharacterHuntController::class, 'store'])->name('characters.hunts.store');
    Route::post('/characters/{character}/zones/{zone}/hunting-sessions', [CharacterHuntingSessionController::class, 'store'])->name('characters.hunting-sessions.store');
    Route::get('/characters/{character}/hunting-sessions/{huntingSession}', [CharacterHuntingSessionController::class, 'show'])->name('characters.hunting-sessions.show');
    Route::post('/characters/{character}/hunting-sessions/{huntingSession}/tick', [CharacterHuntingSessionController::class, 'tick'])->name('characters.hunting-sessions.tick');
    Route::post('/characters/{character}/hunting-sessions/{huntingSession}/stop', [CharacterHuntingSessionController::class, 'stop'])->name('characters.hunting-sessions.stop');
    Route::post('/characters/{character}/hunting-sessions/{huntingSession}/manual-combat', [ManualCombatController::class, 'store'])->name('characters.manual-combats.store');
    Route::post('/characters/{character}/zones/{zone}/manual-combat', [ManualCombatController::class, 'storeForZone'])->name('characters.manual-combats.zones.store');
    Route::get('/characters/{character}/manual-combats/{combatSession}', [ManualCombatController::class, 'show'])->name('characters.manual-combats.show');
    Route::get('/characters/{character}/manual-combats/{combatSession}/play', [ManualCombatController::class, 'play'])->name('characters.manual-combats.play');
      Route::post('/characters/{character}/manual-combats/{combatSession}/actions', [ManualCombatController::class, 'action'])->name('characters.manual-combats.actions.store');
      Route::post('/characters/{character}/manual-combats/{combatSession}/claim-rewards', [ManualCombatController::class, 'claimRewards'])->name('characters.manual-combats.rewards.claim');
      Route::post('/characters/{character}/manual-combats/{combatSession}/abandon', [ManualCombatController::class, 'abandon'])->name('characters.manual-combats.abandon');
    Route::post('/characters/{character}/hunt-rewards/claim', CharacterHuntRewardClaimController::class)->name('characters.hunt-rewards.claim');
    Route::post('/characters/{character}/equipment/equip', [CharacterEquipmentController::class, 'equip'])->name('characters.equipment.equip');
    Route::post('/characters/{character}/equipment/unequip', [CharacterEquipmentController::class, 'unequip'])->name('characters.equipment.unequip');
    Route::post('/characters/{character}/item-instances/{itemInstance}/refine', CharacterItemRefinementController::class)->name('characters.item-instances.refine');
    Route::post('/characters/{character}/shops/{shop}/offers/{offer}/purchases', [ShopPurchaseController::class, 'store'])->name('characters.shops.offers.purchases.store');
    Route::post('/characters/{character}/shops/{shop}/sales', [ShopSaleController::class, 'store'])->name('characters.shops.sales.store');
    Route::get('/characters/{character}/shops/{shop}', [ShopController::class, 'show'])->name('characters.shops.show');
    });

    Route::get('/', GameHomeController::class)
        ->middleware('character.required')
        ->name('dashboard');
    Route::get('/inventory.html', [DashboardController::class, 'inventory']);
    Route::get('/reports.html', [DashboardController::class, 'reports']);
    Route::get('/create-product.html', [DashboardController::class, 'createProduct']);
    Route::get('/docs.html', [DashboardController::class, 'docs']);
    Route::post('/logout', LogoutController::class)->name('logout');
});

Route::middleware(['auth', 'game.navigation', 'character.required'])->group(function () {
    Route::get('/maps',[WorldMapController::class,'index'])->name('world-maps.index');
    Route::get('/maps/worlds/{world}',[WorldMapController::class,'world'])->name('world-maps.world');
    Route::get('/maps/regions/{region}',[WorldMapController::class,'region'])->name('world-maps.region');
    Route::get('/maps/{worldMap}',[WorldMapController::class,'show'])->name('world-maps.show');
    Route::get('/worlds', [WorldCatalogController::class, 'index'])->name('worlds.index');
    Route::get('/worlds/{world}/regions/{region}', [WorldCatalogController::class, 'region'])->name('worlds.regions.show');
    Route::get('/worlds/{world}', [WorldCatalogController::class, 'show'])->name('worlds.show');
    Route::get('/regions/{region}', [RegionCatalogController::class, 'show'])->name('regions.show');
    Route::get('/zones/{zone}', [ZoneCatalogController::class, 'show'])->name('zones.show');
});

Route::prefix('admin/content')->name('admin.content.')->middleware(['auth','game.navigation','content.admin'])->group(function(){
    Route::get('item-rarity-drop-rates',[AdminItemRarityDropRateController::class,'index'])->name('item-rarity-drop-rates.index');
    Route::put('item-rarity-drop-rates',[AdminItemRarityDropRateController::class,'update'])->name('item-rarity-drop-rates.update');
    Route::get('item-rarities',[AdminItemRarityController::class,'index'])->name('item-rarities.index');
    Route::put('item-rarities/{itemRarity}',[AdminItemRarityController::class,'update'])->name('item-rarities.update');
    Route::patch('character-classes/{character_class}/activate',[AdminCharacterClassController::class,'activate'])->name('character-classes.activate');
    Route::patch('character-classes/{character_class}/deactivate',[AdminCharacterClassController::class,'deactivate'])->name('character-classes.deactivate');
    Route::patch('character-classes/{character_class}/hide',[AdminCharacterClassController::class,'hide'])->name('character-classes.hide');
    Route::delete('character-classes/{character_class}/icon',[AdminCharacterClassController::class,'destroyIcon'])->name('character-classes.icon.destroy');
    Route::resource('character-classes',AdminCharacterClassController::class)->only(['index','create','store','edit','update'])->parameters(['character-classes'=>'character_class']);
    Route::patch('npcs/{npc}/activate',[AdminNpcController::class,'activate'])->name('npcs.activate');
    Route::patch('npcs/{npc}/deactivate',[AdminNpcController::class,'deactivate'])->name('npcs.deactivate');
    Route::resource('npcs',AdminNpcController::class)->only(['index','create','store','edit','update']);
    Route::get('shops/items/search',[AdminShopOfferController::class,'search'])->name('shops.items.search');
    Route::patch('shops/{shop}/activate',[AdminShopController::class,'activate'])->name('shops.activate');
    Route::patch('shops/{shop}/deactivate',[AdminShopController::class,'deactivate'])->name('shops.deactivate');
    Route::patch('shops/{shop}/hide',[AdminShopController::class,'hide'])->name('shops.hide');
    Route::resource('shops',AdminShopController::class)->only(['index','create','store','edit','update']);
    Route::post('shops/{shop}/offers',[AdminShopOfferController::class,'store'])->name('shops.offers.store');
    Route::put('shops/{shop}/offers/{offer}',[AdminShopOfferController::class,'update'])->name('shops.offers.update');
    Route::patch('shops/{shop}/offers/{offer}/activate',[AdminShopOfferController::class,'activate'])->name('shops.offers.activate');
    Route::patch('shops/{shop}/offers/{offer}/deactivate',[AdminShopOfferController::class,'deactivate'])->name('shops.offers.deactivate');
    Route::get('progression',[AdminCharacterProgressionController::class,'index'])->name('progression.index');
    Route::put('progression',[AdminCharacterProgressionController::class,'update'])->name('progression.update');
    Route::get('combat-balance',[\App\Http\Controllers\Admin\Content\CombatBalanceController::class,'index'])->name('combat-balance.index');
    Route::put('combat-balance',[\App\Http\Controllers\Admin\Content\CombatBalanceController::class,'update'])->name('combat-balance.update');
    Route::get('worlds/{world}/regions', [AdminRegionController::class, 'index'])->name('worlds.regions.index');
    Route::get('worlds/{world}/regions/create', [AdminRegionController::class, 'create'])->name('worlds.regions.create');
    Route::post('worlds/{world}/regions', [AdminRegionController::class, 'store'])->name('worlds.regions.store');
    Route::patch('worlds/{world}/activate', [AdminWorldController::class, 'activate'])->name('worlds.activate');
    Route::patch('worlds/{world}/deactivate', [AdminWorldController::class, 'deactivate'])->name('worlds.deactivate');
    Route::delete('worlds/{world}/image', [AdminWorldController::class, 'destroyImage'])->name('worlds.image.destroy');
    Route::resource('worlds', AdminWorldController::class)->only(['index', 'create', 'store', 'edit', 'update']);
    Route::patch('regions/{region}/activate', [AdminRegionController::class, 'activate'])->name('regions.activate');
    Route::patch('regions/{region}/deactivate', [AdminRegionController::class, 'deactivate'])->name('regions.deactivate');
    Route::resource('regions', AdminRegionController::class)->only(['index', 'create', 'store', 'edit', 'update']);
    Route::patch('game-home-cards/{gameHomeCard}/activate',[AdminGameHomeCardController::class,'activate'])->name('game-home-cards.activate');
    Route::patch('game-home-cards/{gameHomeCard}/deactivate',[AdminGameHomeCardController::class,'deactivate'])->name('game-home-cards.deactivate');
    Route::delete('game-home-cards/{gameHomeCard}/banner',[AdminGameHomeCardController::class,'destroyBanner'])->name('game-home-cards.banner.destroy');
    Route::resource('game-home-cards',AdminGameHomeCardController::class)->except('show')->parameters(['game-home-cards'=>'gameHomeCard']);
    Route::patch('character-templates/{character_template}/activate',[AdminCharacterTemplateController::class,'activate'])->name('character-templates.activate');
    Route::patch('character-templates/{character_template}/deactivate',[AdminCharacterTemplateController::class,'deactivate'])->name('character-templates.deactivate');
    Route::patch('character-templates/{character_template}/hide',[AdminCharacterTemplateController::class,'hide'])->name('character-templates.hide');
    Route::delete('character-templates/{character_template}/image',[AdminCharacterTemplateController::class,'destroyImage'])->name('character-templates.image.destroy');
    Route::resource('character-templates',AdminCharacterTemplateController::class)->parameters(['character-templates'=>'character_template']);
    Route::get('world-maps/{worldMap}/editor',[AdminWorldMapController::class,'editor'])->name('world-maps.editor');
    Route::resource('world-maps',AdminWorldMapController::class)->parameters(['world-maps'=>'worldMap']);
    Route::post('world-maps/{worldMap}/areas',[AdminWorldMapAreaController::class,'store'])->name('world-maps.areas.store');
    Route::put('world-maps/{worldMap}/areas/{worldMapArea}',[AdminWorldMapAreaController::class,'update'])->name('world-maps.areas.update');
    Route::patch('world-maps/{worldMap}/areas/{worldMapArea}/activate',[AdminWorldMapAreaController::class,'activate'])->name('world-maps.areas.activate');
    Route::patch('world-maps/{worldMap}/areas/{worldMapArea}/deactivate',[AdminWorldMapAreaController::class,'deactivate'])->name('world-maps.areas.deactivate');
    Route::delete('items/{item}/image',[AdminItemController::class,'destroyImage'])->name('items.image.destroy');
    Route::post('items/{item}/visual-assets',[AdminItemVisualAssetController::class,'store'])->name('items.visual-assets.store');
    Route::delete('items/{item}/visual-assets/{itemVisualAsset}',[AdminItemVisualAssetController::class,'destroy'])->name('items.visual-assets.destroy');
    Route::delete('monsters/{monster}/image',[AdminMonsterController::class,'destroyImage'])->name('monsters.image.destroy');
    Route::resource('items',AdminItemController::class)->except('show');
    Route::resource('monsters',AdminMonsterController::class);
    Route::resource('zones',AdminZoneController::class);
    Route::get('loot',[AdminLootController::class,'index'])->name('loot.index');
    Route::post('zones/{zone}/monsters',[AdminZoneMonsterController::class,'store'])->name('zones.monsters.store');
    Route::put('zones/{zone}/monsters/{monster}',[AdminZoneMonsterController::class,'update'])->name('zones.monsters.update');
    Route::delete('zones/{zone}/monsters/{monster}',[AdminZoneMonsterController::class,'destroy'])->name('zones.monsters.destroy');
    Route::post('monsters/{monster}/loot',[AdminLootController::class,'store'])->name('monsters.loot.store');
    Route::put('monsters/{monster}/loot/{lootEntry}',[AdminLootController::class,'update'])->name('monsters.loot.update');
    Route::patch('monsters/{monster}/loot/{lootEntry}/activate',[AdminLootController::class,'activate'])->name('monsters.loot.activate');
    Route::patch('monsters/{monster}/loot/{lootEntry}/deactivate',[AdminLootController::class,'deactivate'])->name('monsters.loot.deactivate');
    Route::get('refinement',[AdminRefinementController::class,'index'])->name('refinement.index');
    Route::post('refinement',[AdminRefinementController::class,'store'])->name('refinement.store');
    Route::put('refinement/{refinementLevel}',[AdminRefinementController::class,'update'])->name('refinement.update');
    Route::patch('refinement/{refinementLevel}/activate',[AdminRefinementController::class,'activate'])->name('refinement.activate');
    Route::patch('refinement/{refinementLevel}/deactivate',[AdminRefinementController::class,'deactivate'])->name('refinement.deactivate');
    Route::delete('refinement/{refinementLevel}',[AdminRefinementController::class,'destroy'])->name('refinement.destroy');
    Route::post('refinement/{refinementLevel}/materials',[AdminRefinementController::class,'storeMaterial'])->name('refinement.materials.store');
    Route::put('refinement/{refinementLevel}/materials/{material}',[AdminRefinementController::class,'updateMaterial'])->name('refinement.materials.update');
    Route::delete('refinement/{refinementLevel}/materials/{material}',[AdminRefinementController::class,'destroyMaterial'])->name('refinement.materials.destroy');
    Route::post('refinement/stats',[AdminRefinementStatModifierController::class,'store'])->name('refinement.stats.store');
    Route::put('refinement/stats/{modifier}',[AdminRefinementStatModifierController::class,'update'])->name('refinement.stats.update');
    Route::patch('refinement/stats/{modifier}/activate',[AdminRefinementStatModifierController::class,'activate'])->name('refinement.stats.activate');
    Route::patch('refinement/stats/{modifier}/deactivate',[AdminRefinementStatModifierController::class,'deactivate'])->name('refinement.stats.deactivate');
});
