<?php
namespace Tests\Feature;
use App\Domain\Media\CatalogImages\CatalogImageException;use App\Domain\Media\CatalogImages\CatalogImageService;use App\Domain\Media\CatalogImages\CatalogImageType;use App\Domain\Media\MediaAssetType;use App\Domain\Media\MediaAssetService;use App\Models\Item;use App\Models\MediaAsset;use App\Models\Monster;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Storage;use Tests\TestCase;
class CatalogImageTest extends TestCase{use RefreshDatabase;private $temporary=[];protected function tearDown():void{foreach($this->temporary as $path)if(file_exists($path))unlink($path);parent::tearDown();}
public function test_png_jpeg_and_webp_generate_verified_square_variants_and_original(){foreach(['png','jpg','webp']as$format){Storage::fake('public');$file=$this->image($format,40,80,true);$upload=app(CatalogImageService::class)->process(CatalogImageType::ITEM,$file);$metadata=$upload->metadata();$this->assertSame(1,$metadata['catalog_image_version']);$this->assertSame('item',$metadata['catalog_type']);$this->assertStringNotContainsString('\\',$upload->root());$this->assertMatchesRegularExpression('#game-assets/items/\d{4}/\d{2}/[0-9a-f-]{36}#',$upload->root());Storage::disk('public')->assertExists($metadata['original']['path']);foreach([64,128,256]as$size){$path=$metadata['variants'][(string)$size];Storage::disk('public')->assertExists($path);$info=getimagesizefromstring(Storage::disk('public')->get($path));$this->assertSame([$size,$size,'image/webp'],[$info[0],$info[1],$info['mime']]);$this->assertGreaterThan(0,$metadata['variant_sizes'][(string)$size]);}$image=imagecreatefromstring(Storage::disk('public')->get($metadata['variants']['64']));$alpha=(imagecolorat($image,1,1)>>24)&0x7F;imagedestroy($image);$this->assertGreaterThan(100,$alpha);}}
public function test_vertical_and_horizontal_content_is_centered_without_stretch(){foreach([[40,80],[80,40]]as$dimensions){Storage::fake('public');$upload=app(CatalogImageService::class)->process(CatalogImageType::MONSTER,$this->image('png',$dimensions[0],$dimensions[1],false));$image=imagecreatefromstring(Storage::disk('public')->get($upload->metadata()['variants']['128']));$center=imagecolorsforindex($image,imagecolorat($image,64,64));$corner=imagecolorsforindex($image,imagecolorat($image,2,2));imagedestroy($image);$this->assertGreaterThan(100,$corner['alpha']);$this->assertLessThan(20,$center['alpha']);}}
public function test_invalid_formats_corruption_size_and_dimensions_are_rejected(){Storage::fake('public');foreach([$this->raw('<svg></svg>','bad.svg','image/svg+xml'),$this->image('gif',64,64,false),$this->raw('broken','bad.png','image/png'),$this->image('png',31,64,false),$this->image('png',4097,32,false)]as$file){try{app(CatalogImageService::class)->process(CatalogImageType::ITEM,$file);$this->fail('Se aceptó una imagen inválida.');}catch(CatalogImageException $e){$this->assertNotSame('',$e->getMessage());}}$largePath=$this->temp();file_put_contents($largePath,str_repeat('x',CatalogImageService::MAX_BYTES+1));$this->expectException(CatalogImageException::class);app(CatalogImageService::class)->process(CatalogImageType::ITEM,new UploadedFile($largePath,'large.png','image/png',null,true));}
public function test_replace_metadata_canonical_path_cleanup_delete_and_other_media_are_safe(){Storage::fake('public');$item=$this->item();$other=app(MediaAssetService::class)->attach($item,['asset_type'=>MediaAssetType::CARD,'disk'=>'public','path'=>'other/card.webp']);$first=app(CatalogImageService::class)->replace($item,CatalogImageType::ITEM,$this->image('png',50,80,true));$oldRoot=$first->metadata['catalog_image_root'];$second=app(CatalogImageService::class)->replace($item,CatalogImageType::ITEM,$this->image('jpg',80,50,false));$this->assertNotSame($oldRoot,$second->metadata['catalog_image_root']);$this->assertStringEndsWith('/128.webp',$second->path);Storage::disk('public')->assertMissing($oldRoot);$this->assertDatabaseHas('media_assets',['id'=>$other->id]);app(CatalogImageService::class)->delete($item,CatalogImageType::ITEM);$this->assertDatabaseHas('items',['id'=>$item->id]);$this->assertDatabaseHas('media_assets',['id'=>$other->id]);$this->assertDatabaseMissing('media_assets',['id'=>$second->id]);Storage::disk('public')->assertMissing($second->metadata['catalog_image_root']);}
public function test_persistence_failure_removes_new_directory_and_preserves_existing_references(){Storage::fake('public');try{app(CatalogImageService::class)->replace(new Item(),CatalogImageType::ITEM,$this->image('png',64,64,true));$this->fail();}catch(\InvalidArgumentException $e){$this->assertSame([],Storage::disk('public')->allFiles());$this->assertSame([],array_values(array_filter(Storage::disk('public')->allDirectories(),function($path){return substr_count($path,'/')>=4;})));}}
public function test_legacy_missing_and_incomplete_assets_resolve_without_writes(){Storage::fake('public');Storage::disk('public')->put('legacy/icon.webp','legacy');$legacy=new MediaAsset(['disk'=>'public','path'=>'legacy/icon.webp','metadata'=>null]);$view=app(CatalogImageService::class)->presentation(CatalogImageType::ITEM,$legacy);$this->assertTrue($view->exists());$this->assertSame(Storage::disk('public')->url('legacy/icon.webp'),$view->url64());$missing=app(CatalogImageService::class)->presentation(CatalogImageType::MONSTER);$this->assertTrue($missing->isFallback());$this->assertStringContainsString('default-monster-128.webp',$missing->url128());$this->expectException(\InvalidArgumentException::class);$missing->url(32);}
private function item(){return Item::create(['code'=>'catalog_image_item','name'=>'Image Item','item_type'=>'material','equipment_type'=>null,'rarity'=>'common','is_stackable'=>true,'max_stack'=>99,'status'=>'active']);}
private function image($format,$width,$height,$transparent){$path=$this->temp();$image=imagecreatetruecolor($width,$height);imagealphablending($image,false);imagesavealpha($image,true);$background=imagecolorallocatealpha($image,0,0,0,$transparent?127:0);imagefill($image,0,0,$background);$red=imagecolorallocatealpha($image,220,30,40,0);imagefilledrectangle($image,(int)($width*.2),(int)($height*.2),(int)($width*.8),(int)($height*.8),$red);if($format==='png')imagepng($image,$path);elseif($format==='jpg')imagejpeg($image,$path,90);elseif($format==='webp')imagewebp($image,$path,90);else imagegif($image,$path);imagedestroy($image);$mime=$format==='jpg'?'image/jpeg':($format==='gif'?'image/gif':'image/'.$format);return new UploadedFile($path,'fixture.'.$format,$mime,null,true);}
private function raw($content,$name,$mime){$path=$this->temp();file_put_contents($path,$content);return new UploadedFile($path,$name,$mime,null,true);}private function temp(){$path=tempnam(sys_get_temp_dir(),'catalog_test_');$this->temporary[]=$path;return$path;}}
