<?php
namespace Tests\Feature;
use App\Domain\Characters\Progression\CharacterProgressionService;use App\Models\Character;use App\Models\CharacterLevelRequirement;use App\Models\CharacterProgressionSetting;use App\Models\User;use Database\Seeders\CharacterLevelRequirementSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\DB;use InvalidArgumentException;use Tests\TestCase;
final class CharacterProgressionCapTest extends TestCase
{
 use RefreshDatabase;
 protected function setUp():void{parent::setUp();$this->seed(CharacterLevelRequirementSeeder::class);}
 private function grant(Character $character,$amount){return DB::transaction(function()use($character,$amount){$locked=Character::whereKey($character->id)->lockForUpdate()->firstOrFail();return app(CharacterProgressionService::class)->grantExperienceLocked($locked,$amount);});}
 public function test_cap_accumulates_experience_and_later_increase_enables_progression(){$character=Character::factory()->for(User::factory())->create(['level'=>5,'experience'=>850]);$result=$this->grant($character,1000)->toArray();$this->assertSame(5,$result['level_after']);$this->assertSame(1850,$result['experience_after']);CharacterLevelRequirement::create(['level'=>6,'required_experience'=>1200]);CharacterProgressionSetting::whereKey(1)->update(['max_character_level'=>6,'version'=>2]);$result=$this->grant($character->fresh(),0)->toArray();$this->assertSame(6,$result['level_after']);$this->assertSame(1850,$result['experience_after']);}
 public function test_overflow_and_missing_capped_level_fail_without_changes(){$character=Character::factory()->for(User::factory())->create(['experience'=>PHP_INT_MAX]);try{$this->grant($character,1);$this->fail();}catch(InvalidArgumentException $e){}$this->assertSame(PHP_INT_MAX,$character->fresh()->experience);CharacterProgressionSetting::whereKey(1)->update(['max_character_level'=>6]);try{$this->grant(Character::factory()->for(User::factory())->create(),1);$this->fail();}catch(\RuntimeException $e){$this->assertStringContainsString('does not reach',$e->getMessage());}}
 public function test_character_selector_labels_the_authoritative_maximum_level(){$character=Character::factory()->selected()->create(['level'=>5,'experience'=>920]);$this->actingAs($character->user)->get(route('characters.select'))->assertOk()->assertSee('NIVEL MÁXIMO')->assertSee('aria-valuenow="100"',false)->assertDontSee('0 / 0 EXP');}
 public function test_prepared_levels_are_ignored_until_the_cap_is_raised(){$character=Character::factory()->for(User::factory())->create(['level'=>5,'experience'=>850]);CharacterLevelRequirement::create(['level'=>6,'required_experience'=>1200]);$this->assertSame(5,$this->grant($character,500)->toArray()['level_after']);CharacterProgressionSetting::whereKey(1)->update(['max_character_level'=>6]);$this->assertSame(6,$this->grant($character->fresh(),0)->toArray()['level_after']);}
}
