<?php
namespace Tests\Feature;use App\Domain\Characters\Actions\CreateCharacterAction;use App\Domain\Characters\CharacterStatsCalculator;use App\Domain\Characters\Templates\CharacterTemplateService;use App\Domain\Media\MediaAssetType;use App\Models\Character;use App\Models\CharacterClass;use App\Models\CharacterTemplate;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Storage;use Illuminate\Validation\ValidationException;use Tests\TestCase;
class CharacterTemplateTest extends TestCase{use RefreshDatabase;private function ready($overrides=[]){Storage::fake('public');$class=CharacterClass::where('code','adventurer')->firstOrFail();$t=CharacterTemplate::factory()->create(array_merge(['character_class_id'=>$class->id,'status'=>'active','base_critical_rate'=>'7.25'],$overrides));$variants=[];foreach([128,256,512]as$s){$variants[(string)$s]='ready/'.$s.'.webp';Storage::disk('public')->put($variants[(string)$s],'webp');}$t->mediaAssets()->create(['asset_type'=>MediaAssetType::BASE_VISUAL,'disk'=>'public','path'=>$variants['256'],'mime_type'=>'image/webp','width'=>256,'height'=>384,'file_size'=>4,'metadata'=>['character_visual_version'=>1,'root'=>'ready','body_type'=>$t->body_type,'canvas'=>['width'=>512,'height'=>768,'ratio'=>'2:3'],'variants'=>$variants],'is_primary'=>true,'sort_order'=>0]);return$t->fresh(['characterClass','mediaAssets']);}
public function test_schema_units_relations_and_legacy_are_safe(){$template=$this->ready();$character=Character::factory()->create(['character_template_id'=>null]);$this->assertNull($character->characterTemplate);$this->assertSame($template->id,$template->characterClass->characterTemplates()->first()->id);$a=DB::selectOne("SHOW COLUMNS FROM characters WHERE Field='base_critical_rate'");$b=DB::selectOne("SHOW COLUMNS FROM character_templates WHERE Field='base_critical_rate'");$this->assertSame($a->Type,$b->Type);$this->assertStringContainsString('unsigned',$b->Type);}
public function test_creation_copies_stats_critical_and_is_not_retroactive(){$t=$this->ready(['base_max_health'=>140,'base_attack'=>17]);$this->assertTrue(app(\App\Domain\Media\CharacterVisuals\CharacterVisualAssetService::class)->isActivationReady($t));$first=app(CreateCharacterAction::class)->execute(User::factory()->create(),'Primero',$t->id);$this->assertSame(140,$first->current_health);$this->assertSame('7.25',$first->base_critical_rate);$this->assertSame(7.25,app(CharacterStatsCalculator::class)->calculate($first)->criticalChance());$t->update(['base_attack'=>31,'base_critical_rate'=>'9.50']);$this->assertSame(17,$first->fresh()->base_attack);$this->assertTrue(app(\App\Domain\Media\CharacterVisuals\CharacterVisualAssetService::class)->isActivationReady($t->fresh(['mediaAssets'])));$second=app(CreateCharacterAction::class)->execute(User::factory()->create(),'Segundo',$t->id);$this->assertSame(31,$second->base_attack);$this->assertSame('9.50',$second->base_critical_rate);}
public function test_inactive_or_inactive_class_is_rejected_and_empty_screen_is_controlled(){$t=$this->ready(['status'=>'inactive']);try{app(CreateCharacterAction::class)->execute(User::factory()->create(),'Nope',$t->id);$this->fail();}catch(ValidationException $e){$this->assertTrue(true);}$t->update(['status'=>'active']);$t->characterClass->update(['status'=>'inactive']);try{app(CreateCharacterAction::class)->execute(User::factory()->create(),'Nope2',$t->id);$this->fail();}catch(ValidationException $e){$this->assertTrue(true);}$this->actingAs(User::factory()->create())->get(route('characters.create'))->assertOk()->assertSee('No hay plantillas de personaje disponibles en este momento.');}
public function test_morph_alias_and_previous_aliases_resolve(){$t=$this->ready();$asset=$t->mediaAssets()->first();$this->assertSame('character_template',$asset->mediable_type);$this->assertInstanceOf(CharacterTemplate::class,$asset->mediable);$character=Character::factory()->create();$legacy=$character->mediaAssets()->create(['asset_type'=>'portrait','disk'=>'public','path'=>'portrait.webp','is_primary'=>true]);$this->assertSame('character',$legacy->mediable_type);$this->assertInstanceOf(Character::class,$legacy->mediable);}
public function test_activation_requires_real_files_and_code_locks_after_use(){$t=$this->ready(['status'=>'inactive']);Storage::disk('public')->delete('ready/512.webp');try{app(CharacterTemplateService::class)->setStatus($t,'active');$this->fail();}catch(\InvalidArgumentException $e){$this->assertStringContainsString('imagen base',$e->getMessage());}$t=$this->ready(['status'=>'active']);Character::factory()->fromTemplate($t)->create();$data=$t->toArray();$data['code']='changed';unset($data['id'],$data['created_at'],$data['updated_at'],$data['characters_count']);$this->expectException(\InvalidArgumentException::class);app(CharacterTemplateService::class)->save($data,$t);}
}
