<?php
namespace Tests\Feature;
use App\Domain\Hunts\Rewards\Claim\Exceptions\InsufficientInventoryCapacityForClaimException;use App\Domain\Hunts\Rewards\Claim\HuntRewardClaimService;use App\Domain\Hunts\Rewards\HuntRewardStatus;use App\Domain\Hunts\Sessions\HuntingSessionService;use App\Models\Character;use App\Models\CharacterItem;use App\Models\CharacterWallet;use App\Models\GoldTransaction;use App\Models\HuntReward;use App\Models\HuntRewardItem;use App\Models\HuntingSession;use App\Models\MonsterLootEntry;use App\Models\User;use App\Models\Zone;use Carbon\CarbonImmutable;use Database\Seeders\CharacterLevelRequirementSeeder;use Database\Seeders\WorldCatalogSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use RuntimeException;use Tests\TestCase;
class HuntRewardClaimTest extends TestCase{use RefreshDatabase;protected function setUp():void{parent::setUp();$this->seed(WorldCatalogSeeder::class);$this->seed(CharacterLevelRequirementSeeder::class);CarbonImmutable::setTestNow('2026-07-13 12:00:00');MonsterLootEntry::query()->update(['drop_probability_ppm'=>1000000,'minimum_quantity'=>1,'maximum_quantity'=>1]);}protected function tearDown():void{CarbonImmutable::setTestNow();parent::tearDown();}private function character(array $a=[]){return Character::factory()->selected()->for(User::factory())->create($a+['base_attack'=>500]);}private function zone(){return Zone::where('code','grey_oak_forest')->firstOrFail();}private function reward(Character $c){$service=app(HuntingSessionService::class);$session=HuntingSession::find($service->start($c,$this->zone())->id());$service->tick($c,$session);return[HuntReward::latest('id')->firstOrFail(),$session];}
public function test_claim_aggregates_lines_and_is_idempotent(){list($reward)=$this->reward($c=$this->character());$line=$reward->items()->firstOrFail();HuntRewardItem::create($line->only(['hunt_reward_id','hunt_enemy_id','item_id','source_instance_identifier','item_code_snapshot','item_name_snapshot'])+['quantity'=>3]);$expectedLines=$reward->items()->count();$expectedTotal=(int)$reward->items()->sum('quantity');$generated=$reward->generated_at->copy();$first=app(HuntRewardClaimService::class)->claimAllPendingForCharacter($c)->toArray();$this->assertSame(1,$first['claimed_rewards_count']);$this->assertSame($expectedLines,$first['claimed_item_lines_count']);$this->assertSame($expectedTotal,$first['claimed_total_quantity']);$this->assertSame($expectedTotal,(int)CharacterItem::where('character_id',$c->id)->sum('quantity'));$this->assertSame(0,$first['pending_rewards_summary']['rewards_count']);$this->assertTrue($reward->fresh()->generated_at->equalTo($generated));$this->assertNotNull($reward->fresh()->claimed_at);$second=app(HuntRewardClaimService::class)->claimAllPendingForCharacter($c)->toArray();$this->assertSame(0,$second['claimed_rewards_count']);$this->assertSame($expectedTotal,(int)CharacterItem::sum('quantity'));}
public function test_global_claim_includes_multiple_sessions_and_preserves_states(){list($first,$stopped)=$this->reward($c=$this->character());app(HuntingSessionService::class)->stop($c,$stopped);list($second,$running)=$this->reward($c);$result=app(HuntRewardClaimService::class)->claimAllPendingForCharacter($c)->toArray();$this->assertSame(2,$result['claimed_rewards_count']);$this->assertSame('stopped',$stopped->fresh()->status);$this->assertSame('running',$running->fresh()->status);$this->assertTrue($first->fresh()->claimed_at->equalTo($second->fresh()->claimed_at));}
public function test_empty_and_inactive_item_rewards_are_claimable(){list($empty,$session)=$this->reward($c=$this->character());$empty->items()->delete();app(HuntingSessionService::class)->stop($c,$session);list($reward)=$this->reward($c);$item=$reward->items()->firstOrFail()->item;$item->update(['status'=>'inactive']);$lineCount=$reward->items()->count();$result=app(HuntRewardClaimService::class)->claimAllPendingForCharacter($c)->toArray();$this->assertSame(2,$result['claimed_rewards_count']);$this->assertSame($lineCount,$result['claimed_item_lines_count']);$this->assertTrue(CharacterItem::where('item_id',$item->id)->exists());}
public function test_non_stackable_exact_capacity_and_insufficient_rollback(){list($reward)=$this->reward($c=$this->character(['base_inventory_slots'=>10]));$line=$reward->items()->firstOrFail();$line->item->update(['is_stackable'=>false,'max_stack'=>1]);$line->update(['quantity'=>3]);$total=(int)$reward->items()->sum('quantity');$c->update(['base_inventory_slots'=>$total]);$result=app(HuntRewardClaimService::class)->claimAllPendingForCharacter($c)->toArray();$this->assertSame($total,$result['inventory_capacity']['current_used_slots']);list($tooBig)=$this->reward($d=$this->character(['base_inventory_slots'=>1]));$bad=$tooBig->items()->firstOrFail();$bad->item->update(['is_stackable'=>false,'max_stack'=>1]);$bad->update(['quantity'=>2]);$missing=(int)$tooBig->items()->sum('quantity')-1;try{app(HuntRewardClaimService::class)->claimAllPendingForCharacter($d);$this->fail();}catch(InsufficientInventoryCapacityForClaimException $e){$this->assertSame($missing,$e->capacity()->missingSlotsForClaim());}$this->assertFalse(CharacterItem::where('character_id',$d->id)->exists());$this->assertSame(HuntRewardStatus::PENDING,$tooBig->fresh()->status);}
public function test_failures_during_inventory_and_reward_updates_roll_back(){list($reward)=$this->reward($c=$this->character());CharacterItem::saving(function(){throw new RuntimeException('inventory failure');});try{app(HuntRewardClaimService::class)->claimAllPendingForCharacter($c);$this->fail();}catch(RuntimeException $e){}CharacterItem::flushEventListeners();$this->assertSame(0,CharacterItem::count());$this->assertSame(HuntRewardStatus::PENDING,$reward->fresh()->status);HuntReward::saving(function(){throw new RuntimeException('reward failure');});try{app(HuntRewardClaimService::class)->claimAllPendingForCharacter($c);$this->fail();}catch(RuntimeException $e){}HuntReward::flushEventListeners();$this->assertSame(0,CharacterItem::count());$this->assertSame(HuntRewardStatus::PENDING,$reward->fresh()->status);$this->assertNull($reward->fresh()->claimed_at);}
public function test_endpoint_authorization_json_and_html(){list($reward)=$this->reward($c=$this->character());$other=$this->character();$this->actingAs($other->user)->post(route('characters.hunt-rewards.claim',$c))->assertForbidden();$this->actingAs($c->user)->postJson(route('characters.hunt-rewards.claim',$c),['reward_ids'=>[999],'quantities'=>[999]])->assertOk()->assertJsonStructure(['claimed_rewards_count','claimed_items','claimed_item_instances','stackable_items','item_instances','inventory_status','pending_projection','character_pending_rewards_summary','message']);$this->assertSame(HuntRewardStatus::CLAIMED,$reward->fresh()->status);$this->actingAs($c->user)->post(route('characters.hunt-rewards.claim',$c))->assertRedirect(route('characters.inventory.index',$c));}
public function test_claim_supports_gold_only_experience_only_and_combined_rewards(){list($gold)=$this->reward($goldCharacter=$this->character());$gold->items()->delete();$gold->update(['gold_amount'=>9,'experience_amount'=>0]);$goldResult=app(HuntRewardClaimService::class)->claimAllPendingForCharacter($goldCharacter)->toArray();$this->assertSame(9,$goldResult['claimed_gold_amount']);$this->assertSame(0,$goldResult['claimed_experience_amount']);$this->assertSame(9,(int)CharacterWallet::where('character_id',$goldCharacter->id)->value('gold_balance'));list($experience)=$this->reward($experienceCharacter=$this->character());$experience->items()->delete();$experience->update(['gold_amount'=>0,'experience_amount'=>250]);$experienceResult=app(HuntRewardClaimService::class)->claimAllPendingForCharacter($experienceCharacter)->toArray();$this->assertSame(0,$experienceResult['claimed_gold_amount']);$this->assertSame(250,$experienceResult['claimed_experience_amount']);$this->assertSame(3,$experienceCharacter->fresh()->level);$this->assertFalse(CharacterWallet::where('character_id',$experienceCharacter->id)->exists());list($combined)=$this->reward($combinedCharacter=$this->character());$combined->update(['gold_amount'=>7,'experience_amount'=>100]);$combinedResult=app(HuntRewardClaimService::class)->claimAllPendingForCharacter($combinedCharacter)->toArray();$this->assertSame(7,$combinedResult['claimed_gold_amount']);$this->assertSame(100,$combinedResult['claimed_experience_amount']);$this->assertNotEmpty($combinedResult['claimed_items']);$this->assertSame(1,GoldTransaction::where('character_id',$combinedCharacter->id)->count());}
public function test_inventory_capacity_failure_rolls_back_all_resources(){list($reward)=$this->reward($character=$this->character(['base_inventory_slots'=>1]));$line=$reward->items()->firstOrFail();$line->item->update(['is_stackable'=>false,'max_stack'=>1]);$line->update(['quantity'=>2]);$reward->update(['gold_amount'=>20,'experience_amount'=>250]);try{app(HuntRewardClaimService::class)->claimAllPendingForCharacter($character);$this->fail();}catch(InsufficientInventoryCapacityForClaimException $exception){}$this->assertFalse(CharacterItem::where('character_id',$character->id)->exists());$this->assertFalse(CharacterWallet::where('character_id',$character->id)->exists());$this->assertSame(0,GoldTransaction::where('character_id',$character->id)->count());$this->assertSame(0,$character->fresh()->experience);$this->assertSame(1,$character->fresh()->level);$this->assertSame(HuntRewardStatus::PENDING,$reward->fresh()->status);}
public function test_wallet_failure_rolls_back_inventory_experience_and_reward()
{
    list($reward) = $this->reward($character = $this->character());
    $reward->update(['gold_amount' => 1, 'experience_amount' => 250]);
    $wallet = new CharacterWallet(['character_id' => $character->id]);
    $wallet->gold_balance = PHP_INT_MAX;
    $wallet->save();
    try {
        app(HuntRewardClaimService::class)->claimAllPendingForCharacter($character);
        $this->fail('The wallet overflow should fail.');
    } catch (\InvalidArgumentException $exception) {
        $this->assertSame('Gold balance would exceed PHP_INT_MAX.', $exception->getMessage());
    }
    $this->assertFalse(CharacterItem::where('character_id', $character->id)->exists());
    $this->assertSame(PHP_INT_MAX, (int) CharacterWallet::where('character_id', $character->id)->value('gold_balance'));
    $this->assertSame(0, GoldTransaction::where('character_id', $character->id)->count());
    $this->assertSame(0, $character->fresh()->experience);
    $this->assertSame(1, $character->fresh()->level);
    $this->assertSame(HuntRewardStatus::PENDING, $reward->fresh()->status);
}
}
