<?php
namespace Tests\Feature;
use App\Domain\Hunts\HuntService;use App\Domain\Hunts\Sessions\Exceptions\ActiveHuntingSessionExistsException;use App\Domain\Hunts\Sessions\HuntingSessionService;use App\Domain\Hunts\Sessions\HuntingSessionStatus;use App\Domain\Hunts\Sessions\HuntingSessionStopReason;use App\Models\Character;use App\Models\Hunt;use App\Models\HuntingSession;use App\Models\User;use App\Models\Zone;use Carbon\CarbonImmutable;use Database\Seeders\WorldCatalogSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\DB;use Tests\TestCase;
class HuntingSessionTest extends TestCase{use RefreshDatabase;protected function setUp():void{parent::setUp();$this->seed(WorldCatalogSeeder::class);CarbonImmutable::setTestNow(CarbonImmutable::parse('2026-07-12T12:00:00Z'));}protected function tearDown():void{CarbonImmutable::setTestNow();parent::tearDown();}private function player(){return Character::factory()->for(User::factory())->create(['base_attack'=>500]);}private function zone(){return Zone::where('code','grey_oak_forest')->firstOrFail();}
 public function test_schema_relations_and_manual_hunt_nullable_session(){$columns=DB::select("SHOW COLUMNS FROM hunting_sessions");$this->assertNotEmpty($columns);$character=$this->player();$manual=app(HuntService::class)->start($character,$this->zone());$this->assertNull(Hunt::find($manual->huntId())->hunting_session_id);}
 public function test_start_creates_no_hunt_and_rejects_second_live_session(){$character=$this->player();$service=app(HuntingSessionService::class);$result=$service->start($character,$this->zone());$session=HuntingSession::find($result->id());$this->assertSame(HuntingSessionStatus::RUNNING,$session->status);$this->assertSame(0,Hunt::count());$this->assertSame(0,$session->hunts_count);$this->assertTrue($session->next_encounter_at->equalTo($session->last_heartbeat_at));$this->expectException(ActiveHuntingSessionExistsException::class);$service->start($character,$this->zone());}
 public function test_first_tick_creates_one_associated_hunt_and_early_tick_does_not_duplicate(){$character=$this->player();$service=app(HuntingSessionService::class);$session=HuntingSession::find($service->start($character,$this->zone())->id());$first=$service->tick($character,$session)->toArray();$this->assertSame(1,Hunt::count());$this->assertSame($session->id,Hunt::first()->hunting_session_id);$this->assertSame(1,$first['hunts_count']);$this->assertSame(1,$first['victories_count']);$expected=max(3,(int)ceil(Hunt::first()->playback_duration_ms/1000));$this->assertSame($expected,$first['seconds_until_next_encounter']);$scheduled=HuntingSession::find($session->id)->next_encounter_at;$second=$service->tick($character,$session)->toArray();$this->assertSame(1,Hunt::count());$this->assertTrue($scheduled->equalTo(HuntingSession::find($session->id)->next_encounter_at));$this->assertSame(1,$second['hunts_count']);}
 public function test_late_tick_processes_only_one_and_timeout_processes_none(){$character=$this->player();$service=app(HuntingSessionService::class);$session=HuntingSession::find($service->start($character,$this->zone())->id());CarbonImmutable::setTestNow(CarbonImmutable::now()->addSeconds(20));$service->tick($character,$session);$this->assertSame(1,Hunt::count());$expired=HuntingSession::factory()->for($character)->create(['zone_id'=>$this->zone()->id,'last_heartbeat_at'=>CarbonImmutable::now()->subSeconds(31),'next_encounter_at'=>CarbonImmutable::now()->subHour()]);$state=$service->tick($character,$expired)->toArray();$this->assertSame(HuntingSessionStopReason::HEARTBEAT_TIMEOUT,$state['stop_reason']);$this->assertSame(1,Hunt::count());}
 public function test_abandoned_expired_session_does_not_block_new_start_and_stop_is_idempotent(){$character=$this->player();$old=HuntingSession::factory()->for($character)->create(['zone_id'=>$this->zone()->id,'last_heartbeat_at'=>CarbonImmutable::now()->subSeconds(31)]);$service=app(HuntingSessionService::class);$new=$service->start($character,$this->zone());$this->assertSame(HuntingSessionStopReason::HEARTBEAT_TIMEOUT,$old->fresh()->stop_reason);$session=HuntingSession::find($new->id());$first=$service->stop($character,$session)->toArray();$second=$service->stop($character,$session)->toArray();$this->assertSame(HuntingSessionStopReason::USER_STOPPED,$first['stop_reason']);$this->assertSame($first['stop_reason'],$second['stop_reason']);}
 public function test_http_json_is_controlled_and_show_does_not_mutate(){$character=$this->player();$user=$character->user;$session=HuntingSession::find(app(HuntingSessionService::class)->start($character,$this->zone())->id());$heartbeat=$session->last_heartbeat_at;$this->actingAs($user)->get(route('characters.hunting-sessions.show',[$character,$session]))->assertOk()->assertSee('Cacería conectada')->assertSee('Math.min(10000',false);$this->assertTrue($heartbeat->equalTo($session->fresh()->last_heartbeat_at));$response=$this->actingAs($user)->postJson(route('characters.hunting-sessions.tick',[$character,$session]));$response->assertOk()->assertJsonStructure(['session_id','status','server_time','next_encounter_at','seconds_until_next_encounter','consecutive_defeats','hunts_count','victories_count','defeats_count','draws_count','latest_hunt']);$this->assertArrayNotHasKey('character_id',$response->json());}
}
