<?php
namespace Tests\Feature;
use App\Domain\Shops\ShopLocationType;use App\Domain\Shops\ShopOfferCategory;use App\Domain\Shops\ShopOfferVisibility;use App\Domain\WorldCatalog\CatalogStatus;use App\Domain\WorldCatalog\ItemType;use App\Domain\WorldCatalog\ZoneType;use App\Models\Character;use App\Models\Item;use App\Models\Npc;use App\Models\Region;use App\Models\Shop;use App\Models\ShopOffer;use App\Models\ShopPurchase;use App\Models\User;use App\Models\World;use App\Models\Zone;use Illuminate\Database\QueryException;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;use Tests\TestCase;
final class ShopSchemaTest extends TestCase{use RefreshDatabase;
 private function item(){return Item::create(['code'=>'shop-test-item','name'=>'Shop test item','description'=>null,'item_type'=>ItemType::MATERIAL,'equipment_type'=>null,'rarity'=>'common','is_stackable'=>true,'max_stack'=>99,'status'=>CatalogStatus::ACTIVE]);}
 private function zone(){$world=World::create(['code'=>'shop-world','name'=>'Shop world','status'=>CatalogStatus::ACTIVE]);$region=Region::create(['world_id'=>$world->id,'code'=>'shop-region','name'=>'Shop region','status'=>CatalogStatus::ACTIVE]);return Zone::create(['region_id'=>$region->id,'code'=>'shop-zone','name'=>'Shop zone','zone_type'=>ZoneType::FIELD,'status'=>CatalogStatus::ACTIVE]);}
 private function offer(Shop $shop,Item $item){return ShopOffer::create(['shop_id'=>$shop->id,'item_id'=>$item->id,'category'=>ShopOfferCategory::MATERIALS,'quantity'=>5,'gold_price'=>250,'stock_limit'=>10,'stock_remaining'=>10,'purchase_limit_per_character'=>3,'required_character_level'=>null,'visibility'=>ShopOfferVisibility::VISIBLE,'status'=>CatalogStatus::ACTIVE,'sort_order'=>0]);}
 public function test_tables_use_expected_engine_collation_columns_and_constraints(){foreach(['npcs','shops','shop_locations','shop_offers','shop_purchases']as$table){$meta=DB::selectOne('SELECT ENGINE,TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?',[$table]);$this->assertSame('InnoDB',$meta->ENGINE);$this->assertSame('utf8mb4_unicode_ci',$meta->TABLE_COLLATION);}foreach(['portrait','portrait_path','portrait_url','banner','banner_path','banner_url','background_image']as$column){$this->assertFalse(Schema::hasColumn('npcs',$column));$this->assertFalse(Schema::hasColumn('shops',$column));}$this->assertTrue(Schema::hasColumns('shop_offers',['category','quantity','gold_price','stock_limit','stock_remaining','purchase_limit_per_character','required_character_level','visibility','status','starts_at','ends_at']));$this->assertTrue(Schema::hasColumns('shop_purchases',['shop_id','shop_offer_id','character_id','item_id','quantity_purchased','gold_spent','idempotency_key','purchased_at','metadata']));}
 public function test_models_expose_npc_flexible_location_offer_and_purchase_relations(){$npc=Npc::factory()->create();$shop=Shop::factory()->for($npc)->create();$zone=$this->zone();$location=$shop->locations()->create(['locatable_type'=>ShopLocationType::ZONE,'locatable_id'=>$zone->id,'status'=>CatalogStatus::ACTIVE]);$item=$this->item();$offer=$this->offer($shop,$item);$character=Character::factory()->for(User::factory())->create();$purchase=ShopPurchase::create(['shop_id'=>$shop->id,'shop_offer_id'=>$offer->id,'character_id'=>$character->id,'item_id'=>$item->id,'quantity_purchased'=>5,'gold_spent'=>250,'idempotency_key'=>'11111111-1111-5111-8111-111111111111','purchased_at'=>now()]);$this->assertTrue($shop->npc->is($npc));$this->assertTrue($location->locatable->is($zone));$this->assertTrue($zone->shopLocations->first()->shop->is($shop));$this->assertTrue($offer->item->is($item));$this->assertTrue($purchase->offer->is($offer));$this->assertTrue($character->shopPurchases->first()->is($purchase));}
 public function test_historical_purchase_restricts_shop_item_offer_and_character_deletion(){$shop=Shop::factory()->create();$item=$this->item();$offer=$this->offer($shop,$item);$character=Character::factory()->for(User::factory())->create();ShopPurchase::create(['shop_id'=>$shop->id,'shop_offer_id'=>$offer->id,'character_id'=>$character->id,'item_id'=>$item->id,'quantity_purchased'=>5,'gold_spent'=>250,'idempotency_key'=>'22222222-2222-5222-8222-222222222222','purchased_at'=>now()]);foreach([$shop,$offer,$item,$character]as$model){try{$model->delete();$this->fail('Historical reference was deleted.');}catch(QueryException $e){$this->assertSame('23000',(string)$e->getCode());}}$shop->update(['status'=>CatalogStatus::INACTIVE]);$this->assertSame(1,ShopPurchase::count());$this->assertSame(1,Item::whereKey($item->id)->count());}
}
