<?php
namespace Tests\Feature;
use App\Domain\Shops\ShopAvailabilityService;use App\Domain\Shops\ShopCatalogValidator;use App\Domain\Shops\ShopOfferCategory;use App\Domain\Shops\ShopOfferVisibility;use App\Domain\WorldCatalog\CatalogStatus;use App\Domain\WorldCatalog\ItemType;use App\Models\Character;use App\Models\Item;use App\Models\Shop;use App\Models\ShopOffer;use Carbon\CarbonImmutable;use Illuminate\Foundation\Testing\RefreshDatabase;use InvalidArgumentException;use Tests\TestCase;
final class ShopAvailabilityTest extends TestCase{use RefreshDatabase;
 private function offer(){$shop=Shop::factory()->create();$item=Item::create(['code'=>'availability-item','name'=>'Availability item','item_type'=>ItemType::CONSUMABLE,'rarity'=>'common','is_stackable'=>true,'max_stack'=>10,'status'=>CatalogStatus::ACTIVE]);return ShopOffer::create(['shop_id'=>$shop->id,'item_id'=>$item->id,'category'=>ShopOfferCategory::CONSUMABLES,'quantity'=>1,'gold_price'=>10,'stock_limit'=>5,'stock_remaining'=>5,'purchase_limit_per_character'=>null,'required_character_level'=>2,'visibility'=>ShopOfferVisibility::VISIBLE,'status'=>CatalogStatus::ACTIVE,'starts_at'=>null,'ends_at'=>null]);}
 public function test_visibility_and_purchase_availability_are_distinct(){$now=CarbonImmutable::parse('2026-07-22 12:00:00','UTC');$offer=$this->offer();$service=app(ShopAvailabilityService::class);$character=Character::factory()->create(['level'=>1]);$this->assertTrue($service->isOfferVisible($offer,$now));$this->assertFalse($service->isOfferPurchasable($offer,$now,$character));$character->level=2;$this->assertTrue($service->isOfferPurchasable($offer,$now,$character));$offer->stock_remaining=0;$this->assertTrue($service->isOfferVisible($offer,$now));$this->assertFalse($service->isOfferPurchasable($offer,$now,$character));}
 public function test_windows_are_start_inclusive_end_exclusive_and_future_offer_remains_visible(){$now=CarbonImmutable::parse('2026-07-22 12:00:00','UTC');$offer=$this->offer();$offer->starts_at=$now->addHour();$offer->ends_at=$now->addHours(2);$service=app(ShopAvailabilityService::class);$this->assertTrue($service->isOfferVisible($offer,$now));$this->assertFalse($service->isOfferPurchasable($offer,$now));$this->assertTrue($service->isOfferPurchasable($offer,$now->addHour()));$this->assertFalse($service->isOfferPurchasable($offer,$now->addHours(2)));}
 public function test_stock_limit_remaining_and_windows_are_validated(){$offer=$this->offer();$validator=app(ShopCatalogValidator::class);$offer->stock_remaining=6;try{$validator->validateOffer($offer);$this->fail('Invalid stock was accepted.');}catch(InvalidArgumentException $e){}$offer->stock_limit=null;try{$validator->validateOffer($offer);$this->fail('Half-unlimited stock was accepted.');}catch(InvalidArgumentException $e){}$offer->stock_remaining=null;$offer->starts_at=CarbonImmutable::parse('2026-07-23','UTC');$offer->ends_at=CarbonImmutable::parse('2026-07-22','UTC');$this->expectException(InvalidArgumentException::class);$validator->validateOffer($offer);}
}
