<?php
namespace Tests\Feature;
use App\Domain\WorldMaps\WorldMapAdminService;use App\Domain\WorldMaps\WorldMapImageService;use App\Models\World;use App\Models\WorldMap;use Database\Seeders\WorldCatalogSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Storage;use InvalidArgumentException;use Tests\TestCase;
class WorldMapUploadTest extends TestCase
{
use RefreshDatabase;
protected function setUp():void{parent::setUp();$this->seed(WorldCatalogSeeder::class);Storage::fake('public');config(['world_maps.disk'=>'public','world_maps.minimum_width'=>100,'world_maps.minimum_height'=>100,'world_maps.max_file_size_kb'=>1024]);}
public function test_accepts_real_png_and_jpeg_and_rejects_non_image_and_small_dimensions(){$service=app(WorldMapImageService::class);foreach(['map.png','map.jpg'] as $name){$stored=$service->store(UploadedFile::fake()->image($name,640,360));$this->assertTrue(Storage::disk('public')->exists($stored['image_path']));$this->assertSame(640,$stored['original_width']);$this->assertStringNotContainsString('\\',$stored['image_path']);$this->assertSame(0,preg_match('/^[A-Za-z]:/',$stored['image_path']));}foreach([UploadedFile::fake()->create('fake.png',10,'image/png'),UploadedFile::fake()->image('small.png',20,20)] as $file){try{$service->store($file);$this->fail('Expected upload rejection.');}catch(InvalidArgumentException $e){$this->assertTrue(true);}}}
public function test_metadata_separates_disk_existence_and_generated_public_url(){$world=World::first();Storage::disk('public')->put('maps/meta.png','content');$map=new WorldMap(['world_id'=>$world->id,'image_disk'=>'public','image_path'=>'maps/meta.png','original_width'=>640,'original_height'=>360,'mime_type'=>'image/png','file_size'=>7]);$metadata=app(WorldMapImageService::class)->metadata($map);$this->assertTrue($metadata['exists']);$this->assertNotEmpty($metadata['url']);$this->assertSame(640/360,$metadata['aspect_ratio']);Storage::disk('public')->delete('maps/meta.png');$this->assertFalse(app(WorldMapImageService::class)->metadata($map)['exists']);}
public function test_aspect_change_requires_confirmation_and_failure_keeps_old_reference(){$world=World::first();Storage::disk('public')->put('maps/old.png','old');$map=WorldMap::create(['world_id'=>$world->id,'code'=>'replace_map','name'=>'Replace','image_disk'=>'public','image_path'=>'maps/old.png','original_width'=>640,'original_height'=>360,'mime_type'=>'image/png','file_size'=>3,'version'=>1,'status'=>'active','is_default'=>false,'sort_order'=>0]);$data=['world_id'=>$world->id,'region_id'=>null,'code'=>$map->code,'name'=>$map->name,'description'=>null,'status'=>'active','is_default'=>false,'sort_order'=>0,'version'=>1,'confirm_aspect_ratio_change'=>false];try{app(WorldMapAdminService::class)->saveMap($data,$map,UploadedFile::fake()->image('portrait.png',200,400));$this->fail();}catch(InvalidArgumentException $e){$this->assertStringContainsString('proporción diferente',$e->getMessage());}$this->assertSame('maps/old.png',$map->fresh()->image_path);$this->assertTrue(Storage::disk('public')->exists('maps/old.png'));$data['confirm_aspect_ratio_change']=true;$saved=app(WorldMapAdminService::class)->saveMap($data,$map->fresh(),UploadedFile::fake()->image('portrait.png',200,400));$this->assertNotSame('maps/old.png',$saved->image_path);$this->assertFalse(Storage::disk('public')->exists('maps/old.png'));}
}
