<?php
namespace Tests\Feature;
use App\Models\Region;use App\Models\User;use App\Models\World;use App\Models\WorldMap;use Database\Seeders\WorldCatalogSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Storage;use Tests\TestCase;
class WorldMapEditorFixTest extends TestCase
{
use RefreshDatabase;private $admin;
protected function setUp():void{parent::setUp();$this->seed(WorldCatalogSeeder::class);Storage::fake('public');config(['world_maps.disk'=>'public','world_maps.minimum_width'=>100,'world_maps.minimum_height'=>100,'game_admin.emails'=>['editor-admin@example.test']]);$this->admin=User::factory()->create(['email'=>'editor-admin@example.test']);}
private function map($exists=true){if($exists)Storage::disk('public')->put('maps/editor.png','image');return WorldMap::create(['world_id'=>World::first()->id,'code'=>'editor_fix_map','name'=>'Editor Fix','description'=>'Exact description','image_disk'=>'public','image_path'=>'maps/editor.png','original_width'=>1672,'original_height'=>941,'mime_type'=>'image/png','file_size'=>5,'version'=>1,'status'=>$exists?'active':'inactive','is_default'=>false,'sort_order'=>3]);}
public function test_create_requires_image_and_exactly_one_context_with_spanish_message(){$world=World::first();$region=Region::first();$base=['code'=>'exact_code','name'=>'Exact Name','description'=>'Exact Description','status'=>'inactive','is_default'=>0,'sort_order'=>3];$this->actingAs($this->admin)->post(route('admin.content.world-maps.store'),array_merge($base,['world_id'=>$world->id,'region_id'=>$region->id]))->assertSessionHasErrors(['image','world_id','region_id']);$response=$this->actingAs($this->admin)->post(route('admin.content.world-maps.store'),array_merge($base,['world_id'=>'','region_id'=>'','image'=>UploadedFile::fake()->image('map.png',640,360)]));$response->assertSessionHasErrors(['world_id','region_id']);$this->assertSame('Selecciona un Mundo o una Región, pero no ambos.',session('errors')->first('world_id'));}
public function test_create_form_is_multipart_has_mutually_exclusive_inputs_and_no_ratio_confirmation(){$response=$this->actingAs($this->admin)->get(route('admin.content.world-maps.create'));$response->assertOk()->assertSee('enctype="multipart/form-data"',false)->assertSee('data-world-select',false)->assertSee('data-region-select',false)->assertDontSee('data-aspect-ratio-confirmation',false);}
public function test_values_are_persisted_without_transformation(){$region=Region::first();$this->actingAs($this->admin)->post(route('admin.content.world-maps.store'),['world_id'=>'','region_id'=>$region->id,'code'=>'eldoria_valtheria','name'=>'eldoria_valtheria_name','description'=>'eldoria_valtheria_description','image'=>UploadedFile::fake()->image('map.png',640,360),'status'=>'active','is_default'=>0,'sort_order'=>3])->assertRedirect();$this->assertDatabaseHas('world_maps',['code'=>'eldoria_valtheria','name'=>'eldoria_valtheria_name','description'=>'eldoria_valtheria_description','sort_order'=>3,'world_id'=>null,'region_id'=>$region->id]);}
public function test_editor_uses_real_viewbox_and_explicit_loading_controls(){$map=$this->map();$response=$this->actingAs($this->admin)->get(route('admin.content.world-maps.editor',$map));$response->assertOk()->assertSee('viewBox="0 0 1672 941"',false)->assertSee('Cargando imagen del mapa...')->assertSee('data-world-map-create disabled',false)->assertSee('data-world-map-save disabled',false)->assertSee('data-world-map-image',false)->assertSee('data-world-map-editor',false);}
public function test_missing_image_shows_admin_fallback_and_disabled_editor(){$map=$this->map(false);$response=$this->actingAs($this->admin)->get(route('admin.content.world-maps.editor',$map));$response->assertOk()->assertSee('La imagen del mapa no está disponible.')->assertSee('Existe en disk: false')->assertSee('Reemplazar imagen')->assertDontSee('data-world-map-image',false)->assertSee('data-world-map-create disabled',false);}
public function test_ratio_conflict_marks_confirmation_for_edit_only(){$map=$this->map();$response=$this->actingAs($this->admin)->put(route('admin.content.world-maps.update',$map),['world_id'=>$map->world_id,'region_id'=>'','code'=>$map->code,'name'=>$map->name,'description'=>$map->description,'image'=>UploadedFile::fake()->image('portrait.png',200,400),'status'=>'active','is_default'=>0,'sort_order'=>3,'version'=>1]);$response->assertSessionHas('aspect_ratio_confirmation_required',true)->assertSessionHasErrors('image');$this->actingAs($this->admin)->get(route('admin.content.world-maps.edit',$map))->assertSee('data-aspect-ratio-confirmation',false);}
public function test_editor_source_defends_cached_pending_and_failed_images_idempotently(){$source=file_get_contents(base_path('src/assets/js/world-map-editor.js'));$this->assertStringContainsString("image.addEventListener('load',resolveReady",$source);$this->assertStringContainsString("image.addEventListener('error',resolveError",$source);$this->assertStringContainsString('if(image.complete)',$source);$this->assertStringContainsString('image.naturalWidth>0&&image.naturalHeight>0',$source);$this->assertStringContainsString("imageResolved=true",$source);$this->assertStringContainsString("editor.dataset.worldMapEditorInitialized==='true'",$source);$this->assertStringContainsString("editor.dataset.worldMapEditorInitialized='true'",$source);$this->assertStringContainsString("width<=0||height<=0",$source);$this->assertStringContainsString("state==='closed'?'polygon':'polyline'",$source);$this->assertStringContainsString("state!=='closed'||!input.value",$source);$this->assertStringContainsString("matrix.inverse()",$source);$css=preg_replace('/\s+/','',file_get_contents(base_path('src/assets/scss/_world-map.scss')));$this->assertStringContainsString('width:100%;max-width:100%',$css);$this->assertStringContainsString('pointer-events:none',$css);$this->assertStringContainsString('.is-drawing.world-map-overlay{pointer-events:all',$css);}
public function test_layout_versions_compiled_assets_to_avoid_stale_editor_bundle(){$layout=file_get_contents(resource_path('views/layouts/game.blade.php'));$this->assertStringContainsString("filemtime(public_path('assets/js/main.js'))",$layout);$this->assertStringContainsString('?v={{ $mainJsVersion }}',$layout);}
}
