@extends('layouts.game')
@section('title','Inventario de '.$character->name)
@php($breadcrumbs=[['label'=>'Inicio','url'=>route('dashboard')],['label'=>'Mi personaje','url'=>route('characters.show',$character)],['label'=>'Inventario','url'=>null]])
@section('content')
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->has('claim'))<div class="alert alert-danger">{{ $errors->first('claim') }}</div>@endif
<div class="mb-4"><a href="{{ route('characters.show',$character) }}">Volver al personaje</a><h1 class="fs-3 mt-2">Inventario</h1><p class="text-secondary">Objetos distintos: {{ count($inventorySummary['inventory_items']) }}</p></div>
@isset($pendingRewardsSummary)<div class="card mb-4"><div class="card-header"><h2 class="h5 mb-0">Recompensas pendientes</h2></div><div class="card-body"><p>{{ $pendingRewardsSummary['rewards_count'] }} recompensas · {{ $pendingRewardsSummary['total_quantity'] }} unidades</p><p>Proyección: {{ $inventorySummary['pending_projection']['projected_used_slots'] }} / {{ $inventorySummary['inventory_status']['effective_capacity'] }} slots · Faltantes: {{ $inventorySummary['pending_projection']['missing_slots_for_claim'] }}</p><form method="POST" action="{{ route('characters.hunt-rewards.claim',$character) }}">@csrf<button class="btn btn-primary" type="submit" @if($pendingRewardsSummary['rewards_count']===0) disabled @endif>Reclamar todas</button></form></div></div>@endisset
<div class="row g-3 mb-4"><div class="col-md-4"><div class="card"><div class="card-body">Capacidad <strong>{{ $inventorySummary['inventory_status']['current_used_slots'] }} / {{ $inventorySummary['inventory_status']['effective_capacity'] }}</strong></div></div></div><div class="col-md-4"><div class="card"><div class="card-body">Proyección pendiente <strong>{{ $inventorySummary['pending_projection']['projected_used_slots'] }} slots</strong></div></div></div><div class="col-md-4"><div class="card"><div class="card-body">Reserva de cacería <strong>{{ $inventorySummary['pending_projection']['effective_reserve'] }}</strong></div></div></div></div>
<div class="card"><div class="card-header"><h2 class="h5 mb-0">Objetos apilables</h2></div>
@if(empty($inventorySummary['inventory_items']))<div class="card-body p-5 text-center text-secondary">El inventario está vacío.</div>@else
<div class="table-responsive"><table class="table mb-0"><thead><tr><th>Objeto</th><th>Tipo</th><th>Rareza</th><th>Total</th><th>Bloqueado</th><th>Disponible</th></tr></thead><tbody>
@foreach($inventorySummary['inventory_items'] as $entry)@php($inventoryItem=$inventoryItems->get($entry['item_id']))<tr><td><div class="d-flex align-items-center gap-2"><x-media.icon :model="$inventoryItem" :alt="'Icono de '.$entry['item_name']" :placeholder-text="$entry['item_name']" :width="40" :height="40" class="flex-shrink-0 object-fit-cover" /><div>{{ $entry['item_name'] }}<br><small>{{ $entry['item_code'] }}</small></div></div></td><td>Stack {{ $entry['max_stack'] }}</td><td>{{ $entry['used_slots'] }} slots</td><td>{{ $entry['quantity'] }}</td><td>{{ $entry['locked_quantity'] }}</td><td><strong>{{ $entry['available_quantity'] }}</strong></td></tr>@endforeach
</tbody></table></div>@endif</div>
@endsection
