@extends('layouts.game')
@section('title','Inventario de '.$character->name)
@php($breadcrumbs=[['label'=>'Inicio','url'=>route('dashboard')],['label'=>'Mi personaje','url'=>route('characters.show',$character)],['label'=>'Inventario','url'=>null]])
@section('content')
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->has('claim'))<div class="alert alert-danger">{{ $errors->first('claim') }}</div>@endif
@if($errors->has('equipment'))<div class="alert alert-danger">{{ $errors->first('equipment') }}</div>@endif
@if($errors->has('refinement'))<div class="alert alert-danger">{{ $errors->first('refinement') }}</div>@endif
@if(empty($inventorySummary['stackable_items']) && empty($inventorySummary['item_instances']))<div class="alert alert-secondary">El inventario está vacío.</div>@endif
<div class="mb-4"><a href="{{ route('characters.show',$character) }}">Volver al personaje</a><h1 class="fs-3 mt-2">Inventario</h1><p class="text-secondary">Tipos apilables: {{ count($inventorySummary['stackable_items']) }} · Objetos únicos: {{ count($inventorySummary['item_instances']) }}</p></div>
@isset($pendingRewardsSummary)<div class="card mb-4"><div class="card-header"><h2 class="h5 mb-0">Recompensas pendientes</h2></div><div class="card-body"><p>{{ $pendingRewardsSummary['rewards_count'] }} recompensas · {{ $pendingRewardsSummary['total_quantity'] }} unidades</p><p>Proyección: {{ $inventorySummary['pending_projection']['projected_used_slots'] }} / {{ $inventorySummary['inventory_status']['effective_capacity'] }} slots · Faltantes: {{ $inventorySummary['pending_projection']['missing_slots_for_claim'] }}</p><form method="POST" action="{{ route('characters.hunt-rewards.claim',$character) }}">@csrf<button class="btn btn-primary" type="submit" @if($pendingRewardsSummary['rewards_count']===0) disabled @endif>Reclamar todas</button></form></div></div>@endisset
<div class="row g-3 mb-4"><div class="col-md-4"><div class="card"><div class="card-body">Capacidad <strong>{{ $inventorySummary['inventory_status']['current_used_slots'] }} / {{ $inventorySummary['inventory_status']['effective_capacity'] }}</strong></div></div></div><div class="col-md-4"><div class="card"><div class="card-body">Proyección pendiente <strong>{{ $inventorySummary['pending_projection']['projected_used_slots'] }} slots</strong></div></div></div><div class="col-md-4"><div class="card"><div class="card-body">Reserva de cacería <strong>{{ $inventorySummary['pending_projection']['effective_reserve'] }}</strong></div></div></div></div>
<div class="card"><div class="card-header"><h2 class="h5 mb-0">Objetos apilables</h2></div>@if(empty($inventorySummary['stackable_items']))<div class="card-body p-5 text-center text-secondary">No hay objetos apilables.</div>@else<div class="table-responsive"><table class="table mb-0"><thead><tr><th>Objeto</th><th>Stack</th><th>Slots</th><th>Total</th><th>Bloqueado</th><th>Disponible</th></tr></thead><tbody>@foreach($inventorySummary['stackable_items'] as $entry)@php($inventoryItem=$inventoryItems->get($entry['item_id']))<tr><td><div class="d-flex align-items-center gap-2"><x-media.icon :model="$inventoryItem" :alt="'Icono de '.$entry['item_name']" :placeholder-text="$entry['item_name']" :width="40" :height="40" /><div>{{ $entry['item_name'] }}<br><small>{{ $entry['item_code'] }}</small></div></div></td><td>{{ $entry['max_stack'] }}</td><td>{{ $entry['used_slots'] }}</td><td>{{ $entry['quantity'] }}</td><td>{{ $entry['locked_quantity'] }}</td><td><strong>{{ $entry['available_quantity'] }}</strong></td></tr>@endforeach</tbody></table></div>@endif</div>
<div class="card mt-3"><div class="card-header"><h2 class="h5 mb-0">Objetos únicos</h2></div>@if(empty($inventorySummary['item_instances']))<div class="card-body text-secondary">No hay objetos únicos.</div>@else<div class="table-responsive"><table class="table mb-0"><thead><tr><th>Objeto y bonus</th><th>Referencia</th><th>Refinamiento</th><th>Estado</th><th>Adquirido</th><th>Acciones</th></tr></thead><tbody>
@foreach($inventorySummary['item_instances'] as $instance)@php($inventoryItem=$inventoryItems->get($instance['item_id']))<tr><td><div class="d-flex align-items-center gap-2"><x-media.icon :model="$inventoryItem" :alt="'Icono de '.$instance['item_name']" :placeholder-text="$instance['item_name']" :width="40" :height="40" /><div><span>{{ $instance['item_name'] }}</span><ul class="small mb-0">@foreach($instance['bonuses'] as $bonusName=>$bonusValue)@if($bonusValue != 0)<li>{{ str_replace('_',' ',$bonusName) }}: +{{ $bonusValue }}</li>@endif @endforeach</ul></div></div></td><td>Ref. {{ $instance['public_reference'] }}</td><td>+{{ $instance['refinement_level'] }}</td><td>{{ $instance['status'] }}</td><td>{{ $instance['acquired_at'] }}</td><td>@forelse($instance['compatible_slots'] as $slot)@php($eligibility=$instance['eligibility_by_slot'][$slot])<div class="mb-2"><div class="small"><strong>Nivel {{ $eligibility['required_level'] }}</strong> · Tu nivel: {{ $eligibility['character_level'] }}</div><div class="small">Clases: @forelse($eligibility['allowed_classes'] as $class){{ $class['name'] }}@if(!$loop->last), @endif @empty Cualquier clase @endforelse · Tu clase: {{ $eligibility['character_class_name'] ?: 'Sin clase' }}</div><div class="small {{ $eligibility['eligible']?'text-success':'text-danger' }}">{{ $eligibility['message'] }}</div><form method="POST" action="{{ route('characters.equipment.equip',$character) }}" class="d-inline-block me-1">@csrf<input type="hidden" name="item_instance_uuid" value="{{ $instance['uuid'] }}"><input type="hidden" name="slot" value="{{ $slot }}"><button class="btn btn-sm btn-outline-primary" type="submit" @if(!$eligibility['eligible']) disabled @endif>Equipar: {{ $equipmentSlotLabels[$slot] }}</button></form></div>@empty<span class="text-secondary">No equipable</span>@endforelse</td></tr>@endforeach
</tbody></table></div>@endif</div>
<div class="card mt-3"><div class="card-header"><h2 class="h5 mb-0">Refinamiento de equipamiento</h2></div>
@if(empty($refinementPreviews))<div class="card-body text-secondary">No hay instancias refinables.</div>@else
<div class="table-responsive"><table class="table mb-0"><thead><tr><th>Objeto</th><th>Nivel y probabilidad</th><th>Coste</th><th>Materiales</th><th>Consecuencia y acción</th></tr></thead><tbody>
@foreach($refinementPreviews as $preview)<tr>
<td>{{ $preview['item_name'] }}<br><small>{{ $preview['status'] }}</small>@if(!$preview['stat_modifier_configured'])<span class="d-block text-warning">Sin configuración estadística activa</span>@else<ul class="small mb-0">@foreach($preview['total_bonuses'] as $name=>$total)@if($total != 0)<li>{{ str_replace('_',' ',$name) }}: base +{{ $preview['base_bonuses'][$name] }} · refinamiento +{{ $preview['refinement_bonuses'][$name] }} · total +{{ $total }}</li>@endif @endforeach</ul>@endif</td>
<td>+{{ $preview['current_level'] }} @if($preview['next_level'] !== null)→ +{{ $preview['next_level'] }}@endif @if($preview['success_chance_basis_points'] !== null)<span class="d-block"><strong>Probabilidad:</strong> {{ $preview['success_chance_percent'] }} % ({{ $preview['success_chance_basis_points'] }} BP)</span>@endif</td>
<td>{{ $preview['gold_cost'] }} oro <small>({{ $preview['gold_available'] }} disponible)</small></td>
<td>@forelse($preview['materials'] as $material)<span class="d-block">{{ $material['item_name'] }}: {{ $material['required'] }} / {{ $material['available'] }}</span>@empty<span class="text-secondary">Sin materiales</span>@endforelse</td>
<td>@if($preview['failure_explanation'])<small class="d-block mb-2"><strong>En caso de fallo:</strong> {{ $preview['failure_explanation'] }}</small>@endif<form method="POST" action="{{ route('characters.item-instances.refine',[$character,$preview['uuid']]) }}" onsubmit="this.querySelector('button').disabled=true">@csrf<input type="hidden" name="refinement_token" value="{{ $preview['token'] }}"><button type="submit" class="btn btn-sm btn-primary" @if(!$preview['can_refine']) disabled @endif>Refinar</button></form>@if(!$preview['can_refine'])<small class="text-danger d-block">{{ $preview['unavailable_reason'] }}</small>@endif</td>
</tr>@endforeach
</tbody></table></div>@endif</div>
@endsection
