<?php
namespace App\Domain\Hunts\Playback;final class HuntingPlaybackLimits{const BASE_ATTACK_DELAY_MS=1000;const CRITICAL_EXTRA_DELAY_MS=300;const TARGET_DEFEATED_EXTRA_DELAY_MS=700;const RESULT_REVEAL_DELAY_MS=500;const LOOT_REVEAL_DELAY_MS=1000;const MIN_SEGMENT_DELAY_MS=100;const BASE_SPEED_MULTIPLIER=10000;const MAX_PLAYBACK_DURATION_MS=1800000;}
