@extends('layouts.game')
@section('title','Admin · Rarezas de Items')
@section('content')
@include('admin.content.partials.navigation')
@include('admin.content.partials.messages')
<h1>Rarezas de Items</h1><p class="text-secondary">Las cuatro rarezas son estructurales. El código no puede editarse y no se admiten nuevas rarezas.</p>
@foreach($rarities as $rarity)
<form method="POST" action="{{ route('admin.content.item-rarities.update',$rarity) }}" class="card mb-3" data-rarity-visual-form>@csrf @method('PUT')
<div class="card-body"><div class="row g-3">
<div class="col-md-2"><label class="form-label">Código</label><input class="form-control" value="{{ $rarity->code }}" disabled></div>
<div class="col-md-3"><label class="form-label">Nombre</label><input class="form-control" name="name" value="{{ old('name',$rarity->name) }}" required></div>
<div class="col-md-2"><label class="form-label">Estado</label><select class="form-select" name="status">@foreach(['active','inactive','hidden'] as $status)<option value="{{ $status }}" @if(old('status',$rarity->status)===$status) selected @endif>{{ $status }}</option>@endforeach</select></div>
<div class="col-md-2"><label class="form-label">Orden</label><input class="form-control" type="number" name="sort_order" min="1" value="{{ old('sort_order',$rarity->sort_order) }}"></div>
<div class="col-md-3"><label class="form-label">Estilo seguro (fallback)</label><select class="form-select" name="visual_style">@foreach(['neutral','blue','purple','gold'] as $style)<option value="{{ $style }}" @if(old('visual_style',$rarity->visual_style)===$style) selected @endif>{{ $style }}</option>@endforeach</select></div>
@foreach(['weapon_accuracy_bonus_basis_points'=>'Precisión arma (bp)','weapon_critical_bonus_basis_points'=>'Crítico arma (bp)','armor_evasion_bonus_basis_points'=>'Evasión defensiva (bp)','armor_speed_bonus_hundredths'=>'Velocidad defensiva (centésimas)','armor_absorb_damage_bonus_basis_points'=>'Absorb defensivo (bp)'] as $field=>$label)<div class="col-md"><label class="form-label">{{ $label }}</label><input class="form-control" type="number" min="0" name="{{ $field }}" value="{{ old($field,$rarity->{$field}) }}"></div>@endforeach
<div class="col-12"><hr><h2 class="h5">Presentación visual dinámica</h2></div>
<div class="col-md-4"><label class="form-label">Color del borde</label><div class="input-group"><input type="color" class="form-control form-control-color" value="{{ old('border_color_hex',$rarity->border_color_hex) }}" data-rarity-color-picker="border"><input class="form-control" name="border_color_hex" value="{{ old('border_color_hex',$rarity->border_color_hex) }}" pattern="#[0-9A-Fa-f]{6}" data-rarity-color-text="border" required></div></div>
<div class="col-md-4"><label class="form-label">Transparencia del borde (%)</label><input type="range" class="form-range" min="0" max="100" step=".01" value="{{ old('border_opacity_percent',$rarity->border_opacity_percent) }}" data-rarity-range="border-opacity"><input class="form-control" name="border_opacity_percent" type="number" min="0" max="100" step=".01" value="{{ old('border_opacity_percent',$rarity->border_opacity_percent) }}" data-rarity-number="border-opacity" required></div>
<div class="col-md-4"><label class="form-label">Grosor (px)</label><input class="form-control" name="border_width_px" type="number" min="1" max="5" step="1" value="{{ old('border_width_px',$rarity->border_width_px) }}" data-rarity-px="border-width" required></div>
<div class="col-md-4"><label class="form-label">Color del difuminado</label><div class="input-group"><input type="color" class="form-control form-control-color" value="{{ old('inner_glow_color_hex',$rarity->inner_glow_color_hex) }}" data-rarity-color-picker="glow"><input class="form-control" name="inner_glow_color_hex" value="{{ old('inner_glow_color_hex',$rarity->inner_glow_color_hex) }}" pattern="#[0-9A-Fa-f]{6}" data-rarity-color-text="glow" required><button class="btn btn-outline-secondary" type="button" data-rarity-copy-border>Usar color del borde</button></div></div>
<div class="col-md-4"><label class="form-label">Transparencia del difuminado (%)</label><input type="range" class="form-range" min="0" max="100" step=".01" value="{{ old('inner_glow_opacity_percent',$rarity->inner_glow_opacity_percent) }}" data-rarity-range="glow-opacity"><input class="form-control" name="inner_glow_opacity_percent" type="number" min="0" max="100" step=".01" value="{{ old('inner_glow_opacity_percent',$rarity->inner_glow_opacity_percent) }}" data-rarity-number="glow-opacity" required></div>
<div class="col-md-2"><label class="form-label">Blur (px)</label><input class="form-control" name="inner_glow_blur_px" type="number" min="0" max="40" step="1" value="{{ old('inner_glow_blur_px',$rarity->inner_glow_blur_px) }}" data-rarity-px="glow-blur" required></div>
<div class="col-md-2"><label class="form-label">Spread (px)</label><input class="form-control" name="inner_glow_spread_px" type="number" min="0" max="20" step="1" value="{{ old('inner_glow_spread_px',$rarity->inner_glow_spread_px) }}" data-rarity-px="glow-spread" required></div>
<div class="col-12"><p class="small text-warning d-none" data-rarity-visual-warning>Vista intensa: comprueba la legibilidad con fondos claros y oscuros.</p><div class="row g-3"><div class="col-md-6"><article class="item-rarity-visual rarity-preview-card" style="{{ $rarity->rarity_visual_style_attribute }}" data-rarity-preview><strong>Objeto de ejemplo</strong><span>{{ $rarity->name }}</span><small>Instancia #ABC12345</small></article></div><div class="col-md-6 bg-dark p-3 rounded"><article class="item-rarity-visual rarity-preview-card rarity-preview-card--dark" style="{{ $rarity->rarity_visual_style_attribute }}" data-rarity-preview><strong>Objeto de ejemplo</strong><span>{{ $rarity->name }}</span><small>Instancia #ABC12345</small></article></div></div></div>
</div><div class="mt-3 text-secondary">Items permitidos: {{ $rarity->items_count }} · Instancias: {{ $rarity->item_instances_count }}</div><button class="btn btn-primary mt-3">Guardar {{ $rarity->name }}</button></div></form>
@endforeach
@endsection
