<?php
namespace App\Http\Controllers\Admin\Content;
use App\Domain\GameHome\Admin\GameHomeCardService;use App\Domain\GameHome\GameHomeCardDestinationResolver;use App\Domain\GameHome\GameHomeCardDestinationType;use App\Domain\GameHome\GameHomeCardRouteCatalog;use App\Domain\GameHome\Media\GameHomeCardBannerException;use App\Domain\GameHome\Media\GameHomeCardBannerService;use App\Domain\Media\MediaAssetType;use App\Http\Controllers\Controller;use App\Http\Requests\Admin\Content\GameHomeCardRequest;use App\Models\GameHomeCard;use InvalidArgumentException;
final class GameHomeCardController extends Controller
{
 public function index(){return view('admin.content.game-home-cards.index',['cards'=>GameHomeCard::with(['mediaAssets'=>function($q){$q->where('asset_type',MediaAssetType::HOME_CARD_BANNER)->where('is_primary',true);}])->orderBy('sort_order')->orderBy('id')->get()]);}
 public function create(GameHomeCardRouteCatalog $routes,GameHomeCardDestinationResolver $resolver){return$this->form(new GameHomeCard(),$routes,$resolver);}
 public function store(GameHomeCardRequest $request,GameHomeCardService $service,GameHomeCardBannerService $banners){return$this->persist($request,$service,$banners);}
 public function edit(GameHomeCard $gameHomeCard,GameHomeCardRouteCatalog $routes,GameHomeCardDestinationResolver $resolver){$gameHomeCard->load(['mediaAssets'=>function($q){$q->where('asset_type',MediaAssetType::HOME_CARD_BANNER)->where('is_primary',true);}]);return$this->form($gameHomeCard,$routes,$resolver);}
 public function update(GameHomeCardRequest $request,GameHomeCard $gameHomeCard,GameHomeCardService $service,GameHomeCardBannerService $banners){return$this->persist($request,$service,$banners,$gameHomeCard);}
 public function activate(GameHomeCard $gameHomeCard,GameHomeCardService $service){$service->setActive($gameHomeCard,true);return back()->with('status','Card activada.');}
 public function deactivate(GameHomeCard $gameHomeCard,GameHomeCardService $service){$service->setActive($gameHomeCard,false);return back()->with('status','Card desactivada.');}
 public function destroyBanner(GameHomeCard $gameHomeCard,GameHomeCardBannerService $banners){$banners->delete($gameHomeCard);return back()->with('status','Banner eliminado.');}
 public function destroy(GameHomeCard $gameHomeCard,GameHomeCardBannerService $banners){$banners->deleteCard($gameHomeCard);return redirect()->route('admin.content.game-home-cards.index')->with('status','Card eliminada.');}
 private function persist($request,$service,$banners,$card=null){try{$saved=$service->save($request->validated(),$card);if($request->hasFile('banner'))$banners->replace($saved,$request->file('banner'));return redirect()->route('admin.content.game-home-cards.edit',$saved)->with('status',$card?'Card actualizada.':'Card creada.');}catch(GameHomeCardBannerException $e){return back()->withInput()->withErrors(['banner'=>$e->getMessage()]);}catch(InvalidArgumentException $e){return back()->withInput()->withErrors(['destination_value'=>$e->getMessage()]);}}
 private function form(GameHomeCard $card,GameHomeCardRouteCatalog $routes,GameHomeCardDestinationResolver $resolver){return view('admin.content.game-home-cards.form',['card'=>$card,'destinationTypes'=>GameHomeCardDestinationType::labels(),'routes'=>$routes->all(),'globalShops'=>$resolver->globalShopOptions(),'banner'=>$card->exists?$card->mediaAssets->first():null]);}
}
