<?php
namespace App\Http\Controllers\Admin\Content;
use App\Domain\Admin\Content\ContentAdminReadService;use App\Domain\Admin\Content\ContentAdminService;use App\Domain\Media\CatalogImages\CatalogImageException;use App\Domain\Media\CatalogImages\CatalogImageService;use App\Domain\Media\CatalogImages\CatalogImageType;use App\Http\Controllers\Controller;use App\Http\Requests\Admin\Content\MonsterRequest;use App\Models\Item;use App\Models\Monster;use InvalidArgumentException;
final class MonsterController extends Controller{
public function index(ContentAdminReadService $read){return view('admin.content.monsters.index',['monsters'=>$read->monsters()]);}public function create(ContentAdminReadService $read,CatalogImageService $images){return view('admin.content.monsters.form',['monster'=>new Monster(),'catalogImage'=>$images->presentation(CatalogImageType::MONSTER),'statuses'=>$read->statuses()]);}
public function store(MonsterRequest $request,ContentAdminService $service){try{$monster=$service->saveMonster($request->validated());return redirect()->route('admin.content.monsters.show',$monster)->with('status','Monstruo creado.');}catch(CatalogImageException $e){return back()->withInput()->withErrors(['image'=>$e->getMessage()]);}catch(InvalidArgumentException $e){return back()->withInput()->withErrors(['content'=>$e->getMessage()]);}}
public function show(Monster $monster,ContentAdminReadService $read){$monster=$read->monster($monster);return view('admin.content.monsters.show',['monster'=>$monster,'catalogImage'=>$read->monsterImage($monster),'lootRows'=>$read->lootRows($monster),'items'=>Item::orderBy('name')->get(),'statuses'=>$read->statuses()]);}public function edit(Monster $monster,ContentAdminReadService $read){$monster=$read->monster($monster);return view('admin.content.monsters.form',['monster'=>$monster,'catalogImage'=>$read->monsterImage($monster),'statuses'=>$read->statuses()]);}
public function update(MonsterRequest $request,Monster $monster,ContentAdminService $service){try{$service->saveMonster($request->validated(),$monster);return redirect()->route('admin.content.monsters.show',$monster)->with('status','Monstruo actualizado.');}catch(CatalogImageException $e){return back()->withInput()->withErrors(['image'=>$e->getMessage()]);}catch(InvalidArgumentException $e){return back()->withInput()->withErrors(['content'=>$e->getMessage()]);}}
public function destroyImage(Monster $monster,ContentAdminService $service){$service->deleteMonsterImage($monster);return back()->with('status','Imagen del Monster eliminada.');}public function destroy(Monster $monster,ContentAdminService $service){$service->deactivateMonster($monster);return back()->with('status','Monstruo desactivado; no se eliminó físicamente.');}}
