<?php
namespace App\Http\Controllers\Admin\Content;
use App\Domain\WorldMaps\Exceptions\WorldMapAspectRatioConfirmationException;use App\Domain\WorldMaps\WorldMapActionType;use App\Domain\WorldMaps\WorldMapAdminService;use App\Domain\WorldMaps\WorldMapAreaStatus;use App\Domain\WorldMaps\WorldMapImageService;use App\Domain\WorldMaps\WorldMapStatus;use App\Domain\WorldMaps\WorldMapSvgProjector;use App\Http\Controllers\Controller;use App\Http\Requests\Admin\Content\WorldMapRequest;use App\Models\Region;use App\Models\World;use App\Models\WorldMap;
final class WorldMapController extends Controller
{
public function index(){$regionId=(int)request('region_id');$region=$regionId?Region::with('world')->findOrFail($regionId):null;$maps=WorldMap::with(['world','region.world'])->when($region,function($query)use($region){$query->where('region_id',$region->id);})->orderBy('sort_order')->orderBy('name')->paginate(25)->appends(request()->query());return view('admin.content.world-maps.index',['maps'=>$maps,'contextRegion'=>$region]);}public function create(){$map=new WorldMap();$regionId=(int)request('region_id');if($regionId)$map->region_id=Region::findOrFail($regionId)->id;return$this->form($map);}public function store(WorldMapRequest $request,WorldMapAdminService $service){return$this->save($request,$service,null);}public function show(WorldMap $worldMap){return redirect()->route('admin.content.world-maps.editor',$worldMap);}public function edit(WorldMap $worldMap){return$this->form($worldMap);}public function update(WorldMapRequest $request,WorldMap $worldMap,WorldMapAdminService $service){return$this->save($request,$service,$worldMap);}public function destroy(WorldMap $worldMap,WorldMapAdminService $service){try{$service->deactivateMap($worldMap,request('version'));return back()->with('status','Mapa desactivado correctamente.');}catch(\Throwable $e){return back()->withErrors(['world_map'=>$e->getMessage()]);}}
public function editor(WorldMap $worldMap,WorldMapImageService $images,WorldMapSvgProjector $projector){$worldMap->load(['world','region.world','areas'=>function($q){$q->orderBy('z_index')->orderBy('sort_order')->orderBy('id');}]);$image=$images->metadata($worldMap);$areas=$worldMap->areas->map(function($area)use($worldMap,$projector){$payload=$area->toArray();$svgPoints=$area->polygon_points?$projector->project($area->polygon_points,$worldMap->original_width,$worldMap->original_height):'';return['model'=>$area,'payload'=>$payload,'svg_points'=>$svgPoints];});return view('admin.content.world-maps.editor',['map'=>$worldMap,'image'=>$image,'areaRows'=>$areas,'options'=>$this->options($worldMap)]);}
private function form($map){return view('admin.content.world-maps.form',['map'=>$map,'worlds'=>World::orderBy('name')->get(),'regions'=>Region::with('world')->orderBy('world_id')->orderBy('name')->get(),'statuses'=>WorldMapStatus::values()]);}private function options($map){return['statuses'=>WorldMapAreaStatus::values(),'actions'=>WorldMapActionType::operational(),'zones'=>\App\Models\Zone::with('region.world')->orderBy('name')->get(),'maps'=>WorldMap::where('id','<>',$map->id)->orderBy('name')->get(),'worlds'=>World::orderBy('name')->get(),'regions'=>Region::with('world')->orderBy('name')->get(),'internal_routes'=>config('world_maps.internal_routes',[])];}
private function save($request,$service,$map){try{$saved=$service->saveMap($request->validated(),$map,$request->file('image'));return redirect()->route('admin.content.world-maps.editor',$saved)->with('status',$map?'Mapa actualizado correctamente. Revisa los polígonos si cambiaste la imagen.':'Mapa creado correctamente.');}catch(WorldMapAspectRatioConfirmationException $e){return back()->withInput()->with('aspect_ratio_confirmation_required',true)->withErrors(['image'=>$e->getMessage()]);}catch(\Throwable $e){return back()->withInput()->withErrors(['world_map'=>$e->getMessage()]);}}
}
