@extends('layouts.game')
@section('title','Admin · Clase de personaje')
@section('content')
@include('admin.content.partials.navigation')
@include('admin.content.partials.messages')
@php($class=$row['model'])
<h1>{{ $class->exists?'Editar clase':'Crear clase' }}</h1>
@if($class->exists)<div class="alert alert-secondary">Usos actuales: {{ $class->character_templates_count }} plantillas, {{ $class->characters_count }} Characters y {{ $class->items_count }} Items. Desactivar conserva todas estas relaciones.</div>@endif
<form method="POST" enctype="multipart/form-data" action="{{ $class->exists?route('admin.content.character-classes.update',$class):route('admin.content.character-classes.store') }}">@csrf @if($class->exists)@method('PUT')@endif
<div class="row g-3"><div class="col-md-4"><label class="form-label">Código</label><input class="form-control" name="code" required maxlength="64" value="{{ old('code',$class->code) }}"><div class="form-text">Identificador técnico único. Minúsculas, números, guion y guion bajo.</div></div><div class="col-md-4"><label class="form-label">Nombre</label><input class="form-control" name="name" required maxlength="255" value="{{ old('name',$class->name) }}"></div><div class="col-md-2"><label class="form-label">Estado</label><select class="form-select" name="status" required>@foreach($statuses as $status)<option value="{{ $status }}" @if(old('status',$class->status)===$status) selected @endif>{{ $status }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Orden</label><input class="form-control" type="number" min="0" name="sort_order" required value="{{ old('sort_order',$class->sort_order) }}"></div>
<div class="col-12"><label class="form-label">Descripción</label><textarea class="form-control" name="description" rows="3">{{ old('description',$class->description) }}</textarea></div>
<div class="col-md-6"><div class="form-check mt-4"><input type="hidden" name="can_dual_wield" value="0"><input class="form-check-input" type="checkbox" name="can_dual_wield" value="1" id="can-dual-wield" @if(old('can_dual_wield',$class->can_dual_wield)) checked @endif><label class="form-check-label" for="can-dual-wield">Puede usar dos armas de una mano</label></div></div>
<div class="col-md-4"><label class="form-label">Icono opcional</label><input class="form-control" type="file" name="icon" accept="image/png,image/jpeg,image/webp"><div class="form-text">PNG, JPG o WebP. Máximo 5 MB.</div></div><div class="col-md-2"><img src="{{ $row['icon']->url128() }}" width="128" height="128" alt="Vista previa del icono" class="catalog-image-thumbnail"></div></div>
<button class="btn btn-primary mt-3">Guardar</button></form>
@if($class->exists)<div class="d-flex flex-wrap gap-2 mt-3"><form method="POST" action="{{ route('admin.content.character-classes.activate',$class) }}">@csrf @method('PATCH')<button class="btn btn-outline-success">Activar</button></form><form method="POST" action="{{ route('admin.content.character-classes.deactivate',$class) }}">@csrf @method('PATCH')<button class="btn btn-outline-warning">Inactivar</button></form><form method="POST" action="{{ route('admin.content.character-classes.hide',$class) }}">@csrf @method('PATCH')<button class="btn btn-outline-secondary">Ocultar</button></form>@if($row['icon']->exists())<form method="POST" action="{{ route('admin.content.character-classes.icon.destroy',$class) }}">@csrf @method('DELETE')<button class="btn btn-outline-danger">Eliminar icono</button></form>@endif</div>@endif
@endsection
