<?php
namespace Tests\Feature\Admin\Content;
use App\Models\Character;use App\Models\Region;use App\Models\User;use App\Models\World;use App\Models\WorldMap;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Storage;use Tests\TestCase;
class AdminWorldTest extends TestCase
{
use RefreshDatabase;private $admin;
protected function setUp():void{parent::setUp();Storage::fake('public');config(['game_admin.emails'=>['world-admin@example.test']]);$this->admin=User::factory()->create(['email'=>'world-admin@example.test']);}
public function test_admin_access_list_order_count_preview_fallback_and_menu(){$later=$this->world('later','Zeta',20,'inactive');$first=$this->world('first','Alpha',10);$this->region($first,'alpha_region');$this->get(route('admin.content.worlds.index'))->assertRedirect('/login');$this->actingAs(User::factory()->create())->get(route('admin.content.worlds.index'))->assertForbidden();DB::flushQueryLog();DB::enableQueryLog();$response=$this->actingAs($this->admin)->get(route('admin.content.worlds.index'));$queries=count(DB::getQueryLog());DB::disableQueryLog();$response->assertOk()->assertSeeInOrder([$first->name,$later->name])->assertSee('Mundos')->assertSee('Regiones')->assertSee('default-world-64.webp')->assertSee('<td>1</td>',false);$this->assertLessThanOrEqual(12,$queries);}
public function test_world_crud_validation_and_status_preserve_relations(){$payload=$this->worldPayload('new_world');$this->actingAs($this->admin)->post(route('admin.content.worlds.store'),$payload)->assertRedirect();$world=World::where('code','new_world')->firstOrFail();$region=$this->region($world,'kept_region');$map=WorldMap::factory()->for($region)->create(['world_id'=>null,'code'=>'kept_map']);$this->post(route('admin.content.worlds.store'),$payload)->assertSessionHasErrors('code');$this->post(route('admin.content.worlds.store'),$this->worldPayload('bad_status',['status'=>'unknown']))->assertSessionHasErrors('status');$this->post(route('admin.content.worlds.store'),$this->worldPayload('bad_order',['sort_order'=>-1]))->assertSessionHasErrors('sort_order');$this->put(route('admin.content.worlds.update',$world),$this->worldPayload('new_world',['name'=>'Mundo actualizado','description'=>null]))->assertRedirect();$this->assertSame('Mundo actualizado',$world->fresh()->name);$this->patch(route('admin.content.worlds.deactivate',$world))->assertRedirect();$this->assertSame('inactive',$world->fresh()->status);$this->assertDatabaseHas('regions',['id'=>$region->id,'world_id'=>$world->id]);$this->assertDatabaseHas('world_maps',['id'=>$map->id,'region_id'=>$region->id]);$this->patch(route('admin.content.worlds.activate',$world))->assertRedirect();$this->assertSame('active',$world->fresh()->status);}
public function test_world_cover_is_managed_by_media_assets_and_used_publicly(){$this->actingAs($this->admin)->post(route('admin.content.worlds.store'),$this->worldPayload('pictured',['image'=>UploadedFile::fake()->image('world.png',96,64)]))->assertRedirect();$world=World::where('code','pictured')->firstOrFail();$asset=$world->mediaAssets()->where('asset_type','image')->where('is_primary',true)->firstOrFail();$this->get(route('admin.content.worlds.index'))->assertOk()->assertSee($asset->metadata['variants']['64']);$this->get(route('admin.content.worlds.edit',$world))->assertOk()->assertSee($asset->metadata['variants']['128']);Character::factory()->selectedFor($this->admin)->create();$this->get(route('worlds.index'))->assertOk()->assertSee('/storage/'.$asset->metadata['variants']['256'],false);$this->delete(route('admin.content.worlds.image.destroy',$world))->assertRedirect();$this->assertDatabaseMissing('media_assets',['id'=>$asset->id]);$this->get(route('worlds.index'))->assertOk()->assertSee('Vista no disponible');$this->post(route('admin.content.worlds.store'),$this->worldPayload('bad_image',['image'=>UploadedFile::fake()->create('world.svg',10,'image/svg+xml')]))->assertSessionHasErrors('image');}
public function test_nested_region_is_authoritative_and_existing_region_cannot_move(){$world=$this->world('parent','Mundo padre',1);$other=$this->world('other','Otro mundo',2);$payload=$this->regionPayload($world,'nested');$this->actingAs($this->admin)->get(route('admin.content.worlds.regions.create',$world))->assertOk()->assertSee($world->name)->assertSee('type="hidden" name="world_id"',false);$this->post(route('admin.content.worlds.regions.store',$world),$payload)->assertRedirect();$region=Region::where('code','nested')->firstOrFail();$this->assertSame($world->id,$region->world_id);$this->post(route('admin.content.worlds.regions.store',$world),array_merge($payload,['code'=>'spoofed','world_id'=>$other->id]))->assertSessionHasErrors('world_id');$this->put(route('admin.content.regions.update',$region),array_merge($payload,['world_id'=>$other->id]))->assertSessionHasErrors('world_id');$this->assertSame($world->id,$region->fresh()->world_id);$foreign=$this->region($other,'foreign');$this->get(route('admin.content.worlds.regions.index',$world))->assertOk()->assertSee($region->name)->assertDontSee($foreign->name);$this->get(route('admin.content.worlds.edit',$world))->assertOk()->assertSee($region->name)->assertDontSee($foreign->name);}
public function test_region_form_supports_active_and_inactive_current_world_with_compatible_query(){$active=$this->world('active_form','Mundo activo',1);$inactive=$this->world('inactive_form','Mundo inactivo',2,'inactive');$activeRegion=$this->region($active,'active_region');$inactiveRegion=$this->region($inactive,'inactive_region');$this->actingAs($this->admin)->get(route('admin.content.regions.edit',$activeRegion))->assertOk()->assertSee($active->name)->assertSee('type="hidden" name="world_id"',false)->assertSee('La pertenencia queda bloqueada');$this->get(route('admin.content.regions.edit',$inactiveRegion))->assertOk()->assertSee($inactive->name)->assertSee('type="hidden" name="world_id"',false)->assertSee('La pertenencia queda bloqueada');$this->get(route('admin.content.regions.create'))->assertOk()->assertSee($active->name)->assertDontSee($inactive->name);$source=file_get_contents(app_path('Domain/Admin/Content/WorldContentAdminReadService.php'));$this->assertStringNotContainsString('orWhere'.'Key(', $source);}
public function test_region_map_action_filters_existing_maps_without_mutating_them(){$world=$this->world('maps','Mundo mapas',1);$region=$this->region($world,'mapped');$other=$this->region($world,'other_region');$map=WorldMap::factory()->for($region)->create(['world_id'=>null,'code'=>'expected_map','name'=>'Mapa esperado']);WorldMap::factory()->for($other)->create(['world_id'=>null,'code'=>'foreign_map','name'=>'Mapa ajeno']);$this->actingAs($this->admin)->get(route('admin.content.world-maps.index',['region_id'=>$region->id]))->assertOk()->assertSee('Mapa esperado')->assertDontSee('Mapa ajeno')->assertSee($region->name);$this->get(route('admin.content.world-maps.create',['region_id'=>$region->id]))->assertOk()->assertSee('value="'.$region->id.'"',false)->assertSee(' selected ',false);$this->assertSame(2,WorldMap::count());$this->assertSame($region->id,$map->fresh()->region_id);}
private function world($code,$name,$order,$status='active'){return World::create(['code'=>$code,'name'=>$name,'description'=>null,'status'=>$status,'sort_order'=>$order]);}
private function region(World $world,$code){return Region::create(array_merge($this->regionPayload($world,$code),['name'=>ucfirst($code)]));}
private function worldPayload($code,array $overrides=[]){return array_merge(['code'=>$code,'name'=>'Mundo de prueba','description'=>null,'status'=>'active','sort_order'=>10],$overrides);}
private function regionPayload(World $world,$code){return['world_id'=>$world->id,'code'=>$code,'name'=>'Región de prueba','description'=>null,'recommended_level_min'=>1,'recommended_level_max'=>10,'status'=>'active','sort_order'=>10];}
}
