<?php
namespace Tests\Feature\Admin\Content;
use App\Models\Item;use App\Models\Monster;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Storage;use Tests\TestCase;
class CatalogImageAdminTest extends TestCase{use RefreshDatabase;private $admin;private $temporary=[];protected function setUp():void{parent::setUp();Storage::fake('public');config(['game_admin.emails'=>['images@example.test']]);$this->admin=User::factory()->create(['email'=>'images@example.test']);}protected function tearDown():void{foreach($this->temporary as$path)if(file_exists($path))unlink($path);parent::tearDown();}
public function test_item_create_list_replace_and_delete_image(){unset($this->itemPayload()['image']);$this->actingAs($this->admin)->post(route('admin.content.items.store'),$this->itemPayload('admin_image_item',$this->image('png')))->assertRedirect();$item=Item::where('code','admin_image_item')->firstOrFail();$asset=$item->mediaAssets()->where('asset_type','icon')->where('is_primary',true)->firstOrFail();$this->assertStringEndsWith('/128.webp',$asset->path);$this->get(route('admin.content.items.index'))->assertOk()->assertSee($asset->metadata['variants']['64'])->assertSee('loading="lazy"',false)->assertSee('width="64"',false);$oldRoot=$asset->metadata['catalog_image_root'];$this->put(route('admin.content.items.update',$item),$this->itemPayload('admin_image_item',$this->image('jpg')))->assertRedirect();$new=$item->mediaAssets()->where('asset_type','icon')->where('is_primary',true)->firstOrFail();$this->assertNotSame($oldRoot,$new->metadata['catalog_image_root']);Storage::disk('public')->assertMissing($oldRoot);$this->get(route('admin.content.items.edit',$item))->assertSee($new->metadata['variants']['128'])->assertSee('multipart/form-data',false);$this->delete(route('admin.content.items.image.destroy',$item))->assertRedirect();$this->assertDatabaseHas('items',['id'=>$item->id]);$this->assertDatabaseMissing('media_assets',['id'=>$new->id]);}
public function test_monster_create_list_replace_and_delete_image(){ $this->actingAs($this->admin)->post(route('admin.content.monsters.store'),$this->monsterPayload('admin_image_monster',$this->image('webp')))->assertRedirect();$monster=Monster::where('code','admin_image_monster')->firstOrFail();$asset=$monster->mediaAssets()->where('asset_type','portrait')->where('is_primary',true)->firstOrFail();$this->get(route('admin.content.monsters.index'))->assertOk()->assertSee($asset->metadata['variants']['64'])->assertSee('decoding="async"',false);$this->get(route('admin.content.monsters.edit',$monster))->assertSee($asset->metadata['variants']['128'])->assertSee('Eliminar imagen');$this->delete(route('admin.content.monsters.image.destroy',$monster))->assertRedirect();$this->assertDatabaseHas('monsters',['id'=>$monster->id]);$this->assertDatabaseMissing('media_assets',['id'=>$asset->id]);}
public function test_image_is_optional_validation_is_spanish_and_normal_user_is_forbidden(){ $this->actingAs($this->admin)->post(route('admin.content.items.store'),$this->itemPayload('without_image'))->assertRedirect();$this->assertDatabaseHas('items',['code'=>'without_image']);$bad=$this->raw('<svg/>','bad.svg','image/svg+xml');$this->post(route('admin.content.items.store'),$this->itemPayload('bad_image',$bad))->assertSessionHasErrors('image');$item=Item::where('code','without_image')->firstOrFail();$this->actingAs(User::factory()->create())->delete(route('admin.content.items.image.destroy',$item))->assertForbidden();}
public function test_item_and_monster_lists_have_bounded_queries_for_media(){for($i=0;$i<8;$i++){Item::create($this->itemModel('bounded_item_'.$i));Monster::create($this->monsterModel('bounded_monster_'.$i));}DB::flushQueryLog();DB::enableQueryLog();$this->actingAs($this->admin)->get(route('admin.content.items.index'))->assertOk();$items=count(DB::getQueryLog());DB::flushQueryLog();$this->get(route('admin.content.monsters.index'))->assertOk();$monsters=count(DB::getQueryLog());DB::disableQueryLog();$this->assertLessThanOrEqual(12,$items);$this->assertLessThanOrEqual(12,$monsters);}
private function itemPayload($code='unused',$image=null){return array_merge($this->itemModel($code),['required_level'=>1,'character_class_ids'=>[],'max_health_bonus'=>0,'attack_bonus'=>0,'defense_bonus'=>0,'accuracy_bonus'=>0,'evasion_bonus'=>0,'critical_chance_bonus'=>0,'attack_speed_bonus'=>0],$image?['image'=>$image]:[]);}private function itemModel($code){return['code'=>$code,'name'=>'Image Item','description'=>null,'item_type'=>'material','equipment_type'=>null,'rarity'=>'common','is_stackable'=>1,'max_stack'=>99,'status'=>'active'];}
private function monsterPayload($code,$image=null){return array_merge($this->monsterModel($code),$image?['image'=>$image]:[]);}private function monsterModel($code){return['code'=>$code,'name'=>'Image Monster','description'=>null,'level'=>1,'max_health'=>20,'attack'=>3,'defense'=>2,'accuracy_rate'=>70,'evasion_rate'=>2,'critical_chance'=>1,'experience_reward'=>5,'gold_min'=>1,'gold_max'=>2,'status'=>'active'];}
private function image($format){$path=$this->temp();$image=imagecreatetruecolor(64,96);$color=imagecolorallocate($image,30,120,220);imagefill($image,0,0,$color);if($format==='png')imagepng($image,$path);elseif($format==='jpg')imagejpeg($image,$path);else imagewebp($image,$path);imagedestroy($image);return new UploadedFile($path,'image.'.$format,$format==='jpg'?'image/jpeg':'image/'.$format,null,true);}private function raw($content,$name,$mime){$path=$this->temp();file_put_contents($path,$content);return new UploadedFile($path,$name,$mime,null,true);}private function temp(){$path=tempnam(sys_get_temp_dir(),'admin_image_');$this->temporary[]=$path;return$path;}}
