<?php
namespace Tests\Feature\Admin\Content;
use App\Domain\Characters\Progression\CharacterProgressionConfigurationService;use App\Models\Character;use App\Models\CharacterLevelRequirement;use App\Models\CharacterProgressionRevision;use App\Models\CharacterProgressionSetting;use App\Models\User;use Database\Seeders\CharacterLevelRequirementSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\DB;use InvalidArgumentException;use Tests\TestCase;
final class CharacterProgressionAdminTest extends TestCase
{
 use RefreshDatabase;private $admin;
 protected function setUp():void{parent::setUp();$this->seed(CharacterLevelRequirementSeeder::class);config(['game_admin.emails'=>['progression-admin@example.test']]);$this->admin=User::factory()->create(['email'=>'progression-admin@example.test']);}
 private function payload($overrides=[]){$curve=CharacterLevelRequirement::orderBy('level')->get()->map(function($r){return['level'=>(string)$r->level,'required_experience'=>(string)$r->required_experience];})->all();return array_merge(['max_character_level'=>'5','version'=>(string)CharacterProgressionSetting::findOrFail(1)->version,'reason'=>'Ajuste de balance controlado','curve'=>$curve],$overrides);}
 public function test_global_setting_schema_and_access(){$setting=CharacterProgressionSetting::findOrFail(1);$this->assertSame(5,$setting->max_character_level);$this->assertSame(1,$setting->version);$this->assertLessThanOrEqual((int)CharacterLevelRequirement::max('level'),$setting->max_character_level);$table=DB::selectOne('SELECT ENGINE,TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?',['character_progression_settings']);$this->assertSame('InnoDB',$table->ENGINE);$this->get(route('admin.content.progression.index'))->assertRedirect('/login');$this->actingAs(User::factory()->create())->get(route('admin.content.progression.index'))->assertForbidden();$this->actingAs($this->admin)->get(route('admin.content.progression.index'))->assertOk()->assertSee('EXP acumulada requerida para alcanzar este nivel')->assertSee('NIVEL MÁXIMO ACTUAL');}
 public function test_admin_update_is_versioned_and_audited(){$this->actingAs($this->admin)->put(route('admin.content.progression.update'),$this->payload())->assertSessionHas('status','Configuración de progresión actualizada correctamente.');$setting=CharacterProgressionSetting::findOrFail(1);$this->assertSame(2,$setting->version);$this->assertSame($this->admin->id,$setting->updated_by);$revision=CharacterProgressionRevision::firstOrFail();$this->assertSame(5,$revision->previous_max_level);$this->assertSame(5,$revision->new_max_level);$this->assertSame('Ajuste de balance controlado',$revision->reason);$this->assertCount(5,$revision->previous_curve);$this->assertCount(5,$revision->new_curve);$this->put(route('admin.content.progression.update'),$this->payload(['version'=>'1']))->assertSessionHasErrors('version');$this->assertSame(2,$setting->fresh()->version);$this->assertSame(1,CharacterProgressionRevision::count());}
 public function test_invalid_curve_cap_reason_and_overflow_are_atomic(){$this->actingAs($this->admin);$before=CharacterLevelRequirement::orderBy('level')->pluck('required_experience','level')->all();$this->put(route('admin.content.progression.update'),$this->payload(['reason'=>'']))->assertSessionHasErrors('reason');$curve=$this->payload()['curve'];$curve[2]['level']='4';$this->put(route('admin.content.progression.update'),$this->payload(['curve'=>$curve]))->assertSessionHasErrors();$curve=$this->payload()['curve'];$curve[2]['required_experience']='100';$this->put(route('admin.content.progression.update'),$this->payload(['curve'=>$curve]))->assertSessionHasErrors();$curve=$this->payload()['curve'];$curve[2]['required_experience']='1.5';$this->put(route('admin.content.progression.update'),$this->payload(['curve'=>$curve]))->assertSessionHasErrors();$curve=$this->payload()['curve'];$curve[2]['required_experience']='9223372036854775808';$this->put(route('admin.content.progression.update'),$this->payload(['curve'=>$curve]))->assertSessionHasErrors();$this->put(route('admin.content.progression.update'),$this->payload(['max_character_level'=>'6']))->assertSessionHasErrors();$this->assertSame($before,CharacterLevelRequirement::orderBy('level')->pluck('required_experience','level')->all());$this->assertSame(1,CharacterProgressionSetting::find(1)->version);$this->assertSame(0,CharacterProgressionRevision::count());}
 public function test_cap_cannot_drop_below_existing_character(){Character::factory()->for(User::factory())->create(['level'=>5,'experience'=>850]);$this->expectException(InvalidArgumentException::class);app(CharacterProgressionConfigurationService::class)->update($this->admin,$this->payload(['max_character_level'=>'4']));}
 public function test_atomic_replacement_allows_a_threshold_to_take_an_old_unique_value(){$curve=$this->payload()['curve'];$curve[1]['required_experience']='250';$curve[2]['required_experience']='300';$curve[3]['required_experience']='500';$curve[4]['required_experience']='900';app(CharacterProgressionConfigurationService::class)->update($this->admin,$this->payload(['curve'=>$curve]));$this->assertSame([0,250,300,500,900],CharacterLevelRequirement::orderBy('level')->pluck('required_experience')->map(function($v){return(int)$v;})->all());$this->assertSame(2,CharacterProgressionSetting::find(1)->version);$this->assertSame(1,CharacterProgressionRevision::count());}
 public function test_atomic_update_also_handles_a_lower_level_taking_the_old_value_of_the_next_level(){$curve=$this->payload()['curve'];$curve[1]['required_experience']='50';$curve[2]['required_experience']='100';$curve[3]['required_experience']='300';$curve[4]['required_experience']='600';app(CharacterProgressionConfigurationService::class)->update($this->admin,$this->payload(['curve'=>$curve]));$this->assertSame([0,50,100,300,600],CharacterLevelRequirement::orderBy('level')->pluck('required_experience')->map(function($value){return(int)$value;})->all());}
 public function test_admin_can_prepare_consecutive_levels_without_changing_the_cap(){$curve=$this->payload()['curve'];$curve[]=['level'=>'6','required_experience'=>'1300'];$curve[]=['level'=>'7','required_experience'=>'1900'];$this->actingAs($this->admin)->put(route('admin.content.progression.update'),$this->payload(['curve'=>$curve]))->assertSessionHasNoErrors();$this->assertSame(5,CharacterProgressionSetting::findOrFail(1)->max_character_level);$this->assertSame([6=>1300,7=>1900],CharacterLevelRequirement::where('level','>',5)->orderBy('level')->pluck('required_experience','level')->map(function($value){return(int)$value;})->all());$revision=CharacterProgressionRevision::firstOrFail();$this->assertCount(7,$revision->new_curve);$this->actingAs($this->admin)->get(route('admin.content.progression.index'))->assertOk()->assertSee('PREPARADO PARA FUTURA AMPLIACIÓN')->assertSee('value="1300"',false);}
 public function test_prepared_level_can_be_activated_later(){$curve=$this->payload()['curve'];$curve[]=['level'=>'6','required_experience'=>'1300'];app(CharacterProgressionConfigurationService::class)->update($this->admin,$this->payload(['curve'=>$curve]));$payload=$this->payload(['max_character_level'=>'6','reason'=>'Activar nivel preparado']);app(CharacterProgressionConfigurationService::class)->update($this->admin,$payload);$this->assertSame(6,CharacterProgressionSetting::findOrFail(1)->max_character_level);$this->assertSame(2,CharacterProgressionRevision::count());}
 public function test_only_the_final_prepared_level_can_be_removed(){$curve=$this->payload()['curve'];$curve[]=['level'=>'6','required_experience'=>'1300'];$curve[]=['level'=>'7','required_experience'=>'1900'];app(CharacterProgressionConfigurationService::class)->update($this->admin,$this->payload(['curve'=>$curve]));array_pop($curve);app(CharacterProgressionConfigurationService::class)->update($this->admin,$this->payload(['curve'=>$curve,'version'=>'2','reason'=>'Retirar último nivel preparado']));$this->assertFalse(CharacterLevelRequirement::where('level',7)->exists());$this->assertTrue(CharacterLevelRequirement::where('level',6)->exists());$active=array_slice($curve,0,4);try{app(CharacterProgressionConfigurationService::class)->update($this->admin,$this->payload(['curve'=>$active,'version'=>'3']));$this->fail('An active level was removed.');}catch(InvalidArgumentException $e){$this->assertStringContainsString('exceeds the configured curve',$e->getMessage());}$this->assertSame(6,(int)CharacterLevelRequirement::max('level'));}
 public function test_invalid_new_levels_are_atomic_and_ui_exposes_curve_controls(){$this->actingAs($this->admin)->get(route('admin.content.progression.index'))->assertOk()->assertSee('+ Agregar siguiente nivel')->assertSee('Eliminar último nivel')->assertSee('data-experience-delta',false);$before=CharacterLevelRequirement::orderBy('level')->pluck('required_experience','level')->all();$curve=$this->payload()['curve'];$curve[]=['level'=>'7','required_experience'=>'1300'];$this->put(route('admin.content.progression.update'),$this->payload(['curve'=>$curve]))->assertSessionHasErrors();$curve=$this->payload()['curve'];$curve[]=['level'=>'6','required_experience'=>'850'];$this->put(route('admin.content.progression.update'),$this->payload(['curve'=>$curve]))->assertSessionHasErrors();$this->assertSame($before,CharacterLevelRequirement::orderBy('level')->pluck('required_experience','level')->all());$this->assertSame(0,CharacterProgressionRevision::count());}
}
