<?php
namespace Tests\Feature\Admin\Content;
use App\Models\Item;use App\Models\Npc;use App\Models\Shop;use App\Models\User;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
final class ShopSaleConfigurationAdminTest extends TestCase{use RefreshDatabase;private $admin;protected function setUp():void{parent::setUp();config(['game_admin.emails'=>['sales-admin@example.test']]);$this->admin=User::factory()->create(['email'=>'sales-admin@example.test']);}
public function test_admin_can_configure_and_disable_item_sale_without_losing_price(){$this->actingAs($this->admin)->post(route('admin.content.items.store'),$this->item(['is_sellable'=>1,'sell_price'=>125]))->assertRedirect();$item=Item::where('code','sale_admin_item')->firstOrFail();$this->assertTrue($item->is_sellable);$this->assertSame(125,$item->sell_price);$this->put(route('admin.content.items.update',$item),$this->item(['is_sellable'=>0,'sell_price'=>125,'unexpected_field'=>'ignored']))->assertRedirect();$item->refresh();$this->assertFalse($item->is_sellable);$this->assertSame(125,$item->sell_price);$this->assertFalse(isset($item->unexpected_field));}
public function test_protected_item_type_and_zero_sellable_price_are_rejected(){$this->actingAs($this->admin)->post(route('admin.content.items.store'),$this->item(['item_type'=>'quest','is_sellable'=>1,'sell_price'=>10]))->assertSessionHasErrors('sell_price');$this->post(route('admin.content.items.store'),$this->item(['code'=>'zero_price','is_sellable'=>1,'sell_price'=>0]))->assertSessionHasErrors('sell_price');}
public function test_admin_converts_shop_percentage_exactly_and_preserves_it_when_disabled(){$npc=Npc::factory()->create();$this->actingAs($this->admin)->post(route('admin.content.shops.store'),$this->shop($npc,['buys_items'=>1,'purchase_rate_percent'=>'75.25']))->assertRedirect();$shop=Shop::where('code','sale-shop')->firstOrFail();$this->assertTrue($shop->buys_items);$this->assertSame(7525,$shop->purchase_rate_basis_points);$this->put(route('admin.content.shops.update',$shop),$this->shop($npc,['buys_items'=>0,'purchase_rate_percent'=>'75.25','unexpected_field'=>'ignored']))->assertRedirect();$shop->refresh();$this->assertFalse($shop->buys_items);$this->assertSame(7525,$shop->purchase_rate_basis_points);$this->get(route('admin.content.shops.edit',$shop))->assertOk()->assertSee('value="75.25"',false);}
public function test_invalid_shop_percentages_are_rejected(){foreach(['0','0.001','100.01','abc']as$rate){$npc=Npc::factory()->create();$this->actingAs($this->admin)->post(route('admin.content.shops.store'),$this->shop($npc,['code'=>'shop-'.$npc->id,'purchase_rate_percent'=>$rate]))->assertSessionHasErrors();}}
public function test_legacy_item_payload_and_sale_disable_keep_safe_contracts(){$legacy=$this->item(['code'=>'legacy_sale_fields']);unset($legacy['is_sellable'],$legacy['sell_price']);$this->actingAs($this->admin)->post(route('admin.content.items.store'),$legacy)->assertRedirect()->assertSessionHasNoErrors();$item=Item::where('code','legacy_sale_fields')->firstOrFail();$this->assertFalse($item->is_sellable);$this->assertSame(0,$item->sell_price);$sellable=$this->item(['code'=>'disable_sale_item','is_sellable'=>1,'sell_price'=>125]);$this->post(route('admin.content.items.store'),$sellable)->assertRedirect()->assertSessionHasNoErrors();$item=Item::where('code','disable_sale_item')->firstOrFail();$this->put(route('admin.content.items.update',$item),array_merge($sellable,['is_sellable'=>0]))->assertRedirect()->assertSessionHasNoErrors();$item->refresh();$this->assertFalse($item->is_sellable);$this->assertSame(125,$item->sell_price);$this->post(route('admin.content.items.store'),$this->item(['code'=>'still_zero','is_sellable'=>1,'sell_price'=>0]))->assertSessionHasErrors('sell_price');$this->post(route('admin.content.items.store'),$this->item(['code'=>'still_protected','item_type'=>'quest','is_sellable'=>1,'sell_price'=>10]))->assertSessionHasErrors('sell_price');}
private function item(array $overrides=[]){return array_merge(['code'=>'sale_admin_item','name'=>'Sale Admin Item','description'=>null,'item_type'=>'material','equipment_type'=>null,'rarity'=>'common','is_stackable'=>1,'max_stack'=>99,'is_sellable'=>0,'sell_price'=>0,'status'=>'active','max_health_bonus'=>0,'attack_bonus'=>0,'defense_bonus'=>0,'accuracy_bonus'=>0,'evasion_bonus'=>0,'critical_chance_bonus'=>0,'attack_speed_bonus'=>0],$overrides);}private function shop(Npc $npc,array $overrides=[]){return array_merge(['code'=>'sale-shop','name'=>'Sale Shop','description'=>null,'npc_id'=>$npc->id,'buys_items'=>0,'purchase_rate_percent'=>'100','status'=>'active','starts_at'=>null,'ends_at'=>null,'sort_order'=>0],$overrides);}}
