<?php
namespace Tests\Feature\Admin\Content;
use App\Domain\Admin\Content\ContentAdminService;use App\Domain\Hunts\HuntService;use App\Models\Character;use App\Models\Region;use App\Models\User;use App\Models\Zone;use App\Models\ZoneEncounterSize;use Database\Seeders\WorldCatalogSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
class ZoneEncounterConfigurationTest extends TestCase{use RefreshDatabase;private $admin;private $region;
protected function setUp():void{parent::setUp();config(['game_admin.emails'=>['admin@example.test']]);$this->admin=User::factory()->create(['email'=>'admin@example.test']);$this->seed(WorldCatalogSeeder::class);$this->region=Region::firstOrFail();}
private function payload($sizes,$code='encounter_zone'){return['region_id'=>$this->region->id,'code'=>$code,'name'=>'Encounter Zone','description'=>null,'zone_type'=>'field','recommended_level_min'=>1,'recommended_level_max'=>5,'is_safe'=>0,'allows_hunting'=>1,'status'=>'active','sort_order'=>99,'encounter_sizes'=>$sizes];}
public function test_create_form_defaults_and_edit_form_load_persisted_values(){$this->actingAs($this->admin)->get(route('admin.content.zones.create'))->assertOk()->assertSee('Cantidad de monstruos por encuentro')->assertSee('name="encounter_sizes[1]" value="100"',false)->assertSee('name="encounter_sizes[2]" value="0"',false)->assertSee('name="encounter_sizes[3]" value="0"',false)->assertSee('Máximo administrable actual: 3 monstruos por encuentro.');$zone=Zone::where('code','grey_oak_forest')->firstOrFail();app(ContentAdminService::class)->saveZone($this->payload([1=>60,2=>30,3=>10],$zone->code),$zone);$this->get(route('admin.content.zones.edit',$zone))->assertOk()->assertSee('name="encounter_sizes[1]" value="60"',false)->assertSee('name="encounter_sizes[2]" value="30"',false)->assertSee('name="encounter_sizes[3]" value="10"',false);}
public function test_admin_saves_valid_combinations_without_duplicates(){foreach([[100,0,0],[0,100,0],[0,0,100],[60,30,10],[0,50,50]]as$index=>$values){$sizes=[1=>$values[0],2=>$values[1],3=>$values[2]];$code='valid_zone_'.$index;$this->actingAs($this->admin)->post(route('admin.content.zones.store'),$this->payload($sizes,$code))->assertRedirect();$zone=Zone::where('code',$code)->firstOrFail();$this->assertSame(3,$zone->encounterSizeConfigs()->whereIn('enemy_count',[1,2,3])->count());foreach($sizes as$count=>$weight)$this->assertDatabaseHas('zone_encounter_sizes',['zone_id'=>$zone->id,'enemy_count'=>$count,'weight'=>$weight,'is_active'=>$weight>0,'sort_order'=>$count*10]);$this->put(route('admin.content.zones.update',$zone),$this->payload($sizes,$code))->assertRedirect();$this->assertSame(3,$zone->encounterSizeConfigs()->whereIn('enemy_count',[1,2,3])->count());}}
public function test_invalid_combinations_and_non_admin_are_rejected(){$invalid=[[1=>99,2=>0,3=>0],[1=>101,2=>0,3=>0],[1=>-1,2=>101,3=>0],[1=>0,2=>0,3=>101],[1=>50,2=>50,4=>0],[1=>50,2=>50]];foreach($invalid as$index=>$sizes){$this->actingAs($this->admin)->post(route('admin.content.zones.store'),$this->payload($sizes,'invalid_'.$index))->assertSessionHasErrors();$this->assertDatabaseMissing('zones',['code'=>'invalid_'.$index]);}$this->actingAs(User::factory()->create())->post(route('admin.content.zones.store'),$this->payload([1=>100,2=>0,3=>0],'forbidden'))->assertForbidden();$this->assertDatabaseMissing('zones',['code'=>'forbidden']);}
public function test_service_is_transactional_preserves_higher_rows_and_generates_two_or_three_repeated_enemies(){$zone=Zone::where('code','grey_oak_forest')->firstOrFail();ZoneEncounterSize::create(['zone_id'=>$zone->id,'enemy_count'=>4,'weight'=>1,'is_active'=>false,'sort_order'=>40]);foreach([2,3]as$count){app(ContentAdminService::class)->saveZone($this->payload([1=>0,2=>$count===2?100:0,3=>$count===3?100:0],$zone->code),$zone);$character=Character::factory()->for(User::factory())->create(['base_attack'=>500]);$result=app(HuntService::class)->start($character,$zone);$this->assertSame($count,$result->enemyCount());$this->assertCount($count,array_unique(array_map(function($enemy){return$enemy->instanceIdentifier();},$result->enemies())));}$this->assertDatabaseHas('zone_encounter_sizes',['zone_id'=>$zone->id,'enemy_count'=>4,'weight'=>1]);try{app(ContentAdminService::class)->saveZone($this->payload([1=>50,2=>40,3=>9],'rollback_zone'));$this->fail('Invalid total accepted.');}catch(\InvalidArgumentException $e){$this->assertDatabaseMissing('zones',['code'=>'rollback_zone']);}}
public function test_seeder_adds_three_rows_idempotently_and_preserves_custom_ratios(){$zone=Zone::where('code','grey_oak_forest')->firstOrFail();app(ContentAdminService::class)->saveZone($this->payload([1=>0,2=>50,3=>50],$zone->code),$zone);$this->seed(WorldCatalogSeeder::class);$this->seed(WorldCatalogSeeder::class);$rows=$zone->encounterSizeConfigs()->whereIn('enemy_count',[1,2,3])->orderBy('enemy_count')->get();$this->assertCount(3,$rows);$this->assertSame([0,50,50],$rows->pluck('weight')->map(function($v){return(int)$v;})->all());}
}
