<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Schema;
class CreateHuntEnemiesAndConvertHunts extends Migration{
 public function up(){
  Schema::create('hunt_enemies',function(Blueprint $t){$t->engine='InnoDB';$t->charset='utf8mb4';$t->collation='utf8mb4_unicode_ci';$t->id();$t->foreignId('hunt_id')->constrained('hunts')->cascadeOnDelete();$t->foreignId('monster_id')->constrained('monsters')->onDelete('restrict');$t->unsignedInteger('position');$t->string('instance_identifier',191);$t->string('monster_code_snapshot',64);$t->string('monster_name_snapshot',191);$t->unsignedInteger('initial_health');$t->unsignedInteger('final_health');$t->string('status',20);$t->timestamps();$t->unique(['hunt_id','position']);$t->unique(['hunt_id','instance_identifier'],'hunt_enemy_instance_unique');$t->index('monster_id');});
  Schema::table('hunts',function(Blueprint $t){$t->unsignedInteger('enemy_count')->nullable()->after('zone_name');});
  $invalid=DB::table('hunts as h')->leftJoin('monsters as m','m.id','=','h.monster_id')->whereNull('m.id')->exists();if($invalid)throw new RuntimeException('Historical Hunt references an invalid Monster.');
  DB::table('hunts')->orderBy('id')->chunkById(500,function($hunts){$ids=[];$rows=[];$now=now();foreach($hunts as $h){$monster=DB::table('monsters')->where('id',$h->monster_id)->first();if(!$monster)throw new RuntimeException('Historical Hunt cannot be converted.');$ids[]=$h->id;$rows[]=['hunt_id'=>$h->id,'monster_id'=>$h->monster_id,'position'=>1,'instance_identifier'=>'monster:'.$h->monster_id.':1','monster_code_snapshot'=>$monster->code,'monster_name_snapshot'=>$h->monster_name,'initial_health'=>$h->monster_health_before,'final_health'=>$h->monster_health_after,'status'=>$h->monster_health_after<=0?'defeated':'alive','created_at'=>$now,'updated_at'=>$now];}if($rows)DB::table('hunt_enemies')->insert($rows);if($ids)DB::table('hunts')->whereIn('id',$ids)->update(['enemy_count'=>1]);},'id');
  $bad=DB::table('hunts as h')->leftJoin(DB::raw('(SELECT hunt_id,COUNT(*) total FROM hunt_enemies GROUP BY hunt_id) e'),'e.hunt_id','=','h.id')->where(function($q){$q->whereNull('e.total')->orWhere('e.total','<>',1)->orWhere('h.enemy_count','<>',1);})->exists();$orphans=DB::table('hunt_enemies as e')->leftJoin('hunts as h','h.id','=','e.hunt_id')->whereNull('h.id')->exists();if($bad||$orphans)throw new RuntimeException('Historical Hunt verification failed.');
  DB::statement('ALTER TABLE hunts MODIFY enemy_count INT UNSIGNED NOT NULL');
  Schema::table('hunts',function(Blueprint $t){$t->dropForeign(['monster_id']);$t->dropIndex(['monster_id']);$t->dropColumn(['monster_id','monster_name','monster_health_before','monster_health_after']);});
 }
 public function down(){
  $invalid=DB::table('hunts as h')->leftJoin(DB::raw('(SELECT hunt_id,COUNT(*) total FROM hunt_enemies GROUP BY hunt_id) e'),'e.hunt_id','=','h.id')->where(function($q){$q->whereNull('e.total')->orWhere('e.total','<>',1)->orWhere('h.enemy_count','<>',1);})->exists();if($invalid)throw new RuntimeException('Rollback cannot represent multi-enemy Hunts without data loss.');
  Schema::table('hunts',function(Blueprint $t){$t->unsignedBigInteger('monster_id')->nullable()->after('zone_name');$t->string('monster_name',191)->nullable()->after('monster_id');$t->unsignedInteger('monster_health_before')->nullable();$t->unsignedInteger('monster_health_after')->nullable();});
  DB::table('hunts')->orderBy('id')->chunkById(500,function($hunts){foreach($hunts as $h){$e=DB::table('hunt_enemies')->where('hunt_id',$h->id)->first();if(!$e)throw new RuntimeException('HuntEnemy backfill missing.');DB::table('hunts')->where('id',$h->id)->update(['monster_id'=>$e->monster_id,'monster_name'=>$e->monster_name_snapshot,'monster_health_before'=>$e->initial_health,'monster_health_after'=>$e->final_health]);}},'id');
  if(DB::table('hunts')->whereNull('monster_id')->orWhereNull('monster_name')->orWhereNull('monster_health_before')->orWhereNull('monster_health_after')->exists())throw new RuntimeException('Rollback backfill verification failed.');
  DB::statement('ALTER TABLE hunts MODIFY monster_id BIGINT UNSIGNED NOT NULL, MODIFY monster_name VARCHAR(191) NOT NULL, MODIFY monster_health_before INT UNSIGNED NOT NULL, MODIFY monster_health_after INT UNSIGNED NOT NULL');
  Schema::table('hunts',function(Blueprint $t){$t->index('monster_id');$t->foreign('monster_id')->references('id')->on('monsters')->onDelete('restrict');});Schema::drop('hunt_enemies');Schema::table('hunts',function(Blueprint $t){$t->dropColumn('enemy_count');});
 }
}
