@extends('layouts.game') @section('title','Admin · Item') @section('content')
@include('admin.content.partials.navigation') @include('admin.content.partials.messages')
<h1>{{ $item->exists?'Editar Item':'Crear Item' }}</h1><form method="POST" enctype="multipart/form-data" action="{{ $item->exists?route('admin.content.items.update',$item):route('admin.content.items.store') }}">@csrf @if($item->exists)@method('PUT')@endif<div class="row g-3">
@foreach(['code'=>'Código','name'=>'Nombre'] as $field=>$label)<div class="col-md-6"><label class="form-label">{{ $label }}</label><input class="form-control" name="{{ $field }}" value="{{ old($field,$item->{$field}) }}" required></div>@endforeach<div class="col-12"><label>Descripción</label><textarea class="form-control" name="description">{{ old('description',$item->description) }}</textarea></div>
@foreach(['item_type'=>$options['item_types'],'equipment_type'=>$options['equipment_types'],'rarity'=>$options['rarities'],'status'=>$options['statuses']] as $field=>$values)<div class="col-md-3"><label>{{ $field }}</label><select class="form-select" name="{{ $field }}"><option value="">—</option>@foreach($values as $value)<option value="{{ $value }}" @if(old($field,$item->{$field})===$value) selected @endif>{{ $value }}</option>@endforeach</select></div>@endforeach
<div class="col-md-6"><label class="form-label">Requisito de manos</label><select class="form-select" name="hand_requirement"><option value="">Compatibilidad heredada / no aplica</option>@foreach($options['hand_requirements'] as $value=>$label)<option value="{{ $value }}" @if(old('hand_requirement',$item->hand_requirement)===$value) selected @endif>{{ $label }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Familia funcional</label><select class="form-select" name="equipment_family"><option value="">Compatibilidad heredada / no aplica</option>@foreach($options['equipment_families'] as $value=>$label)<option value="{{ $value }}" @if(old('equipment_family',$item->equipment_family)===$value) selected @endif>{{ $label }}</option>@endforeach</select></div>
@if($item->exists && $item->equipment_type==='weapon' && $item->hand_requirement===null && $item->equipment_family===null)<div class="col-12"><div class="alert alert-warning mb-0">Este objeto utiliza compatibilidad heredada y solo puede equiparse en la mano principal hasta que se clasifique.</div></div>@endif
<div class="col-md-3"><label>Apilable</label><select class="form-select" name="is_stackable"><option value="0" @if(!old('is_stackable',$item->is_stackable)) selected @endif>No</option><option value="1" @if(old('is_stackable',$item->is_stackable)) selected @endif>Sí</option></select></div><div class="col-md-3"><label>Max stack</label><input class="form-control" type="number" min="1" name="max_stack" value="{{ old('max_stack',$item->max_stack?:1) }}"></div>
<div class="col-md-4"><label class="form-label">Nivel mínimo requerido</label><input class="form-control" type="number" min="1" max="65535" name="required_level" value="{{ old('required_level',$item->required_level?:1) }}"></div><div class="col-md-8"><label class="form-label">Clases permitidas</label><select class="form-select" name="character_class_ids[]" multiple size="5">@foreach($options['character_classes'] as $class)<option value="{{ $class['id'] }}" @if(in_array($class['id'],old('character_class_ids',$options['selected_character_class_ids']),true)) selected @endif>{{ $class['name'] }} ({{ $class['code'] }}) · {{ $class['status'] }}</option>@endforeach</select></div>
@foreach(['max_health_bonus','attack_bonus','defense_bonus','accuracy_bonus','evasion_bonus','critical_chance_bonus','attack_speed_bonus'] as $field)<div class="col-md-3"><label>{{ $field }}</label><input class="form-control" type="number" min="0" step="{{ in_array($field,['critical_chance_bonus','attack_speed_bonus'])?'0.01':'1' }}" name="{{ $field }}" value="{{ old($field,$item->{$field}?:0) }}"></div>@endforeach
</div>@include('admin.content.partials.catalog-image-upload',['model'=>$item,'catalogImage'=>$catalogImage])<button class="btn btn-primary mt-3">Guardar</button></form>
@if($item->exists && $catalogImage->exists())<form method="POST" action="{{ route('admin.content.items.image.destroy',$item) }}" class="mt-2" onsubmit="return confirm('¿Eliminar la imagen actual del Item?')">@csrf @method('DELETE')<button class="btn btn-outline-danger" type="submit">Eliminar imagen</button></form>@endif
@if($item->exists && $visualLayers['enabled'])
<section class="card mt-4"><div class="card-body"><h2 class="h5">Apariencia equipada</h2><p class="text-secondary">Capas transparentes 512 × 768 px, independientes de la imagen cuadrada del inventario.</p>
<div class="row g-3 mb-3">@forelse($visualLayers['assets'] as $layer)<div class="col-md-4"><div class="border rounded p-2 h-100"><img src="{{ $layer->mediaAsset->url() }}" class="img-fluid d-block mx-auto" style="max-height:240px" alt="Capa {{ $visualLayers['slot_labels'][$layer->visual_slot] }}"><div><strong>{{ $layer->body_type }}</strong><br>{{ $visualLayers['slot_labels'][$layer->visual_slot] }}</div><form method="POST" action="{{ route('admin.content.items.visual-assets.destroy',[$item,$layer]) }}" class="mt-2">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Eliminar capa</button></form></div></div>@empty<div class="col-12 text-secondary">No hay capas configuradas.</div>@endforelse</div>
<form method="POST" enctype="multipart/form-data" action="{{ route('admin.content.items.visual-assets.store',$item) }}">@csrf<div class="row g-3"><div class="col-md-4"><label class="form-label">Tipo corporal</label><select name="body_type" class="form-select" required>@foreach($visualLayers['body_types'] as $bodyType)<option value="{{ $bodyType }}">{{ $bodyType }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Canal visual</label><select name="visual_slot" class="form-select" required>@foreach($visualLayers['slots'] as $slot)<option value="{{ $slot }}">{{ $visualLayers['slot_labels'][$slot] }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">PNG o WebP</label><input type="file" name="equipment_layer" class="form-control @error('equipment_layer') is-invalid @enderror" accept="image/png,image/webp" required>@error('equipment_layer')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div><button class="btn btn-outline-primary mt-3">Cargar o reemplazar capa</button></form></div></section>
@endif
@endsection
