@extends('layouts.game') @section('title','Admin · Item') @section('content')
@include('admin.content.partials.navigation') @include('admin.content.partials.messages')
<h1>{{ $item->exists?'Editar Item':'Crear Item' }}</h1><form method="POST" action="{{ $item->exists?route('admin.content.items.update',$item):route('admin.content.items.store') }}">@csrf @if($item->exists)@method('PUT')@endif<div class="row g-3">
@foreach(['code'=>'Código','name'=>'Nombre'] as $field=>$label)<div class="col-md-6"><label class="form-label">{{ $label }}</label><input class="form-control" name="{{ $field }}" value="{{ old($field,$item->{$field}) }}" required></div>@endforeach<div class="col-12"><label>Descripción</label><textarea class="form-control" name="description">{{ old('description',$item->description) }}</textarea></div>
@foreach(['item_type'=>$options['item_types'],'equipment_type'=>$options['equipment_types'],'rarity'=>$options['rarities'],'status'=>$options['statuses']] as $field=>$values)<div class="col-md-3"><label>{{ $field }}</label><select class="form-select" name="{{ $field }}"><option value="">—</option>@foreach($values as $value)<option value="{{ $value }}" @if(old($field,$item->{$field})===$value) selected @endif>{{ $value }}</option>@endforeach</select></div>@endforeach
<div class="col-md-3"><label>Apilable</label><select class="form-select" name="is_stackable"><option value="0" @if(!old('is_stackable',$item->is_stackable)) selected @endif>No</option><option value="1" @if(old('is_stackable',$item->is_stackable)) selected @endif>Sí</option></select></div><div class="col-md-3"><label>Max stack</label><input class="form-control" type="number" min="1" name="max_stack" value="{{ old('max_stack',$item->max_stack?:1) }}"></div>
<div class="col-md-4"><label class="form-label">Nivel mínimo requerido</label><input class="form-control" type="number" min="1" max="65535" name="required_level" value="{{ old('required_level',$item->required_level?:1) }}"><div class="form-text">Nivel mínimo que debe tener el personaje para equipar este objeto.</div></div>
<div class="col-md-8"><label class="form-label">Clases permitidas</label><select class="form-select" name="character_class_ids[]" multiple size="5">@foreach($options['character_classes'] as $class)<option value="{{ $class['id'] }}" @if(in_array($class['id'],old('character_class_ids',$options['selected_character_class_ids']),true)) selected @endif>{{ $class['name'] }} ({{ $class['code'] }}) · {{ $class['status'] }}</option>@endforeach</select><div class="form-text">Si no seleccionas ninguna clase, cualquier clase podrá equiparlo.</div></div>
@foreach(['max_health_bonus','attack_bonus','defense_bonus','accuracy_bonus','evasion_bonus','critical_chance_bonus','attack_speed_bonus'] as $field)<div class="col-md-3"><label>{{ $field }}</label><input class="form-control" type="number" min="0" step="{{ in_array($field,['critical_chance_bonus','attack_speed_bonus'])?'0.01':'1' }}" name="{{ $field }}" value="{{ old($field,$item->{$field}?:0) }}"></div>@endforeach
</div><button class="btn btn-primary mt-3">Guardar</button></form>@endsection
