<?php
namespace App\Domain\Hunts;
use App\Domain\Characters\CharacterStatsCalculator;use App\Domain\Combat\CombatSide;use App\Domain\Combat\CombatSimulator;use App\Domain\Combat\Factories\CharacterCombatantFactory;use App\Domain\Combat\Factories\MonsterCombatantFactory;use App\Domain\Hunts\Data\EncounterEnemy;use App\Domain\Hunts\Data\HuntCombatEventResult;use App\Domain\Hunts\Data\HuntEnemyResult;use App\Domain\Hunts\Data\HuntResult;use App\Domain\Hunts\Exceptions\InvalidHuntingZoneException;use App\Domain\Hunts\Playback\HuntingPlaybackCalculator;use App\Domain\Hunts\Playback\HuntingPlaybackSpeedProvider;use App\Domain\Hunts\Sessions\Data\HuntExecutionContext;use App\Domain\WorldCatalog\CatalogStatus;use App\Models\Character;use App\Models\Hunt;use App\Models\HuntingSession;use App\Models\Zone;use App\Models\ZoneEncounterSize;use Carbon\CarbonImmutable;use Illuminate\Support\Collection;use Illuminate\Support\Facades\DB;use InvalidArgumentException;use RuntimeException;
final class HuntService{
 private $sizeSelector,$monsterSelector,$calculator,$characterFactory,$monsterFactory,$combat,$enemyPersister,$eventPersister,$playback,$speed;
 public function __construct(EncounterSizeSelector $size,WeightedMonsterSelector $monster,CharacterStatsCalculator $calculator,CharacterCombatantFactory $characterFactory,MonsterCombatantFactory $monsterFactory,CombatSimulator $combat,HuntEnemyPersister $enemyPersister,HuntCombatEventPersister $eventPersister,HuntingPlaybackCalculator $playback,HuntingPlaybackSpeedProvider $speed){$this->sizeSelector=$size;$this->monsterSelector=$monster;$this->calculator=$calculator;$this->characterFactory=$characterFactory;$this->monsterFactory=$monsterFactory;$this->combat=$combat;$this->enemyPersister=$enemyPersister;$this->eventPersister=$eventPersister;$this->playback=$playback;$this->speed=$speed;}
 public function start(Character $character,Zone $zone):HuntResult{if(!$character->exists||!$zone->exists)throw new InvalidArgumentException('Persisted entities required.');return DB::transaction(function()use($character,$zone){$locked=Character::whereKey($character->id)->lockForUpdate()->firstOrFail();return$this->executeLocked($locked,$zone,null);},3);}
 public function startForLockedSession(Character $lockedCharacter,Zone $zone,HuntExecutionContext $context):HuntResult{return$this->executeLocked($lockedCharacter,$zone,$context);}
 private function executeLocked(Character $character,Zone $zone,HuntExecutionContext $context=null){
  $started=CarbonImmutable::now();$lockedZone=Zone::whereKey($zone->id)->lockForUpdate()->firstOrFail();if($lockedZone->status!==CatalogStatus::ACTIVE||!$lockedZone->allows_hunting)throw new InvalidHuntingZoneException('Esta zona no permite cacerías.');
  $configs=ZoneEncounterSize::where('zone_id',$lockedZone->id)->orderBy('sort_order')->orderBy('id')->lockForUpdate()->get();$count=$this->sizeSelector->select($configs);$eligible=$this->monsterSelector->eligibleEntries($lockedZone,$character);$selected=$this->monsterSelector->selectMany($eligible,$count);$encounter=[];
  foreach($selected as $index=>$monster){$position=$index+1;$identifier='monster:'.$monster->id.':'.$position;$encounter[]=new EncounterEnemy($identifier,$position,$monster->id,$monster->code,$monster->name,$this->monsterFactory->make($monster,$identifier));}
  $statsBreakdown=$this->calculator->breakdown($character);$player=$this->characterFactory->make($character,$statsBreakdown->effective());$combat=$this->combat->simulateEncounter($player,array_map(function($enemy){return$enemy->combatantStats();},$encounter));$resolvedAt=CarbonImmutable::now();$actions=[];foreach($combat->rounds() as $round)foreach($round->actions() as $action)$actions[]=$action;
  $session=$context?HuntingSession::whereKey($context->huntingSessionId())->firstOrFail():null;$multiplier=$this->speed->multiplier($character,$lockedZone,$resolvedAt,$session);$playback=$this->playback->calculate($actions,$combat->status(),$multiplier);
  $playerResult=$combat->participant($player->identifier());if(!$playerResult)throw new RuntimeException('Player combat result missing.');$enemyResults=[];$participants=[];foreach($combat->participants() as $participant){$participants[$participant->identifier()]=$participant;if($participant->sideIdentifier()===CombatSide::ENEMIES){if(isset($enemyResults[$participant->identifier()]))throw new RuntimeException('Duplicate enemy result identifier.');$enemyResults[$participant->identifier()]=$participant;}}
  if(count($enemyResults)!==count($encounter))throw new RuntimeException('Unexpected enemy result count.');
  $hunt=Hunt::create(['hunting_session_id'=>$context?$context->huntingSessionId():null,'character_id'=>$character->id,'character_name'=>$character->name,'zone_id'=>$lockedZone->id,'zone_name'=>$lockedZone->name,'enemy_count'=>count($encounter),'status'=>$combat->status(),'rounds_count'=>$combat->roundsCount(),'character_health_before'=>$playerResult->initialHealth(),'character_health_after'=>$playerResult->finalHealth(),'character_stats_snapshot'=>$statsBreakdown->toSnapshotArray(),'started_at'=>$started,'completed_at'=>$resolvedAt,'resolved_at'=>$resolvedAt,'combat_events_duration_ms'=>$playback->combatEventsDurationMs(),'result_reveal_duration_ms'=>$playback->resultRevealDurationMs(),'loot_reveal_duration_ms'=>$playback->lootRevealDurationMs(),'playback_duration_ms'=>$playback->playbackDurationMs(),'playback_speed_multiplier'=>$playback->speedMultiplier()]);
  $created=[];$seen=[];foreach($encounter as $enemy){$id=$enemy->instanceIdentifier();if(!isset($enemyResults[$id]))throw new RuntimeException('Enemy combat result missing.');$participant=$enemyResults[$id];unset($enemyResults[$id]);$created[]=$this->enemyPersister->create($hunt,['monster_id'=>$enemy->monsterId(),'position'=>$enemy->position(),'instance_identifier'=>$id,'monster_code_snapshot'=>$enemy->monsterCodeSnapshot(),'monster_name_snapshot'=>$enemy->monsterNameSnapshot(),'initial_health'=>$participant->initialHealth(),'final_health'=>$participant->finalHealth(),'status'=>HuntEnemyStatus::fromFinalHealth($participant->finalHealth())]);$seen[$id]=true;}
  if($enemyResults||count($created)!==$hunt->enemy_count||count($seen)!==$hunt->enemy_count)throw new RuntimeException('Persisted encounter invariant failed.');foreach($created as $index=>$row)if($row->position!==$index+1)throw new RuntimeException('Enemy positions are not consecutive.');
  $this->eventPersister->persist($hunt,$playback,array_fill_keys(array_keys($participants),true));$hunt->setRelation('enemies',collect($created));$hunt->load('combatEvents');return$this->entry($hunt);
 }
 public function history(Character $character,int $limit=50):Collection{return$character->hunts()->with('enemies')->latest()->limit($limit)->get()->map(function($hunt){return$this->entry($hunt);});}
 public function detail(Character $character,$huntId):HuntResult{return$this->entry($character->hunts()->with(['enemies','combatEvents'])->whereKey($huntId)->firstOrFail());}
 private function entry(Hunt $hunt){$enemies=$hunt->enemies->map(function($enemy){return new HuntEnemyResult($enemy->position,$enemy->instance_identifier,$enemy->monster_id,$enemy->monster_code_snapshot,$enemy->monster_name_snapshot,$enemy->initial_health,$enemy->final_health,$enemy->status);})->all();$events=$hunt->relationLoaded('combatEvents')?$hunt->combatEvents->map(function($event){return new HuntCombatEventResult($event->only(['sequence','round','actor_identifier','target_identifier','event_type','did_hit','hit_probability','hit_roll','critical_probability','critical_roll','is_critical','damage','healing','target_health_before','target_health_after','playback_offset_ms','playback_duration_ms']));})->all():[];return new HuntResult($hunt->id,$hunt->character_id,$hunt->character_name,$hunt->zone_id,$hunt->zone_name,$hunt->status,$hunt->rounds_count,$hunt->character_health_before,$hunt->character_health_after,$hunt->enemy_count,$enemies,$hunt->started_at->toIso8601String(),$hunt->completed_at->toIso8601String(),$hunt->resolved_at->toIso8601String(),$hunt->combat_events_duration_ms,$hunt->result_reveal_duration_ms,$hunt->loot_reveal_duration_ms,$hunt->playback_duration_ms,$hunt->playback_speed_multiplier,$events);}
}
