<?php
namespace App\Domain\Media\CatalogImages;
use App\Domain\Media\CatalogImages\Data\CatalogImageUpload;use App\Domain\Media\CatalogImages\Data\CatalogImageView;use App\Domain\Media\MediaAssetService;use App\Models\MediaAsset;use Illuminate\Database\Eloquent\Model;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Log;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;use Throwable;
final class CatalogImageService{
const VERSION=1;const DISK='public';const QUALITY=82;const MAX_BYTES=5242880;const MIN_DIMENSION=32;const MAX_DIMENSION=4096;const MAX_PIXELS=16777216;const SIZES=[64,128,256];private $media;public function __construct(MediaAssetService $media){$this->media=$media;}
public function replace(Model $model,$type,UploadedFile $file){CatalogImageType::assertModel($type,$model);$upload=$this->process($type,$file);try{$result=DB::transaction(function()use($model,$type,$upload){return$this->media->replacePrimary($model,['asset_type'=>CatalogImageType::assetType($type),'disk'=>$upload->disk(),'path'=>$upload->canonicalPath(),'mime_type'=>'image/webp','width'=>128,'height'=>128,'file_size'=>Storage::disk($upload->disk())->size($upload->canonicalPath()),'metadata'=>$upload->metadata(),'sort_order'=>0,'is_primary'=>true]);},3);}catch(Throwable $e){$this->deleteDirectory($upload->disk(),$upload->root(),false);throw$e;}if($result['previous'])$this->deletePhysicalAsset($result['previous']);return$result['asset'];}
public function delete(Model $model,$type){CatalogImageType::assertModel($type,$model);$old=DB::transaction(function()use($model,$type){return$this->media->deletePrimary($model,CatalogImageType::assetType($type));},3);if($old)$this->deletePhysicalAsset($old);}
public function presentation($type,MediaAsset $asset=null){CatalogImageType::assetType($type);$disk=$asset?$asset->disk:null;$canonical=$asset?$asset->path:null;$metadata=$asset&&is_array($asset->metadata)?$asset->metadata:[];$variants=$this->validVariants($metadata);$urls=[];$real=false;foreach(self::SIZES as $size){$path=isset($variants[(string)$size])?$variants[(string)$size]:null;if($path&&$this->fileExists($disk,$path)){$urls[$size]=Storage::disk($disk)->url($path);$real=true;}elseif($canonical&&$this->fileExists($disk,$canonical)){$urls[$size]=Storage::disk($disk)->url($canonical);$real=true;}else{$urls[$size]=$this->fallbackUrl($type,$size);}}return new CatalogImageView($urls,$real,!$real,$disk,$canonical,$this->safeMetadata($metadata));}
public function presentationFor(Model $model,$type){CatalogImageType::assertModel($type,$model);$asset=null;if($model->relationLoaded('mediaAssets')){$asset=$model->mediaAssets->filter(function($candidate)use($type){return$candidate->asset_type===CatalogImageType::assetType($type)&&$candidate->is_primary;})->sortBy('id')->first();}return$this->presentation($type,$asset);}
public function process($type,UploadedFile $file){CatalogImageType::assetType($type);$info=$this->inspect($file);$root='game-assets/'.CatalogImageType::directory($type).'/'.date('Y').'/'.date('m').'/'.(string)Str::uuid();$disk=Storage::disk(self::DISK);$source=null;$square=null;$temporary=[];try{$original=$root.'/original.'.$info['extension'];$stream=fopen($file->getRealPath(),'rb');if($stream===false||!$disk->put($original,$stream))throw new CatalogImageException('No se pudo almacenar la imagen original.');if(is_resource($stream))fclose($stream);$source=$this->decode($file->getRealPath(),$info['mime']);$source=$this->orient($source,$file->getRealPath(),$info['mime']);$width=imagesx($source);$height=imagesy($source);$side=max($width,$height);$square=$this->transparentCanvas($side);if(!imagecopy($square,$source,(int)floor(($side-$width)/2),(int)floor(($side-$height)/2),0,0,$width,$height))throw new CatalogImageException('No se pudo centrar la imagen.');$variants=[];$variantSizes=[];foreach(self::SIZES as $size){$target=$this->transparentCanvas($size);$temp=tempnam(sys_get_temp_dir(),'catalog_webp_');$temporary[]=$temp;try{if(!imagecopyresampled($target,$square,0,0,0,0,$size,$size,$side,$side))throw new CatalogImageException('No se pudo redimensionar la imagen.');if(!imagewebp($target,$temp,self::QUALITY))throw new CatalogImageException('No se pudo generar WebP.');}finally{imagedestroy($target);}$check=getimagesize($temp);if(!$check||$check[0]!==$size||$check[1]!==$size||$check['mime']!=='image/webp'||filesize($temp)<=0)throw new CatalogImageException('La variante WebP generada no es válida.');$path=$root.'/'.$size.'.webp';$variantStream=fopen($temp,'rb');if($variantStream===false||!$disk->put($path,$variantStream))throw new CatalogImageException('No se pudo almacenar una variante.');if(is_resource($variantStream))fclose($variantStream);$variants[(string)$size]=$path;$variantSizes[(string)$size]=$disk->size($path);}foreach(array_merge([$original],array_values($variants)) as $path)if(!$disk->exists($path)||$disk->size($path)<=0)throw new CatalogImageException('El conjunto de imagen quedó incompleto.');$metadata=['catalog_image_version'=>self::VERSION,'catalog_type'=>$type,'catalog_image_root'=>$root,'variants'=>$variants,'variant_sizes'=>$variantSizes,'original'=>['path'=>$original,'mime'=>$info['mime'],'width'=>$info['width'],'height'=>$info['height'],'size'=>$info['size']]];return new CatalogImageUpload(['disk'=>self::DISK,'root'=>$root,'canonical_path'=>$variants['128'],'metadata'=>$metadata]);}catch(Throwable $e){$this->deleteDirectory(self::DISK,$root,false);if($e instanceof CatalogImageException)throw$e;throw new CatalogImageException('No se pudo procesar la imagen de catálogo.',0,$e);}finally{if(is_resource($source))imagedestroy($source);if(is_resource($square))imagedestroy($square);foreach($temporary as $temp)if(is_string($temp)&&file_exists($temp))unlink($temp);}}
private function inspect(UploadedFile $file){$path=$file->getRealPath();$size=$file->getSize();if(!$file->isValid()||!is_string($path)||!is_file($path))throw new CatalogImageException('El archivo de imagen no es válido.');if($size<=0||$size>self::MAX_BYTES)throw new CatalogImageException('La imagen no puede superar 5 MB.');$finfo=new \finfo(FILEINFO_MIME_TYPE);$fileMime=$finfo->file($path);$dimensions=@getimagesize($path);if(!$dimensions||!isset($dimensions['mime']))throw new CatalogImageException('No se pudo inspeccionar la imagen.');$allowed=['image/png'=>'png','image/jpeg'=>'jpg','image/webp'=>'webp'];if(!isset($allowed[$fileMime])||!isset($allowed[$dimensions['mime']])||$fileMime!==$dimensions['mime'])throw new CatalogImageException('Solo se permiten imágenes PNG, JPG o WebP válidas.');$width=(int)$dimensions[0];$height=(int)$dimensions[1];if($width<self::MIN_DIMENSION||$height<self::MIN_DIMENSION)throw new CatalogImageException('La imagen debe medir al menos 32 × 32 píxeles.');if($width>self::MAX_DIMENSION||$height>self::MAX_DIMENSION||$width*$height>self::MAX_PIXELS)throw new CatalogImageException('La imagen supera las dimensiones permitidas.');return['mime'=>$fileMime,'extension'=>$allowed[$fileMime],'width'=>$width,'height'=>$height,'size'=>(int)$size];}
private function decode($path,$mime){$image=false;if($mime==='image/jpeg')$image=@imagecreatefromjpeg($path);elseif($mime==='image/png')$image=@imagecreatefrompng($path);elseif($mime==='image/webp')$image=@imagecreatefromwebp($path);if($image===false)throw new CatalogImageException('La imagen está corrupta o truncada.');return$image;}
private function orient($image,$path,$mime){if($mime!=='image/jpeg'||!function_exists('exif_read_data'))return$image;$exif=@exif_read_data($path);$orientation=is_array($exif)&&isset($exif['Orientation'])?(int)$exif['Orientation']:1;$angle=$orientation===3?180:($orientation===6?-90:($orientation===8?90:0));if($angle===0)return$image;$rotated=imagerotate($image,$angle,0);if($rotated===false)throw new CatalogImageException('No se pudo corregir la orientación de la imagen.');imagealphablending($rotated,false);imagesavealpha($rotated,true);imagedestroy($image);return$rotated;}
private function transparentCanvas($size){$canvas=imagecreatetruecolor($size,$size);if($canvas===false)throw new CatalogImageException('No se pudo crear el lienzo de imagen.');imagealphablending($canvas,false);imagesavealpha($canvas,true);$transparent=imagecolorallocatealpha($canvas,0,0,0,127);imagefill($canvas,0,0,$transparent);return$canvas;}
private function validVariants(array $metadata){if(!isset($metadata['catalog_image_version'])||(int)$metadata['catalog_image_version']!==self::VERSION||!isset($metadata['variants'])||!is_array($metadata['variants']))return[];$valid=[];foreach(self::SIZES as $size){$path=isset($metadata['variants'][(string)$size])?$metadata['variants'][(string)$size]:null;if($this->relativePath($path))$valid[(string)$size]=$path;}return$valid;}
private function safeMetadata(array $metadata){$safe=[];foreach(['catalog_image_version','catalog_type','catalog_image_root','variants','variant_sizes','original'] as $key)if(array_key_exists($key,$metadata))$safe[$key]=$metadata[$key];return$safe;}
private function fileExists($disk,$path){try{return is_string($disk)&&config('filesystems.disks.'.$disk)!==null&&$this->relativePath($path)&&Storage::disk($disk)->exists($path);}catch(Throwable $e){return false;}}
private function relativePath($path){return is_string($path)&&$path!==''&&$path===trim($path)&&strpos($path,"\0")===false&&strpos($path,'\\')===false&&$path[0]!=='/'&&strpos($path,'..')===false;}
private function fallbackUrl($type,$size){return asset('assets/images/catalog/default-'.$type.'-'.$size.'.webp');}
private function deletePhysicalAsset(MediaAsset $asset){$metadata=is_array($asset->metadata)?$asset->metadata:[];$root=isset($metadata['catalog_image_root'])?$metadata['catalog_image_root']:null;if($this->relativePath($root)){$this->deleteDirectory($asset->disk,$root,true);return;}if($this->relativePath($asset->path))try{if(!Storage::disk($asset->disk)->delete($asset->path))Log::warning('No se pudo eliminar un archivo multimedia de catálogo antiguo.',['asset_id'=>$asset->id]);}catch(Throwable $e){Log::warning('Falló la limpieza de un archivo multimedia de catálogo antiguo.',['asset_id'=>$asset->id]);}}
private function deleteDirectory($disk,$root,$warn){try{$deleted=Storage::disk($disk)->deleteDirectory($root);if(!$deleted&&$warn)Log::warning('No se pudo eliminar un directorio multimedia reemplazado.',['disk'=>$disk,'root'=>$root]);}catch(Throwable $e){if($warn)Log::warning('Falló la limpieza de un directorio multimedia reemplazado.',['disk'=>$disk,'root'=>$root]);}}
}
