@extends('layouts.game')
@section('title',$character->name)
@php($breadcrumbs=[['label'=>'Inicio','url'=>route('dashboard')],['label'=>'Mi personaje','url'=>route('characters.show',$character)],['label'=>'Resumen y estadísticas','url'=>null]])
@section('content')
<div class="mb-4"><h1 class="fs-3 mb-1">{{ $character->name }}</h1><p class="text-secondary">Ficha inicial del personaje</p></div>
<div class="row g-3"><div class="col-lg-4"><div class="card h-100"><div class="card-body"><div class="text-center mb-3"><x-media.portrait :model="$character" :alt="'Retrato de '.$character->name" :placeholder-text="$character->name" :width="160" :height="160" class="img-fluid object-fit-cover" /></div><h2 class="h4">{{ $character->name }}</h2><span class="badge bg-success">{{ ucfirst($character->status) }}</span><hr><p>Nivel <strong>{{ $experienceProgress->level() }}</strong></p><p>EXP acumulada <strong>{{ $experienceProgress->experience() }}</strong></p><p>Experiencia mínima del nivel <strong>{{ $experienceProgress->currentLevelExperience() }}</strong></p>@if($experienceProgress->isMaximumLevel())<p class="fw-semibold mb-2">Nivel máximo actual alcanzado</p><div class="progress" role="progressbar" aria-label="Progreso de experiencia: nivel máximo" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"><div class="progress-bar" style="width: 100%">100%</div></div>@else<p class="fw-semibold mb-1">Progreso nivel {{ $experienceProgress->level() }} → {{ $experienceProgress->nextLevel() }}</p><p class="small text-secondary mb-2">Siguiente nivel: {{ $experienceProgress->nextLevelExperience() }} EXP acumulada</p><div class="d-flex justify-content-between small mb-1"><span>{{ $experienceProgress->experienceInLevel() }} / {{ $experienceProgress->experienceRequiredInLevel() }} EXP</span><span>{{ $experienceProgress->percentage() }}%</span></div><div class="progress mb-2" role="progressbar" aria-label="Progreso de experiencia hacia el nivel {{ $experienceProgress->nextLevel() }}" aria-valuenow="{{ $experienceProgress->percentage() }}" aria-valuemin="0" aria-valuemax="100"><div class="progress-bar" style="width: {{ $experienceProgress->percentage() }}%">{{ $experienceProgress->percentage() }}%</div></div><p class="small mb-0">Faltan <strong>{{ $experienceProgress->experienceRemaining() }} EXP</strong></p>@endif</div></div></div><div class="col-lg-8">
<div class="card mb-3"><div class="card-header"><h2 class="h5 mb-0">Estadísticas base almacenadas</h2></div><div class="card-body"><div class="row g-3">@foreach(['Vida máxima base'=>$character->base_max_health,'Ataque base'=>$character->base_attack,'Defensa base'=>$character->base_defense,'Precisión base'=>$character->base_accuracy,'Evasión base'=>$character->base_evasion,'Crítico base'=>$character->base_critical_rate.'%'] as $label=>$value)<div class="col-md-6"><div class="border rounded p-3 d-flex justify-content-between"><span>{{ $label }}</span><strong>{{ $value }}</strong></div></div>@endforeach</div></div></div>
<div id="effective-stats" class="card"><div class="card-header d-flex justify-content-between"><h2 class="h5">Estadísticas efectivas</h2><span class="badge bg-primary">Poder {{ $stats->power() }}</span></div><div class="card-body"><p>Vida efectiva <strong>{{ $stats->currentHealth() }} / {{ $stats->maxHealth() }}</strong></p><div class="row g-3">@foreach(['Ataque'=>$stats->attack(),'Defensa'=>$stats->defense(),'Precisión'=>$stats->accuracyRate().'%','Evasión'=>$stats->evasionRate().'%','Probabilidad crítica'=>$stats->criticalChance().'%','Multiplicador crítico'=>'x'.$stats->criticalDamageMultiplier(),'Velocidad de ataque'=>$stats->attackSpeed(),'Reducción de daño'=>$stats->damageReductionRate().'%','Bonus de loot'=>$stats->lootBonus().'%','Bonus de experiencia'=>$stats->experienceBonus().'%','Bonus de oro'=>$stats->goldBonus().'%','Poder total'=>$stats->power()] as $label=>$value)<div class="col-md-6"><div class="border rounded p-3 d-flex justify-content-between"><span>{{ $label }}</span><strong>{{ $value }}</strong></div></div>@endforeach</div></div></div></div></div>
@endsection
