@extends('layouts.game')
@section('title',$character->name)
@php($breadcrumbs=[['label'=>'Inicio','url'=>route('dashboard')],['label'=>'Mi personaje','url'=>route('characters.show',$character)],['label'=>'Resumen y estadísticas','url'=>null]])
@section('content')
@if(session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
@if($errors->has('equipment'))<div class="alert alert-danger">{{ $errors->first('equipment') }}</div>@endif
<div class="mb-4"><h1 class="fs-3 mb-1">{{ $character->name }}</h1><p class="text-secondary">Ficha inicial del personaje</p></div>
<div class="row g-3"><div class="col-lg-4"><div class="card h-100"><div class="card-body">
<div class="text-center mb-3"><x-media.portrait :model="$character" :alt="'Retrato de '.$character->name" :placeholder-text="$character->name" :width="160" :height="160" class="img-fluid object-fit-cover" /></div>
<h2 class="h4">{{ $character->name }}</h2><span class="badge bg-success">{{ ucfirst($character->status) }}</span><hr>
<p>Nivel <strong>{{ $experienceProgress->level() }}</strong></p><p>EXP acumulada <strong>{{ $experienceProgress->experience() }}</strong></p><p>Experiencia mínima del nivel <strong>{{ $experienceProgress->currentLevelExperience() }}</strong></p>
@if($experienceProgress->isMaximumLevel())<p class="fw-semibold mb-2">Nivel máximo actual alcanzado</p><div class="progress" role="progressbar" aria-label="Progreso de experiencia: nivel máximo" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"><div class="progress-bar" style="width:100%">100%</div></div>
@else<p class="fw-semibold mb-1">Progreso nivel {{ $experienceProgress->level() }} → {{ $experienceProgress->nextLevel() }}</p><p class="small text-secondary mb-2">Siguiente nivel: {{ $experienceProgress->nextLevelExperience() }} EXP acumulada</p><div class="d-flex justify-content-between small mb-1"><span>{{ $experienceProgress->experienceInLevel() }} / {{ $experienceProgress->experienceRequiredInLevel() }} EXP</span><span>{{ $experienceProgress->percentage() }}%</span></div><div class="progress mb-2" role="progressbar" aria-label="Progreso de experiencia hacia el nivel {{ $experienceProgress->nextLevel() }}" aria-valuenow="{{ $experienceProgress->percentage() }}" aria-valuemin="0" aria-valuemax="100"><div class="progress-bar" style="width:{{ $experienceProgress->percentage() }}%">{{ $experienceProgress->percentage() }}%</div></div><p class="small mb-0">Faltan <strong>{{ $experienceProgress->experienceRemaining() }} EXP</strong></p>@endif
</div></div></div><div class="col-lg-8">
@php($baseStats=$statsBreakdown->base())@php($equipmentStats=$statsBreakdown->equipmentBase())@php($refinementStats=$statsBreakdown->refinement())
<div id="effective-stats" class="card"><div class="card-header d-flex justify-content-between"><h2 class="h5 mb-0">Estadísticas del personaje</h2><span class="badge bg-primary">Poder {{ $stats->power() }}</span></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Estadística</th><th>Base</th><th>Equipo base</th><th>Refinamiento</th><th>Efectiva</th></tr></thead><tbody>
<tr><td>Vida máxima</td><td>{{ $baseStats->maxHealth() }}</td><td>+{{ $equipmentStats->maxHealth() }}</td><td>+{{ $refinementStats->maxHealth() }}</td><td><strong>{{ $stats->maxHealth() }}</strong></td></tr>
<tr><td>Ataque</td><td>{{ $baseStats->attack() }}</td><td>+{{ $equipmentStats->attack() }}</td><td>+{{ $refinementStats->attack() }}</td><td><strong>{{ $stats->attack() }}</strong></td></tr>
<tr><td>Defensa</td><td>{{ $baseStats->defense() }}</td><td>+{{ $equipmentStats->defense() }}</td><td>+{{ $refinementStats->defense() }}</td><td><strong>{{ $stats->defense() }}</strong></td></tr>
<tr><td>Precisión</td><td>{{ $baseStats->accuracyRate() }}%</td><td>+{{ $equipmentStats->accuracy() }}%</td><td>+{{ $refinementStats->accuracy() }}%</td><td><strong>{{ $stats->accuracyRate() }}%</strong></td></tr>
<tr><td>Evasión</td><td>{{ $baseStats->evasionRate() }}%</td><td>+{{ $equipmentStats->evasion() }}%</td><td>+{{ $refinementStats->evasion() }}%</td><td><strong>{{ $stats->evasionRate() }}%</strong></td></tr>
<tr><td>Crítico</td><td>{{ $baseStats->criticalChance() }}%</td><td>+{{ $equipmentStats->criticalChance() }}%</td><td>+{{ $refinementStats->criticalChance() }}%</td><td><strong>{{ $stats->criticalChance() }}%</strong></td></tr>
<tr><td>Velocidad de ataque</td><td>{{ $baseStats->attackSpeed() }}</td><td>+{{ $equipmentStats->attackSpeed() }}</td><td>+{{ $refinementStats->attackSpeed() }}</td><td><strong>{{ $stats->attackSpeed() }}</strong></td></tr>
</tbody></table></div><div class="card-body border-top"><p class="mb-2">Vida actual <strong>{{ $stats->currentHealth() }} / {{ $stats->maxHealth() }}</strong></p><p class="mb-2">Reducción de daño efectiva <strong>{{ $stats->damageReductionRate() }}%</strong></p><p class="mb-0">Multiplicador crítico <strong>x{{ $stats->criticalDamageMultiplier() }}</strong></p></div></div>
</div></div>
<div class="card mt-3"><div class="card-header"><h2 class="h5 mb-0">Equipamiento</h2></div><div class="card-body"><div class="row g-3">
@foreach($equipmentSummary->entries() as $equipmentEntry)@php($entry=$equipmentEntry->toArray())<div class="col-md-6"><div class="border rounded p-3 h-100"><h3 class="h6">{{ $entry['slot_label'] }}</h3>
@if($entry['occupied'])<div class="d-flex gap-3 align-items-center">@if($entry['icon_url'])<img src="{{ $entry['icon_url'] }}" width="48" height="48" alt="Icono de {{ $entry['item_name'] }}">@else<div class="border rounded d-flex align-items-center justify-content-center" style="width:48px;height:48px" aria-label="Sin icono">?</div>@endif<div><strong>{{ $entry['item_name'] }} +{{ $entry['refinement_level'] }}</strong><br><small>Ref. {{ $entry['public_reference'] }}</small></div></div>
@if(!$entry['refinement_modifier_configured'])<div class="alert alert-warning py-1 small mt-2">Sin configuración estadística activa</div>@endif<ul class="small mt-2 mb-2">@foreach($entry['total_bonuses'] as $bonusName=>$bonusValue)@if($bonusValue != 0)<li>{{ str_replace('_',' ',$bonusName) }}: base +{{ $entry['base_bonuses'][$bonusName] }} · refinamiento +{{ $entry['refinement_bonuses'][$bonusName] }} · total +{{ $bonusValue }}</li>@endif @endforeach</ul>
<form method="POST" action="{{ route('characters.equipment.unequip',$character) }}">@csrf<input type="hidden" name="slot" value="{{ $entry['slot'] }}"><button class="btn btn-sm btn-outline-secondary" type="submit">Desequipar</button></form>@else<p class="text-secondary mb-0">Vacío</p>@endif
</div></div>@endforeach
</div></div></div>
@endsection
