@extends('layouts.game')
@section('title',$character->name)
@php($breadcrumbs=[['label'=>'Inicio','url'=>route('dashboard')],['label'=>'Mi personaje','url'=>route('characters.show',$character)],['label'=>'Resumen y estadísticas','url'=>null]])
@section('content')
<div class="mb-4"><h1 class="fs-3 mb-1">{{ $character->name }}</h1><p class="text-secondary">Ficha inicial del personaje</p></div>
<div class="row g-3"><div class="col-lg-4"><div class="card h-100"><div class="card-body"><h2 class="h4">{{ $character->name }}</h2><span class="badge bg-success">{{ ucfirst($character->status) }}</span><hr><p>Nivel <strong>{{ $character->level }}</strong></p><p>Experiencia <strong>{{ $character->experience }}</strong></p></div></div></div><div class="col-lg-8">
<div class="card mb-3"><div class="card-header"><h2 class="h5 mb-0">Estadísticas base almacenadas</h2></div><div class="card-body"><div class="row g-3">@foreach(['Vida máxima base'=>$character->base_max_health,'Ataque base'=>$character->base_attack,'Defensa base'=>$character->base_defense,'Precisión base'=>$character->base_accuracy,'Evasión base'=>$character->base_evasion,'Crítico base'=>$character->base_critical_rate.'%'] as $label=>$value)<div class="col-md-6"><div class="border rounded p-3 d-flex justify-content-between"><span>{{ $label }}</span><strong>{{ $value }}</strong></div></div>@endforeach</div></div></div>
<div id="effective-stats" class="card"><div class="card-header d-flex justify-content-between"><h2 class="h5">Estadísticas efectivas</h2><span class="badge bg-primary">Poder {{ $stats->power() }}</span></div><div class="card-body"><p>Vida efectiva <strong>{{ $stats->currentHealth() }} / {{ $stats->maxHealth() }}</strong></p><div class="row g-3">@foreach(['Ataque'=>$stats->attack(),'Defensa'=>$stats->defense(),'Precisión'=>$stats->accuracyRate().'%','Evasión'=>$stats->evasionRate().'%','Probabilidad crítica'=>$stats->criticalChance().'%','Multiplicador crítico'=>'x'.$stats->criticalDamageMultiplier(),'Velocidad de ataque'=>$stats->attackSpeed(),'Reducción de daño'=>$stats->damageReductionRate().'%','Bonus de loot'=>$stats->lootBonus().'%','Bonus de experiencia'=>$stats->experienceBonus().'%','Bonus de oro'=>$stats->goldBonus().'%','Poder total'=>$stats->power()] as $label=>$value)<div class="col-md-6"><div class="border rounded p-3 d-flex justify-content-between"><span>{{ $label }}</span><strong>{{ $value }}</strong></div></div>@endforeach</div></div></div></div></div>
@endsection
