@extends('layouts.game')
@section('title','Admin · '.$monster->name)
@section('content')
@include('admin.content.partials.navigation') @include('admin.content.partials.messages')
<div class="d-flex justify-content-between mb-3"><div class="d-flex align-items-center gap-3"><img src="{{ $catalogImage->url128() }}" alt="Retrato de {{ $monster->name }}" width="128" height="128" class="catalog-image-preview"><h1>{{ $monster->name }}</h1></div><a class="btn btn-outline-primary" href="{{ route('admin.content.monsters.edit',$monster) }}">Editar estadísticas</a></div>
<div class="card mb-3"><div class="card-body"><div class="row">@foreach(['code','level','max_health','attack','defense','accuracy_rate','evasion_rate','critical_chance','experience_reward','gold_min','gold_max','status'] as $field)<div class="col-md-3 mb-2"><small>{{ $field }}</small><strong class="d-block">{{ $monster->{$field} }}</strong></div>@endforeach</div></div></div>
<h2 class="h4">Zonas</h2><ul>@forelse($monster->zones as $zone)<li>{{ $zone->region->world->name }} › {{ $zone->region->name }} › {{ $zone->name }} (peso {{ $zone->pivot->weight }})</li>@empty<li>Sin zonas</li>@endforelse</ul>
<h2 class="h4 mt-4">Loot configurado</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Item</th><th>Probabilidad</th><th>Cantidad</th><th>Orden</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>
@forelse($lootRows as $row) @php($entry=$row['model'])<tr><td><strong>{{ $row['item']->name }}</strong><small class="d-block text-secondary">{{ $row['item']->code }} · {{ $row['item']->item_type }} · {{ $row['item']->is_stackable?'apilable':'no apilable' }}</small>@if($row['quantity_warning'])<span class="badge bg-warning text-dark">Revisar: cantidad inválida para un objeto no apilable</span>@endif</td><td>{{ $row['probability_ppm'] }} PPM <strong>({{ $row['probability_percent'] }} %)</strong></td><td>{{ $entry->minimum_quantity }} – {{ $entry->maximum_quantity }}</td><td>{{ $entry->sort_order }}</td><td><span class="badge bg-{{ $row['status_badge'] }}">{{ $row['status_label'] }}</span></td><td><details><summary class="btn btn-sm btn-outline-primary">Editar</summary><div class="border border-primary rounded p-3 mt-2" style="min-width:340px"><strong>Editando: {{ $row['item']->name }}</strong>@include('admin.content.monsters.partials.loot-form',['action'=>route('admin.content.monsters.loot.update',[$monster,$entry]),'method'=>'PUT','entry'=>$entry,'buttonLabel'=>'Guardar cambios','probabilityPercent'=>$row['probability_percent']])<button class="btn btn-link p-0 mt-2" type="button" onclick="this.closest('details').removeAttribute('open')">Cancelar</button></div></details>@if($entry->status==='active')<form method="POST" action="{{ route('admin.content.monsters.loot.deactivate',[$monster,$entry]) }}" class="d-inline">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-warning">Desactivar</button></form>@elseif($entry->status==='inactive')<form method="POST" action="{{ route('admin.content.monsters.loot.activate',[$monster,$entry]) }}" class="d-inline">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-success">Activar</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="text-secondary">No hay loot configurado.</td></tr>@endforelse
</tbody></table></div>
<div class="card mt-4"><div class="card-header"><h3 class="h5 mb-0">Agregar nueva entrada de loot</h3></div><div class="card-body">@include('admin.content.monsters.partials.loot-form',['action'=>route('admin.content.monsters.loot.store',$monster),'method'=>'POST','entry'=>null,'buttonLabel'=>'Agregar entrada','probabilityPercent'=>'100.0000'])</div></div>
@endsection
