<?php
namespace App\Http\Controllers;
use App\Domain\Hunts\Sessions\Exceptions\ActiveHuntingSessionExistsException;use App\Domain\Hunts\Sessions\HuntingSessionPresentationService;use App\Domain\Hunts\Sessions\HuntingSessionService;use App\Domain\Inventory\Capacity\Exceptions\InsufficientPendingRewardCapacityException;use App\Models\Character;use App\Models\HuntingSession;use App\Models\Zone;use Illuminate\Http\Request;
class CharacterHuntingSessionController extends Controller{
public function store(Request $request,Character $character,Zone $zone,HuntingSessionService $service){$this->authorize('view',$character);try{$result=$service->start($character,$zone);return redirect()->route('characters.hunting-sessions.show',[$character,$result->id()]);}catch(ActiveHuntingSessionExistsException $e){return$this->capacityError($request,$zone,$e->getMessage(),null);}catch(InsufficientPendingRewardCapacityException $e){return$this->capacityError($request,$zone,$e->getMessage(),$e->capacity()->toArray());}}
private function capacityError(Request $request,Zone $zone,$message,$capacity){if($request->expectsJson())return response()->json(['message'=>$message,'inventory_capacity'=>$capacity],422);return redirect()->route('zones.show',$zone)->withErrors(['hunt'=>$message]);}
public function show(Character $character,HuntingSession $huntingSession,HuntingSessionService $service,HuntingSessionPresentationService $presentation){$this->authorize('view',$character);$huntingSession->loadMissing('zone.region.world');return view('characters.hunting-sessions.show',['character'=>$character,'session'=>$service->show($character,$huntingSession)->toArray(),'presentation'=>$presentation->prepare($character,$huntingSession->zone),'zonesUrl'=>route('worlds.show',$huntingSession->zone->region->world)]);}
public function tick(Character $character,HuntingSession $huntingSession,HuntingSessionService $service){$this->authorize('view',$character);return response()->json($service->tick($character,$huntingSession)->toArray());}
public function stop(Request $request,Character $character,HuntingSession $huntingSession,HuntingSessionService $service){$this->authorize('view',$character);$result=$service->stop($character,$huntingSession);if($request->expectsJson())return response()->json($result->toArray());return redirect()->route('characters.hunting-sessions.show',[$character,$huntingSession])->with('status','Cacería conectada detenida.');}
}
