<?php
namespace App\Models;
use App\Domain\Inventory\Instances\ItemInstanceLimits;use App\Domain\Inventory\Instances\ItemInstanceStatus;use App\Domain\Inventory\ItemClassification;use Illuminate\Database\Eloquent\Factories\HasFactory;use Illuminate\Database\Eloquent\Model;use LogicException;
class ItemInstance extends Model
{
    use HasFactory;protected $guarded=[];protected $casts=['item_rarity_id'=>'integer','refinement_level'=>'integer','acquired_at'=>'datetime'];
    protected static function booted()
    {
        static::creating(function($m){if(!$m->item_rarity_id&&$m->item_id){$item=Item::whereKey($m->item_id)->first();$common=$item?$item->allowedRarities()->where('code','common')->first():null;if($common)$m->item_rarity_id=$common->id;}$valid=$m->character_id&&$m->item_id&&$m->item_rarity_id&&$m->uuid&&$m->origin_type&&$m->origin_id&&$m->origin_unit_index&&$m->acquired_at&&in_array($m->status,ItemInstanceStatus::values(),true)&&$m->refinement_level>=ItemInstanceLimits::MIN_REFINEMENT_LEVEL&&$m->refinement_level<=ItemInstanceLimits::MAX_REFINEMENT_LEVEL;if(!$valid)throw new LogicException('Invalid ItemInstance.');$item=Item::whereKey($m->item_id)->first();try{$unique=$item&&(new ItemClassification())->classify($item)===ItemClassification::UNIQUE;}catch(\InvalidArgumentException $e){$unique=false;}if(!$unique)throw new LogicException('ItemInstance requires a coherent unique Item.');if(!$item->allowedRarities()->whereKey($m->item_rarity_id)->exists()&&!static::persistedRewardAllowsRarity($m))throw new LogicException('ItemInstance rarity is not allowed for this Item.');});
        static::updating(function($m){foreach(['uuid','item_rarity_id','origin_type','origin_id','origin_unit_index','acquired_at']as$field)if($m->isDirty($field))throw new LogicException('ItemInstance identity, rarity and origin are immutable.');if($m->isDirty('status')&&(!in_array($m->status,ItemInstanceStatus::values(),true)||!ItemInstanceStatus::canTransition($m->getOriginal('status'),$m->status)))throw new LogicException('Invalid ItemInstance status transition.');if($m->isDirty('refinement_level')&&((int)$m->refinement_level<ItemInstanceLimits::MIN_REFINEMENT_LEVEL||(int)$m->refinement_level>ItemInstanceLimits::MAX_REFINEMENT_LEVEL))throw new LogicException('Invalid ItemInstance refinement level.');});
    }
    private static function persistedRewardAllowsRarity($m){if($m->origin_type==='hunt_reward_item')return HuntRewardItem::whereKey($m->origin_id)->where('item_id',$m->item_id)->where('item_rarity_id',$m->item_rarity_id)->exists();if($m->origin_type==='combat_pending_reward_item')return CombatPendingRewardItem::whereKey($m->origin_id)->where('item_id',$m->item_id)->where('item_rarity_id',$m->item_rarity_id)->exists();return false;}
    public function getRouteKeyName(){return'uuid';}public function isAvailable(){return$this->status===ItemInstanceStatus::AVAILABLE;}public function isEquipped(){return$this->status===ItemInstanceStatus::EQUIPPED;}public function isSold(){return$this->status===ItemInstanceStatus::SOLD;}public function character(){return$this->belongsTo(Character::class);}public function item(){return$this->belongsTo(Item::class);}public function itemRarity(){return$this->belongsTo(ItemRarity::class);}public function events(){return$this->hasMany(ItemInstanceEvent::class);}public function equipment(){return$this->hasOne(CharacterEquipment::class);}
}
