<?php
namespace App\Domain\Equipment;
use App\Domain\Equipment\Data\CharacterEquipmentEntry;use App\Domain\Equipment\Data\CharacterEquipmentSummary;use App\Domain\Inventory\Instances\Data\ItemInstanceEntry;use App\Domain\Inventory\Instances\ItemInstanceStatus;use App\Domain\Inventory\Instances\Rarity\ItemRarityVisualStyleResolver;use App\Domain\Media\MediaAssetType;use App\Models\Character;use App\Models\Item;use InvalidArgumentException;
final class CharacterEquipmentSummaryService
{
    private $validator;private $rarityVisuals;
    public function __construct(EquippableItemValidator $validator,ItemRarityVisualStyleResolver $rarityVisuals){$this->validator=$validator;$this->rarityVisuals=$rarityVisuals;}
    public function snapshot(Character $character,array $statSources=[])
    {
        $rows=$character->equipment()->with('itemInstance.itemRarity')->orderBy('id')->get();$itemIds=$rows->map(function($row){return$row->itemInstance?$row->itemInstance->item_id:null;})->filter()->unique();$items=$itemIds->isEmpty()?collect():Item::whereIn('id',$itemIds)->with(['mediaAssets'=>function($q){$q->where('asset_type',MediaAssetType::ICON)->orderByDesc('is_primary')->orderBy('sort_order')->orderBy('id');}])->get()->keyBy('id');$sources=collect($statSources)->keyBy('item_instance_uuid');$bySlot=$rows->keyBy('slot');$entries=[];
        foreach(CharacterEquipmentSlot::all()as$slot){$row=$bySlot->get($slot);if(!$row){$entries[]=new CharacterEquipmentEntry(['slot'=>$slot,'slot_label'=>CharacterEquipmentSlot::label($slot),'occupied'=>false,'item_instance_uuid'=>null,'public_reference'=>null,'item_id'=>null,'item_code'=>null,'item_name'=>null,'refinement_level'=>null,'status'=>null,'icon_url'=>null,'bonuses'=>[],'base_bonuses'=>[],'refinement_bonuses'=>[],'rarity_bonuses'=>[],'total_bonuses'=>[],'eligibility_current'=>true,'eligibility_reason_codes'=>[],'eligibility_message'=>null]);continue;}$instance=$row->itemInstance;$item=$instance?$items->get($instance->item_id):null;if(!$instance||!$item||(int)$instance->character_id!==(int)$character->id||$instance->status!==ItemInstanceStatus::EQUIPPED)throw new InvalidArgumentException('Inconsistent character equipment state.');$this->validator->assertCompatible($item,$slot);$asset=$item->mediaAssets->first();$source=$sources->get($instance->uuid);$base=$source?$source['base_bonuses']:$this->validator->bonuses($item)->toArray();$refined=$source?$source['refinement_bonuses']:[];$rarity=$source&&isset($source['rarity_bonuses'])?$source['rarity_bonuses']:[];$total=$source?$source['total_bonuses']:$base;$visual=$this->rarityVisuals->resolve($instance->itemRarity);
            $entries[]=new CharacterEquipmentEntry(['slot'=>$slot,'slot_label'=>CharacterEquipmentSlot::label($slot),'occupied'=>true,'item_instance_uuid'=>$instance->uuid,'public_reference'=>ItemInstanceEntry::publicReferenceFor($instance->uuid),'item_id'=>(int)$item->id,'item_code'=>$item->code,'item_name'=>$item->name,'refinement_level'=>(int)$instance->refinement_level,'status'=>$instance->status,'icon_url'=>$asset?$asset->url():null,'rarity_id'=>(int)$instance->itemRarity->id,'rarity_code'=>$instance->itemRarity->code,'rarity_name'=>$instance->itemRarity->name,'rarity_visual_style'=>$instance->itemRarity->visual_style,'rarity_bonuses'=>$rarity,'rarity_visual'=>$visual->toArray(),'css_variables'=>$visual->cssVariables(),'rarity_visual_style_attribute'=>$visual->inlineStyle(),'bonuses'=>$total,'base_bonuses'=>$base,'refinement_bonuses'=>$refined,'total_bonuses'=>$total,'refinement_modifier_configured'=>$source?$source['refinement_modifier_configured']:((int)$instance->refinement_level===0),'refinement_modifier_basis_points'=>$source?$source['refinement_modifier_basis_points']:null,'eligibility_current'=>$source&&array_key_exists('eligibility_current',$source)?$source['eligibility_current']:true,'eligibility_reason_codes'=>$source&&isset($source['eligibility_reason_codes'])?$source['eligibility_reason_codes']:[],'eligibility_message'=>$source&&isset($source['eligibility_message'])?$source['eligibility_message']:'Requisitos cumplidos.']);
        }return new CharacterEquipmentSummary($entries);
    }
}
