<section class="card h-100" aria-labelledby="overview-equipment-heading"><div class="card-header"><h2 id="overview-equipment-heading" class="h5 mb-0">Equipamiento</h2></div><div class="card-body"><div class="overview-equipment-grid">
@foreach($overview['equipment'] as $entry)<article class="overview-slot {{ $entry['occupied'] ? 'overview-slot--occupied item-rarity-visual' : '' }}" @if($entry['occupied']) style="{{ $entry['rarity_visual_style_attribute'] }}" @endif @if(!empty($entry['visual_only'])) aria-disabled="true" title="Las mascotas estarán disponibles próximamente." @endif><span class="overview-slot-label">{{ $entry['slot_label'] }}</span>
  @if($entry['occupied'])
    <button type="button" class="overview-item-button" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{{ implode(' · ',$entry['details']) }}" data-overview-open-panel="equipment-{{ $entry['slot'] }}" aria-label="Ver acciones de {{ $entry['item_name'] }}">@if($entry['icon_url'])<img src="{{ $entry['icon_url'] }}" alt="" width="64" height="64" loading="lazy" decoding="async">@else<span class="overview-item-placeholder" aria-hidden="true"><i class="ti ti-shield"></i></span>@endif<span class="overview-item-name">{{ $entry['item_name'] }} +{{ $entry['refinement_level'] }}</span><span class="badge item-rarity item-rarity--{{ $entry['rarity_visual_style'] }}">{{ $entry['rarity_name'] }}</span><small class="overview-instance-reference">Instancia #{{ $entry['public_reference'] }}</small></button>
    <template id="equipment-{{ $entry['slot'] }}"><img data-panel-image src="{{ $entry['detail_icon_url'] }}" alt="" width="128" height="128" class="catalog-image-preview mb-3"><div data-panel-title>{{ $entry['item_name'] }} +{{ $entry['refinement_level'] }}</div><ul data-panel-details>@foreach($entry['details'] as $detail)<li>{{ $detail }}</li>@endforeach</ul><div data-panel-actions><form method="POST" action="{{ $entry['unequip_url'] }}" data-character-overview-mutation>@csrf<input type="hidden" name="slot" value="{{ $entry['slot'] }}"><button type="submit" class="btn btn-outline-danger w-100">Desequipar</button></form></div></template>
  @elseif(!empty($entry['visual_only']))<span class="overview-empty-slot"><i class="ti ti-paw"></i><span>Placeholder</span><span class="badge bg-secondary">Próximamente</span></span>
  @else<span class="overview-empty-slot"><i class="ti ti-square-rounded"></i><span>Vacío</span></span>@endif
</article>@endforeach
</div></div></section>
